### ISSUE TITLE
Is there a way to get the scenario name in my step definitions

### ISSUE THREAD

**Issue by TheGeminii** [badeball/cypress-cucumber-preprocessor#104]
Hi,

I am happily using your framework but was wondering if I can get the scenario name in a step definition. I've used cucumberjs in the past and there I could do:
` Before((scenario) => {
        console.log('\nscenario: ', scenario.pickle.name);
    });` 

Does the preprocessor expose the scenario name in any way to the step definitions?

**Comment by flowt-au** [comment]
It seems to do that:

    Feature: Test Microservice

        As a user I want to start the app

        Scenario: Start app for ms
            Given I start the ms app
            Then I should see something

![cypress1](https://user-images.githubusercontent.com/37637590/47544983-9456a300-d935-11e8-877b-53131ab54f50.png)

1 Feature
2 Scenario
3 Given
4 Then
Or maybe you mean something else?
Murray

**Comment by flowt-au** [comment]
Oh yes, I see. I misread the question. Sorry.

**Comment by TheGeminii** [comment]
> I think he wants to get the value of that name to be able to use it inside the code, not just to display it in the cypress. I'm not aware at this point how to do this, we would possibly have to pass some more info as a context.

Maybe it's already available using the Cypress api: https://docs.cypress.io/api/cypress-api/spec.html#Syntax

haven't tried it, will try on monday....

**Comment by lgandecki** [comment]
Looks like this will give you the feature file name, but not a particular scenario I'm afraid..

**Comment by hackel** [comment]
If the scenario doesn't have any examples, you can get the scenario name from `cy.state('ctx').test.title`.  Otherwise the name will look like `${scenarioName} (example #${index + 1})`.

**Comment by hardikrana437** [comment]
> If the scenario doesn't have any examples, you can get the scenario name from `cy.state('ctx').test.title`. Otherwise the name will look like `${scenarioName} (example #${index + 1})`.

cy.state doesn't exist on typescript definitions. Is there any way to get the scenario name in my step definitions in ts.

**Comment by symon-skelly** [comment]
This works perfectly for me, though I'm not using TS, the logic behind it  should give you a good starting point:

`const _onRunnableRun = Cypress.runner.onRunnableRun

Cypress.runner.onRunnableRun = function (runnableRun, runnable, args) {
  const r = runnable
  const test = r.ctx.currentTest.title
}`

test = the current scenario name.

**Comment by adadache** [comment]
Of course:

`window.testState.currentScenario`

This is where all your data relies.

**Comment by vivekvasu** [comment]
Any workflow for Typescript users ?

**Comment by tongilcoto** [comment]
> Of course:
> 
> `window.testState.currentScenario`
> 
> This is where all your data relies.

Please, could you post also a link to this object reference ?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
