### ISSUE TITLE
Silent failure in the preprocessor

### ISSUE THREAD

**Issue by javier-crowdar** [badeball/cypress-cucumber-preprocessor#1058]
### Current behavior

When there is an error in the preprocessor to interpret the .feature, the user is not notified in any way and "an old version of the project" is executed.

### Desired behavior

missing error message and stop execution 

### Test code to reproduce

Given any project, feature:

```
Feature: duckduckgo.com
  Scenario: visiting the front page
    When I visit duckduckgo.com
    Then I should see a search bar
```

`cypress run`

runs successfully

I change the language to Spanish and the feature with some mistaken keyword (for example "Scenario" in English instead of Spanish)

```
# language: es
Característica: google.com
  Scenario: visiting the frontpage
    Cuando I visit google.com
    Entonces I should see a search bar
```

This results in a successful execution but the first feature is executed again and not the changes I made

It doesn't only happen because of the languages, it also happened to me for defining a rule wrong, any error that doesn't allow interpreting the feature

debug:
✘ [ERROR] (49:4): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #RuleLine, #Comment, #Empty, got 'Scenario: visiting the frontpage' [plugin feature]

### Versions

    Cypress version: 12.17.1
    Preprocessor version: 18.0.1
    Node version: v18.16.0

### Checklist

- 

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).

- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment]
Furthermore, it's not clear whether you're talking about open- or run-mode here.

**Comment by DmytroSoninLinguahouse** [comment]
Noticed the same issue. If `.feature` fails to compile it does so silently and the cypress just uses the cached version from `.config/Cypress/cy/production` (on Ubuntu). So if you had a working test, but then, for example, in one of command definition files messed something up and included a broken import or any other error that would cause the code to fail at runtime - you'll never know about that, because it will not notify you about the failure and Cypress continue to use previously compiled code.

**Comment by badeball** [comment]
Aha, I see what you mean. I can also observe the same behavior when using `@bahmutov/cypress-esbuild-preprocessor` _without_ `@badeball/cypress-cucumber-preprocessor` (as seen below), which tells me that the problem lies therein.

```js
// "Vanilla" Cypress (IE. without cypress-cucumber-preprocessor), with above-mentioned behavior.
const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");

module.exports = defineConfig({
  e2e: {
    video: false,
    setupNodeEvents(on, config) {
      on("file:preprocessor", createBundler());
    },
  },
});
```

Closing as duplicate of https://github.com/badeball/cypress-cucumber-preprocessor/issues/786 and https://github.com/bahmutov/cypress-esbuild-preprocessor/issues/195.

Sadly, the issue mentioned hasn't gotten a lot of attention. I recommend users suffering from this, to try and contribute in the form of maybe a PR.

**Comment by badeball** [comment]
https://github.com/bahmutov/cypress-esbuild-preprocessor/issues/380 was recently fixed and closed. @javier-crowdar and @DmytroSoninLinguahouse, can you try using the latest @bahmutov/cypress-esbuild-preprocessor (v2.2.7) and see if the behavior is changed?
