### ISSUE TITLE
add tag to datatable seems didnt work

### ISSUE THREAD

**Issue by qileilove** [badeball/cypress-cucumber-preprocessor#128]
![image](https://user-images.githubusercontent.com/3895501/49981677-f9bd2c80-ff93-11e8-85b1-0268443a8b32.png)
im trying use the tag for datatable, it seems not working. but in java cucumber it support this feature, how do i implement this feature?

**Comment by lgandecki** [comment]
Hello @qileilove 

This feature might indeed be not implemented at this point. I'm happy to take a PR. If you need this for work but don't have time, or knowledge, to create a PR - we are happy to build this feature for you, if your company would be willing to sponsor it. :) Please contact us if interested. 

Thanks!

**Comment by jun1983** [comment]
I might have the same problem. I try to ignore some examples with a tag on it. Seems not working

**Comment by dankopetrovic** [comment]
This is not working for me as well.
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/TagsImplementationWithEnvSetExamplesLevel.feature

It doesn't find the '@test-tag' inside 'TagsImplementationWithEnvSetExamplesLevel.feature' file.

`npx cypress-tags run -e TAGS='@test-tag'

Using cypress.json configuration:
Spec files:  cypress/integration/**/*.feature

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    8.1.0                                                                              │
  │ Browser:    Electron 89 (headless)                                                             │
  │ Specs:      2 found (TagsImplementationWithEnvSet.feature, TagsImplementationWithEnvSetScenari │
  │             oLevel.feature)                                                                    │
  │ Searched:   cypress/integration/TagsImplementationWithEnvSet.feature, cypress/integration/Tags │
  │             ImplementationWithEnvSetScenarioLevel.feature                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘`

`(Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  TagsImplementationWithEnvSet.featur      112ms        3        3        -        -        - │
  │    e                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  TagsImplementationWithEnvSetScenari       78ms        2        1        -        1        - │
  │    oLevel.feature                                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        190ms        5        4        -        1        -  `

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
