### ISSUE TITLE
Fun cypress cucumber screenshot recipe

### ISSUE THREAD

**Issue by zhammer** [badeball/cypress-cucumber-preprocessor#158]
since `*` is a valid gherkin step keyword, if you want to take screenshots / do visual regression testing during your cucumber cypress tests in a non-intrusive way, you can define the step:
```js
When('Snap! *', () => {
  cy.then(() => {
    cy.screenshot();
  });
});
```

and then write `* Snap! *` anywhere in your cucumber specs to take a picture:
```feature
Feature: I can take screenshots of my app right from my cucumber cypress specs!
  Scenario: I visit my user page
    Given I am on the home page
    * Snap! *
    When I click on my user icon
    * Snap! *
    Then I see "Zach's Website"
    * Snap! *
```

**Comment by zhammer** [comment]
also if you want to optionally add filenames

`* Snap! "main page" *`
```js
When(/Snap! (?:(.*)\s+)?\*/, fileName => {
  cy.then(() => {
    if (fileName) {
      cy.screenshot(fileName);
    }
    cy.screenshot();
  });
});
```

**Comment by Tay08** [comment]
@zhammer any news about this issue?

**Comment by lgandecki** [comment]
What do you mean @Tay08 ? It's a recipe - feel free to use it in your project as explained here

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
