### ISSUE TITLE
Running cypress from another directory - Error: Step implementation missing for

### ISSUE THREAD

**Issue by claudiunicolaa** [badeball/cypress-cucumber-preprocessor#177]
Hi,

If I open cypress from the project root (`npx cypress open`) and run a scenario (`.feature` file), I received the following message: 
<img width="1552" alt="Screenshot 2019-06-10 at 23 00 56" src="https://user-images.githubusercontent.com/15197275/59223065-b60a4f00-8bd3-11e9-97ba-8eb6dd20eb06.png">

I created a repository that simulates my project structure (https://github.com/claudiunicolaa/cypress-demo).

If I open cypress from `e2e` directory and run a scenario, everything works fine.

How can I specify where to find the scenario steps?

Thanks!

**Comment by artkuznetsov** [comment]
+1. The same problem.

**Comment by eyup-aydin** [comment]
same here

**Comment by Kailash1980** [comment]
I am getting Was unable to find a step for "Then I see "Google" in the title"

Can anyone help .. I cross-check 2-3 time all mapping (b/w feature file and .js file is fine)

**Comment by Kailash1980** [comment]
Hi,

If I open cypress from the project root (./node_modules/.bin/cypress open) and run a scenario (.feature file), I received the following message:

Was unable to find step for "When I enter valid credentials"

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
