### ISSUE TITLE
Error: inconsistent cell count within the table

### ISSUE THREAD

**Issue by amitguptagwl** [badeball/cypress-cucumber-preprocessor#205]
I have `|` in my data.

```cucumber
Then I see selected device summary as follows
      | subheading      | content                                   |
      | <subHeading1>   | <variant> \\| <color> \\| <capacity>        |
```
When I run tests from console and use `\\|` it gives compile time error and does not start the tests. When I use `\|` it gives run time error and fails the tests. 

If I use cypress dashboard then the issue is reverse i.e. `\|` it gives compile time  error and  `\\|` gives run time error.

**Comment by lgandecki** [comment]
you found an edge-case bug! Should be an easy fix. Wanna try making a PR?

**Comment by amitguptagwl** [comment]
Though I'm not aware with the code in this repo. But yes, I'll try to raise a PR today.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
