### ISSUE TITLE
Error when running with Gherkin 7.0

### ISSUE THREAD

**Issue by aleccool213** [badeball/cypress-cucumber-preprocessor#206]
Steps to reproduce:

1. Get some cypress-cucumber-preprocessor tests working with gherkin 5.0
2. Upgrade to Gherkin 7.0
3. Run cypress tests

<img width="1358" alt="Screenshot at Aug 19 10-37-49" src="https://user-images.githubusercontent.com/6475934/63274257-787a1000-c26d-11e9-9065-10237211de49.png">

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
