### ISSUE TITLE
step_definitions under the test root

### ISSUE THREAD

**Issue by mstruensee** [badeball/cypress-cucumber-preprocessor#207]
Can we have this feature added?
https://www.jetbrains.com/help/idea/navigating-from-feature-file-to-step-definition.html

You cannot navigate to a step definition file, if it resides outside a package under the test root.
```
    if (loaded && loaded.config && loaded.config.stepDefinitionsAtTestRoot) {
      const testRootPattern = `${path.dirname(
        filePath
      )}/step_definitions/**/*.+(js|ts)`;
      paths = paths.concat(glob.sync(testRootPattern));
    }
```

I can open a PR if so desired.

**Comment by lgandecki** [comment]
Hello @mstruensee 

I'm sorry. I'm not sure I understand. Navigating from feature file to step definition works, and there is not much we can do in our package about it. If you have .feature files, and then .js file that follow Cucumber syntax, they will get resolved. 

Do you want to add a functionality for what happens when the step definition resides outside a package under the test root? So basically what jetbrains documentation says we can't do?

Please do open a PR if it's trivial, with some simple repo that demonstrates what you are trying to do.
If the PR is not so trivial - please at least make a repo with some additional explanation so I can take a look.

**Comment by mstruensee** [comment]
see my [modifications](https://github.com/mstruensee/cypress-cucumber-example) to your example repo, with the JS files inside of news/step_definitions I can navigate to them with CMD + CLICK (on a mac). 

`Then I see "Google" in the title` I **cannot** because it is outside the test root, it is in common (so for me, I would put it inside of test root for intellisense, but left it outside for now)

<img width="836" alt="Screen Shot 2019-08-20 at 8 30 23 AM" src="https://user-images.githubusercontent.com/5142984/63351582-1e3c8600-c325-11e9-8609-9d5982cd8384.png">

Now I rename news/step_definitions to the original name, news/Google ... and I then lose my intellisense/ability to navigate to it ... (To see this actually work, rename, restart IntelliJ)

<img width="739" alt="Screen Shot 2019-08-20 at 8 34 29 AM" src="https://user-images.githubusercontent.com/5142984/63351708-5cd24080-c325-11e9-9677-77d932c68765.png">

As you can see the [code](https://github.com/mstruensee/cypress-cucumber-preprocessor/commit/c1f851b24b00e47954f8b26c355a97c87ac3c762#diff-91133cdad4756a22d3077dcac0c6f7bdR23) is pretty trivial.  Just an IF check, with a config flag to enable it.

Let me know, I can request a PR from my fork.

**Comment by mstruensee** [comment]
PR raised, we have decided to use cypress/cypress-cucumber-preprocessor so we would like this feature.

**Comment by jcundill** [comment]
@mstruensee  can you check https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/215#issuecomment-524422915 on your PR. Resolving step definitions seems to already work fine 'out of the box' with the latest Webstorm releases.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
