### ISSUE TITLE
LocalStorage bug

### ISSUE THREAD

**Issue by tgrrr** [badeball/cypress-cucumber-preprocessor#209]
When I try and get something from localStorage in cypress, I have no problems:

```js
describe('Test', () => {
  it('rubs the lotion on its skin', () => {
    cy.visit('/');
    cy.wait(2000);

    const LOCAL_STORAGE_KEY = 'local_storage_key';
    const testLocalStorage = `{"watchlist":[4571,29874]}`;
    cy.get('[data-testid=WatchlistButton]')
      .click().should(() => {
        console.log('local_storage_', localStorage.getItem(LOCAL_STORAGE_KEY));
        expect(localStorage.getItem(LOCAL_STORAGE_KEY)).to.eq(testLocalStorage);
      });
  });
});
```
When I try to do the same with Cypress Cucumber PreProcessor, localStorage is `null`:

```js
Given(/I visit the homepage$/, () => {
  cy.visit('/');
  cy.wait(2000);
});

When(/^I reload the homepage$/, () => {

  const testLocalStorage = `{"watchlist":[4571,29874]}`;
  const LOCAL_STORAGE_KEY = 'indiefilm_local_storage_key';

  cy.get('[data-testid=WatchlistButton')
    .click().should(() => {
      expect(localStorage.getItem(LOCAL_STORAGE_KEY)).to.eq(testLocalStorage); // fails
    });

  cy.window().then(
    win => console.log(win.localStorage.getItem(LOCAL_STORAGE_KEY)) // returns null
  );
  cy.reload();
});

Then(/^The state persists$/, () => {
  const testLocalStorage = `{"watchlist":[4571,29874]}`;
  expect(localStorage.getItem(LOCAL_STORAGE_KEY)).to.eq(testLocalStorage); 
  // fails because it returns null
});
```

Versions:
```js
    "react": "^16.8.6",
    "cypress": "^3.2.0",
    "cypress-cucumber-preprocessor": "^1.12.0",
```

**Comment by lgandecki** [comment]
Hey @tgrrr , thanks for reporting this!
Any chance you could create a simple repro and put it on github?

**Comment by jboz** [comment]
did you find a workaround?

**Comment by BirgitPohl** [comment]
Is there a possibility that a "test" in Cypress could mean a step in Cucumber? Meaning, before each call from Cucumber Cypress clears the local storage?

["Cypress automatically runs this command before each test to prevent state from being shared across tests."](https://docs.cypress.io/api/commands/clearlocalstorage.html#Syntax)

**Comment by badeball** [comment]
No, that is not the case. @BirgitPohl, if you're experiencing the same thing, can you provide a minimal repository to reproduces the issue?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
