### ISSUE TITLE
Location of scoped step definitions for logically grouped features

### ISSUE THREAD

**Issue by amitguptagwl** [badeball/cypress-cucumber-preprocessor#231]
I have created a folder, say **homepage** inside `cypress/integration/features` to group feature files for the same page. However, I noticed that I am supposed to create step definition folder on the root of `cypress/integration/features` not inside  `cypress/integration/features/homepage`.

**Comment by amitguptagwl** [comment]
One more issue, if I group the feature files in a subfolder, since I cant keep the folder inside the subfolder, it fails to find step definitions.

**Comment by xeger** [comment]
I have basically the same use case.

About 95% of my step definitions are `common` because they are basic browser automation things (click a button, visit a page).

About 5% of my step definitions are feature-specific, but they are reused across a number of `.feature` files.

I organize my `.feature` into directories based on functional area (`foo/*.feature`, `bar/*.feature`, etc). I need a way to create some "foo steps" shared among all of the foo features, etc.

As a workaround, I can create a subdir for _every single feature of foo_, put an `index.js` into it, and `require('../foo_steps/foo.js')`, etc. This is a huge mess.

@lgandecki I notice that you've recently merged some work with "bundles of features" i.e. `*.features` files ... I wonder, if there is any intersection between the step-location code and the bundling code that might help us out?

If not, would it be reasonable to add a _second_ location that the plugin can search for local step definitions? I'm willing to create a PR, but would want feedback on whether this is a good idea, what naming convention to use for the folder, etc.

**Comment by darrinholst** [comment]
Using the bundled `*.features` mode effectively makes all of your steps global ([noted here](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/189#issuecomment-516643873). If 95% of your steps are common anyway I'd question the benefit of making that last 5% feature specific. I turn `nonGlobalStepDefinitions` off and make it work the "oldschool" way like every other cucumber implementation. (I did give the newschool way an honest shot...it's just not for me. new dog old tricks and all that)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
