### ISSUE TITLE
Extend configuration to ban matching of ts files

### ISSUE THREAD

**Issue by ghost** [badeball/cypress-cucumber-preprocessor#240]
### Description
I am researching different ways to run step definition files written with typescript and I would like to propose the following feature:   
### Proposal
Instead of `tsify`ing files in plugins file let's allow the user to compile `.ts` files to `.js` with `tsc` and run cypress afterward.  
### Pros
Right now step definitions are being compiled on every run. This produces some problems:
* Delay before tests start (it's really annoying)
* Any compilation errors are shown inside cypress log, without details.

If we would compile ts files with `tsc` and just exclude them from files matching step definitions (we already have their's compiled version) then we will solve both of the stated problems.

### Possible solution
Let's introduce new boolean param `matchTypeScriptStepDefinitions` with default value set to true.  
I am ready to prepare PR and an example of usage if you would agree to add this feature to the project.

**Comment by DanAtSpark** [comment]
@lgandecki Hello, can you tell me, please, whether this feature is rejected or just missed?

**Comment by FrancisBourgault** [comment]
Got same issue.

I was using a package.json command that first ran ""tsc" then "cypress run/open", The problem with that approach is you need to manually re-run tsc each time you modify your code when using cypress open.

Though for performance and CI execution, it is much better to simply use "tsc" then "cypress run" and use the compile js file, rather than compiling the "ts" files using browserify for every test suites (in this case, *.features)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
