### ISSUE TITLE
Run `After` hook even if scenario failed

### ISSUE THREAD

**Issue by johnknoop** [badeball/cypress-cucumber-preprocessor#248]
Hi

I'm noticing that the `After` hook only runs when the scenario completes successfully.

Is there any way to make it run regardless of success?

I can't resort to `after` since I need tag support.

Thanks

**Comment by AlexK777** [comment]
Any other updates here? This is very valuable functionality.

**Comment by lgandecki** [comment]
Looks like @jcundill worked on that, is this still planned? :) 
We are also always happy to take PRs

**Comment by automationJatinder** [comment]
@jcundill  Any update on this please. Need this fix as this missing functionality is causing a lot of problem and I have to add different scripts for clean up.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
