### ISSUE TITLE
Could you update dependency "chokidar"?

### ISSUE THREAD

**Issue by roschaefer** [badeball/cypress-cucumber-preprocessor#250]
I'm seeing this for a while now:

![Screenshot_2019-10-11 Human-Connection Human-Connection](https://user-images.githubusercontent.com/2110676/66611930-47a8be00-ebc0-11e9-97f2-d0192d073c19.png)

I have a hard time to figure out which of our packages is to blame for the transitive dependeny, but I believe it's this one. My way to debug this:

```
robert@e480 ~/D/h/Human-Connection> yarn why set-value
yarn why v1.19.1
[1/4] Why do we have the module "set-value"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "set-value@2.0.0"
info Reasons this module exists
   - "cypress-cucumber-preprocessor#chokidar#braces#snapdragon#base#cache-base" depends on it
   - Hoisted from "cypress-cucumber-preprocessor#chokidar#braces#snapdragon#base#cache-base#set-value"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "148KB"
info Disk size with transitive dependencies: "168KB"
info Number of shared dependencies: 5
=> Found "union-value#set-value@0.4.3"
info This module exists because "cypress-cucumber-preprocessor#chokidar#braces#snapdragon#base#cache-base#union-value" depends on it.
Done in 0.47s.


robert@e480 ~/D/h/Human-Connection> yarn list --pattern set-value
yarn list v1.19.1
├─ set-value@2.0.0
├─ union-value@1.0.0
│  └─ set-value@0.4.3
└─ unset-value@1.0.0
Done in 0.44s.

robert@e480 ~/D/h/Human-Connection> yarn why union-value
yarn why v1.19.1
[1/4] Why do we have the module "union-value"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "union-value@1.0.0"
info Reasons this module exists
   - "cypress-cucumber-preprocessor#chokidar#braces#snapdragon#base#cache-base" depends on it
   - Hoisted from "cypress-cucumber-preprocessor#chokidar#braces#snapdragon#base#cache-base#union-value"
info Disk size without dependencies: "16KB"
info Disk size with unique dependencies: "80KB"
info Disk size with transitive dependencies: "212KB"
info Number of shared dependencies: 8
Done in 0.46s.
```

As far as I understand, package `set-value` got resolved to a version `0.4.3` because of a package union-value at `1.0.0` which in turn is somehow required through multiple hops by `chokidar` wich is used by `cypress-cucumber-preprocessor`. Am I right? Please tell me a better way to debug Github's security vulnerabilities and how to learn which package maintainer to ask for an update.

It looks like `chokidar` made a major version bump, so I guess if you update `chokidar` also the security vulnerability will be gone.

**Comment by roschaefer** [comment]
By the way, do you know https://dependabot.com/ ?

**Comment by lgandecki** [comment]
We've had this conversation before :)

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/190#issuecomment-511766984

Having said that - we have a good end to end test coverage now (with typescript and webpack usages), so I've decided to give this a try, since quite a few people keep asking and complaining. I don't want to be difficult and force people to change their approach to security checks because of this one package. I will be merging the security bumps today as soon as they are passing on the CI.

**Comment by roschaefer** [comment]
@lgandecki you're absolutely right, I didn't notice we had this conversation *already in this repository* :see_no_evil: at least it's another transitive dependency now (not `lodash` but `chokidar`).

Yes, it would be really great if you could merge the security bumps. It's slightly embarrassing if you do pair-programming, share your screen, show your repository to a new open-source contributor and the first thing that pops up is the security vulnerability.

Thank you for your great work!

**Comment by lgandecki** [comment]
I've done a few updates. Looks like chokidar was not proposed to be updated. :( I will update manually tomorrow..

**Comment by tanmally** [comment]
Any updates on this?  
I get an error when I run it on my Windows 10 OS.

Error: Can't walk dependency graph: Cannot find module 'fsevents' from '${Path}\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib' in Windows 10 . 

The app complains saying we have to use a version greater than 3 for chokidar

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
