### ISSUE TITLE
Help generating reports for CircleCI

### ISSUE THREAD

**Issue by santii90** [badeball/cypress-cucumber-preprocessor#264]
Hi I have been trying to make circleCI grab the json reports generated but no luck. Anyone know who I can achieve some at least basic reports?

**Comment by dylankelly** [comment]
hi @santii90 - I ended up using https://www.npmjs.com/package/cucumber-junit-convert to convert json to XML required for Circle CI to use in test reports

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
