### ISSUE TITLE
How to use custom keywords ?

### ISSUE THREAD

**Issue by renanwallace** [badeball/cypress-cucumber-preprocessor#266]
I need to translate the commands to be semantic for my language, its possible?
Example:

import * as cypressCucumber from 'cypress-cucumber-preprocessor / steps';

export const Antes = cypressCucumber.Before;
export const Depois = cypressCucumber.After;
export const E = cypressCucumber.And;
export const Quando = cypressCucumber.When;
export const Entao = cypressCucumber.The;

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
