### ISSUE TITLE
Bundle feature files work with typescript/webpack?

### ISSUE THREAD

**Issue by pkell** [badeball/cypress-cucumber-preprocessor#268]
Have tried using All.features to run all the feature files in my project that uses typescript and webpack.
It fails to find any of my feature files.
![image](https://user-images.githubusercontent.com/17783432/68472369-41861b80-0218-11ea-8cd0-206980ac279d.png)
The issue can be recreated in the cypress-cucumber-webpack-typescript-example by adding the socialNetworks feature files from cypress-cucumber-example and trying to run All.features in the integration folder.
Should this work?

**Comment by brundozer** [comment]
Same here using parcel and typescript. If my file has a _.feature_ extension, it works but not with _.features_.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
