### ISSUE TITLE
Possible to load step definitions from external package?

### ISSUE THREAD

**Issue by paulgibbs** [badeball/cypress-cucumber-preprocessor#269]
I don't believe it is currently possible, but do you have any thoughts how I might be able to achieve loading some step definitions from another npm package?

For example, I am using the non-global step definitions structure at the moment, alongside the common folder, but I want to understand if it's impossible to `require('pauls-reusable-step-definitions')` somewhere and have that load a third location of global step definitions.

**Comment by lgandecki** [comment]
hmmmm, what happens if you actually try that? since you are able to require things from packages, I guess having step definitions there might just work? if not - please try, if it doesn't work set up a simple reproduction and push to github so I can play around with it :) You could make a github repo with two packages, one with the tests, one with the step definitions, and then use npm link to connect one to another.

**Comment by paulgibbs** [comment]
@lgandecki Thanks -- I'll test that soon. Do you think it would matter where I require the step definition package? Perhaps in Cypress' `cypress/plugins/index.js` ?

**Comment by lgandecki** [comment]
I'd start with an attempt to require from an existing step definition

**Comment by paulgibbs** [comment]
To report back, I put https://github.com/paulgibbs/paulnodetest/blob/4683e8fb252d72210836dc783cce7024af9f8bd0/index.js in a separate package and `require`d it at the top of a step definition file, and Cypress/Cucumber was able to pick up the step definition and it worked!

I might end up including it via the common folder, I imagine it should work there just as well.

**Comment by alexkrolick** [comment]
Is there a way to make this work outside of a step definition file, in the common step definitions?

`import 'my-pachage/cucumber/common` in `index.js` in the common folder does not seem to do it.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
