### ISSUE TITLE
Coffeescript Language Support For Steps

### ISSUE THREAD

**Issue by James-Whyte** [badeball/cypress-cucumber-preprocessor#270]
First off, thank you kindly for this preprocessor; it's streamlining a whole lot of our acceptance testing and seems simple enough to get across the board. There is a feature I would like to request, however; the ability to write steps in the Coffeescript language.

Let's take an example scenerio:
```
Scenario: Test
    Given I log in
```

With a step in Coffeescript:
```
Given "I log in", ->
    cy.url
        .should 'not.be', 'Failed'
        .and 'be', 'Success'
```

Currently, it _finds_ the step but then once we attempt to run it in the Test Runner, the test fails as it cannot find the step.

Granted, my Coffee is a little shonky. But the idea of minimizing the amount of code and keeping it so simple a designer could implement it would be absolutely delightful.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
