### ISSUE TITLE
Can't see failed test in report when using All.features file

### ISSUE THREAD

**Issue by nnaidenov** [badeball/cypress-cucumber-preprocessor#271]
When I run `cypress run --spec All.features` and some of my test failed I can't see it in `*.cucumber.json` file.

There are 2 situations:

1. When I have for example 4 Scenarios in one file and 1 Scenario failed:
In the report file FAILED Scenario is missing

2. When I have for example 4 Scenarios in one file and all 4 Scenarios failed:
In the reporting folder it was created file with name `empty.cucumber.json` and contains only `[]`

When I run absolutely the same test without using All.features everything is OK and I can see FAILED Scenarios in report folder.

I'm using:
"cypress-cucumber-preprocessor": "1.16.2"
"cypress": "3.6.0"

**Comment by crysislinux** [comment]
I got an even stranger problem.

![image](https://user-images.githubusercontent.com/5404597/69331510-ddd80580-0c8f-11ea-99b3-fd7dc1104363.png)

**Comment by lgandecki** [comment]
Any chance you guys could create small reproductions that show these problems?

**Comment by crysislinux** [comment]
@lgandecki it's very strange. I found the problem on an `ubuntu 18.04` machine but it was totally fine on my mac with the same package version. So I cannot actually give a reproduction.

**Comment by crysislinux** [comment]
@lgandecki 

 I tried again and have video-enabled this time

![image](https://user-images.githubusercontent.com/5404597/69352649-3d4a0b80-0cb8-11ea-9b6d-36b47631a61b.png)

video:
https://drive.google.com/file/d/14pzSjVOurdSoBb3V4geahB_fo5yQo7H-/view?usp=sharing

Maybe the video has some problems?

**Comment by ludorival** [comment]
Hi, I am getting the same issue as @nnaidenov  and I think it's due to a conflict with other reporter in cypress.json. For example, I am using "mochawesome". When I remove it, I do not have the issue. Could you look at in this way ?

**Comment by kishore-marramreddy** [comment]
> When I run `cypress run --spec All.features` and some of my test failed I can't see it in `*.cucumber.json` file.
> 
> There are 2 situations:
> 
> 1. When I have for example 4 Scenarios in one file and 1 Scenario failed:
>    In the report file FAILED Scenario is missing
> 2. When I have for example 4 Scenarios in one file and all 4 Scenarios failed:
>    In the reporting folder it was created file with name `empty.cucumber.json` and contains only `[]`
> 
> When I run absolutely the same test without using All.features everything is OK and I can see FAILED Scenarios in report folder.
> 
> I'm using:
> "cypress-cucumber-preprocessor": "1.16.2"
> "cypress": "3.6.0"

Me too facing the same issue. Does any one any any solution for this ?

**Comment by tlolkema** [comment]
I'm also facing this issue, would be great if someone can look into this.

I'm using newest versions of Cypress/Cucumber-preprocessor (but having same issue with earlier versions)

>   "dependencies": {
    "cypress": "4.4.1",
    "cypress-cucumber-preprocessor": "2.3.1"
  },

**Comment by vibhasomashekhara** [comment]
I have same issues with cypress 4.1.0. I am using multiple-cucumber-html-reporter. A lot of my tests are missing from report.

**Comment by snehalk20** [comment]
Hi, I am facing a similar issue.

I am using the below versions of cypress and cucumber html reporter
"cypress": "^7.7.0",
"cypress-cucumber-preprocessor": "^4.1.4",
"multiple-cucumber-html-reporter": "^1.18.0"
When the tests are failing any or all, there is no cucumber html report being generated.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
