### ISSUE TITLE
How to print steps names into the console?

### ISSUE THREAD

**Issue by Lukaszli** [badeball/cypress-cucumber-preprocessor#290]
Is there any way to print steps names into the console while executing tests?

Something like:
<img width="492" alt="68747470733a2f2f7261772e6769746875622e636f6d2f7a6565766c2f6d6f6368612d637563756d6265722f6d61737465722f6578616d706c652e706e67" src="https://user-images.githubusercontent.com/55093721/71181321-33de9f80-2274-11ea-9c5e-9510704ad202.png">
screen from https://www.npmjs.com/package/mocha-cucumber

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
