### ISSUE TITLE
unable to get cy.log() data on cucumber report

### ISSUE THREAD

**Issue by sandygit2201** [badeball/cypress-cucumber-preprocessor#296]
I am using cypress with cypress-cucumber-process. i am logging some data using cy.log() in side cucumber steps implementation but, on generating cucumber using cypress-multi-reporters module, i am unable to see the data on cucumber report. 
generated json files under **cucumber-json**  also doesn't contain the data logged using cy.log(). 

can anyone help me to fix this issue?

Thank you.

**Comment by pravynandas** [comment]
Try this. After implementing this I get my cy.log() to CI console LOGGER and to the terminal. I hope this will work for report generation too.

... In cypress/plugins/index.js

module.exports = (on, config) => {
// on is used to hook into various events Cypress emits
// required for .features files
  on('file:preprocessor', cucumber());

// To bypass cy.log events to LOGGER
  on('task', { 
    log (message) { 
      console.log(message); 
      return null; 
    } 
  });

// `config` is the resolved Cypress config
//  return cypressConfigResolver();

};


... And in cypress/support/commands.js

// -- Overwrite log command to use task instead
    Cypress.Commands.overwrite('log', (subject, message) => cy.task('log', message));

Courtesy: [Comment](https://github.com/cypress-io/cypress/issues/3199#issuecomment-529430701)

**Comment by Dileep17** [comment]
@pravynandas with above I couldn't get the log written to json output generated. Not sure if im missing something!

tried finding in documentation but couldn;t find the way to write custom log messages to [json output ](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#output)

**Comment by pravynandas** [comment]
Sorry @Dileep17 I tried the console method alone. Haven't tried the json.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
