### ISSUE TITLE
Running all tags when no matching scenario is found

### ISSUE THREAD

**Issue by amitguptagwl** [badeball/cypress-cucumber-preprocessor#297]
1. When I run tests using `npx cypress-tags run -e TAGS='@group1 and not @Ignore'` where a feature file tagged with both `@group1` and `@Ignore` tags then it runs tests from all feature files.
2. When I run tests using `npx cypress-tags run -e TAGS='@group1` where there is no feature file tagged with `@group1` then it runs tests from all feature files.

**Comment by weary-pilgrim** [comment]
I'm having similar problems. It appears that `cypress-tags` runs all scenarios in any `.feature` file where any tag mentioned in the tag expression is mentioned, regardless of whether the tag expression says `not` and regardless of the tags on the scenario.

**Comment by weary-pilgrim** [comment]
When I run `cypress run -e 'TAGS=<tag expression>'` it works correctly (but it takes longer)

**Comment by arichard-info** [comment]
Hello @weary-pilgrim, I opened the PR https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/293 to fix this behavior, and it has been merged. It's now available since the version 1.19.1 
You can re-try it with after upgrading the dependency. Don't forget to specify the GLOB param with a pattern if you want to user something else than `cypress/integration/**/*.feature`

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
