### ISSUE TITLE
Feature request: defineDataTableType

### ISSUE THREAD

**Issue by pravynandas** [badeball/cypress-cucumber-preprocessor#300]
As described in cucumber.io [documents ](https://cucumber.io/docs/cucumber/configuration/)and in this stackoverflow [comment](https://stackoverflow.com/a/50944804/1751166) is this a good idea to have custom datatabletype definitions be part of this plugin?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
