### ISSUE TITLE
Change Default DIrectory for stepDefinitions

### ISSUE THREAD

**Issue by weary-pilgrim** [badeball/cypress-cucumber-preprocessor#311]
I had a problem finding my steps when I first upgraded to v2.0.1 because my cypress config is as follows:

```json
{
  "fixturesFolder": "test/cypress/fixtures",
  "integrationFolder": "test/cypress/integration",
  "pluginsFile": "test/cypress/plugins/index.js",
  "screenshotsFolder": "test/cypress/screenshots",
  "supportFile": "test/cypress/support/index.js",
  "videosFolder": "test/cypress/videos"
}
```

I solved the problem adding this to my package.json:

```json
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "test/cypress/integration",
  }
```

I would love to see you change the default value for the step definition path to be the `integrationFolder` configured in cypress.json. I seems like you should be able to change [this line of code](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/0160151cd211aa72e8b726f77c8fd7e9928d1222/lib/stepDefinitionPath.js#L19) from this:

```javascript
const relativePath = confStepDefinitions || "cypress/integration";
```

to this:

```javascript
const relativePath = confStepDefinitions || Cypress.config('integrationFolder');
```

But when I try that locally, it tells me that `Cypress` is not defined in the context where this code is executed. Is that why you're not using it in the first place?

**Comment by therussiankid92** [comment]
I might be interested in this solution, as this would allow me to update the directory of the stepDefinitions in a programatic way, via the Cypress Module API.

**Comment by lgandecki** [comment]
We don't have access to Cypress object so this is not possible. We used to have the default from the cypress config but we don't want to rely on config files that we don't own. Especially since now you can have the cypress config set through the CLI, which causes all sorts of different problems.

StepDefinitions path is something that you set once and forget, and if you ever change it in cypress config while forgetting updating the cypress-cucumber config, you will see an error that tells you exactly what's wrong, so I believe this is as good as we can get.

**Comment by csirkeee** [comment]
Isn't the config you get as a function parameter in `cypress/plugins/index.js` the fully resolved cypress config information? Couldn't you just pass that into your preprocessor function and get the integration folder from that?

**Comment by lgandecki** [comment]
Hmm I guess you could, but that's a backward incompatible change. It might be worth introducing a major version  bump for this change if this helps a lot of people

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
