### ISSUE TITLE
Can't have tsconfig.json in Cypress-cucumber-typescript for React

### ISSUE THREAD

**Issue by weihsu767** [badeball/cypress-cucumber-preprocessor#313]
I have a project with React, [Cypress-cucumber-preprocessor][1], Typescript(output in es5).  
When I run the cypress with [official example][2] or [another example][3], it has those problems:

    TypeScript error: cypress/integration/Google/google.ts(5,3): Error TS2304: Cannot find name 'cy'.

    SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

If I delete ```tsconfig.json``` in React parent folder, it fixed the ```Syntax Error``` but it still has ```TypeScript error```.   
So it seems like ```tsconfig.json``` make this problem, but the project should not without ```tsconfig.json```.

  [1]: https://www.npmjs.com/package/cypress-cucumber-preprocessor
  [2]: https://github.com/TheBrainFamily/cypress-cucumber-typescript-example
  [3]: https://github.com/TheBrainFamily/cypress-cucumber-typescript-example/tree/master/cypress

**Comment by DanAtSpark** [comment]
Hello, @WeihsuPeach. Do you have some line like `"types": ["cypress"]` in your `tsconfig.json` file?

I think that this problem is related to the fact that `tsify` is using the project's root `tsconfig.json` to process your code. You can add types declaration to the root file.
On the other hand, you can pass another `tsconfig.json` file to the `tsify`. 
```
options.browserifyOptions.plugin.unshift(['tsify', { project: tsConfigPath }]);
```
I'm not sure whether this approach will work but it's worth trying.

**Comment by weihsu767** [comment]
Hi @DanAtSpark , 
I had `"types": ["cypress"]` in my `tsconfig.json` file,
And I tried another way you said, but it still has the same problem

**Comment by gabbloquet** [comment]
I advice to use JS, sadly :/
`const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}
`
in cypress/plugins.index.js

**Comment by CSchulz** [comment]
We ran into similar issues and fixed it by using a webpack configuration.

**Comment by ashishpCACTUS** [comment]
> We ran into similar issues and fixed it by using a webpack configuration.

CSchulz - Can you please explain what webpack configuration you used. I have same issue when using it with an Angular solution

**Comment by lgandecki** [comment]
Sorry to hear it gives you problems.
A few things..
Webpack is not necessary in most cases, with cypress 4.4.0 you can actually just use out of the bo typescript support. A few documented ways of using typescript are here:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#typescript-support

Also the official examples get executed before every release.. So they do work. That gets verified over and over and over and over.. It's not enough to say "when I run them they have a problem". :) Clearly you are doing something different than we in the example, if you are able to create a simple reproduction that demonstrates the error we will be able to help, otherwise it's basically a guessing game

**Comment by ashishpCACTUS** [comment]
lgandecki - Thanks for the prompt reply. I have actually tried out the steps mentioned under 'With out-of-the-box support' and 'Without Webpack' one and skipped the 'With Webpack' one I think. I will try it out and see if it solves my issue. 

Regarding my case - Yes I am trying to do something different, I feel it should be possible but couldn't find anything directly available so scampering and combining things but to my vain.  

Also just to mention before i start my requirement, the example here works perfectly well https://github.com/TheBrainFamily/cypress-cucumber-typescript-example 

My case: 

I am trying to use cypress-cucumber-preprocessor to integrate BDD into an angular solution which has E2E and Component testing of cypress configured with cypress-code coverage enabled. 

Steps followed: 
I created a Blank angular 11 project,  and used the steps mentioned here https://github.com/bahmutov/cypress-angular-unit-test  to get cypress E2E testing , component testing and code coverage enabled. 

The point where I am stuck now is to integrate cypress-cucumber-preprocessor to this solution. Firstly I am unsure if this is possible or not. If it is possible then if you redirect me to some solutions then it will be great help.

My final goal is to have E2E tests inside the cypress Integration folder in the form of Cucumber Gherkin .feature files and corresponding steps files, while the component tests reside inside the App folder  and both E2E and component test inside the Angular solution and if possible to use the cypress code coverage with both the E2E and component tests.  

I have attached the test app I am working here.

Note: Currently cypress is present at 2 places in the app. I wasn't sure if in the main  cypress folder which is next to the src folder both E2E feature file and E2E ts will be configured correctly so I created an additional E2E folder and configured cypress to run BDD from there but i ran into the tsConfig error and got stuck now. 


[NewApp3Copy.zip](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/files/6363550/NewApp3Copy.zip)

Again thanks so much for the quick reply and sorry if this is not the correct place to ask this question but as mentioned i am stuck at the last point and cant find any solution to keep everything inside the same Angular solution.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
