### ISSUE TITLE
Custom parameter type with typescript

### ISSUE THREAD

**Issue by slashersvk** [badeball/cypress-cucumber-preprocessor#323]
I noticed there is a possibility to use custom parameter types as shown here:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/customParameterTypes.js

But I am getting trouble running it with Typescript.

Interface in typscript is defined as `export function defineParameterType(): void;` 
so if I import module, I cannot write a propper definition.

But if I use javascript as shown in expamle, then I always get error `Uncaught Error: Undefined parameter type {boolean}`

My javascript code looks like this:
```
defineParameterType({
  name: "boolean",
  regexp: /true|false/,
  transformer(s) {
    return s === 'true';
  }
});
```

Is there a way to get it working using Typescript?

**Comment by lgandecki** [comment]
I think you need to send a PR to update the types here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/cypress-cucumber-preprocessor

**Comment by jp7677** [comment]
@lgandecki  I'm about to open a PR for the typings. Could you please take a look at https://github.com/jp7677/DefinitelyTyped/commit/f8aa1b8d388a2df5795b5dc6cb697515b84fdcf3 ?

I've more or less copied the `Transform` definition from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cucumber/index.d.ts but omitted the `World` field because afaik the World concept is not used here in cypress-cucumber-prepocessor. Am I correct?

**Comment by slashersvk** [comment]
It looks good to me. But It's not up to me to decide. Btw thanks for making that effort. I didnt have much time to take a look at it.

**Comment by lgandecki** [comment]
@jp7677  yeah that should be fine, thanks!

**Comment by jp7677** [comment]
Submitted, see the linked PR.

**Comment by jp7677** [comment]
This issue should be fixed now with @types/cypress-cucumber-preprocessor 1.14.1.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
