### ISSUE TITLE
Run with tags using before and beforeEach

### ISSUE THREAD

**Issue by dthisner** [badeball/cypress-cucumber-preprocessor#325]
I am trying to create a login script that saves the cookies and then re-uses them through the test. 

The problem I have is following, I can't use `before` and `beforeEach` with tags, I have tried:

```
beforeEach("@landlordLogin", () => {
beforeEach({ tags: "@landlordLogin" }, () => {
```

I have more then one users, thats why I would like to run them with tags.

**Comment by jcundill** [comment]
Hi 
See https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#before-and-after-hooks
Can you use the Cucumber Hooks rather than the mocha ones?
Would that work for you

**Comment by dthisner** [comment]
I need to run the login Before ALL the other tests and then one that is grabbing/restoring the cookies. 
So, I need more then just 'before' and need to be able to use tags.

**Comment by jcundill** [comment]
This is quite a common requirement I would think. The way we handle this in our acceptance tests is as follows

In a Cucumber Before block for the user type associated with a tag we'd do something like

`Given The landlord has logged in
`

or 

`Given The tenant has logged in
`


Which, for us, maps to a step definition like

```
Given(/^The (.+) has logged in$/, (user) => {
    cy.login(user);
});

```
We created a cypress command to look after, and abstract away, all of the login state gnarliness associated with our systems

It does a bunch of things including cy.getCookie and cy.setCookie calls and if tests to see if appropriate cookies already exist

Essentially
 - in your Cucumber Before always login. Use tags if appropriate to setup the type of user who is logging in for this set of features/scenarios if thats how you have structured things
 - write some JS in a helper or a command to make the login actually happen for your DUT and to store the token/key/whatever to a cookie or local storage from this code
 - surround that login logic with an if block that checks if the answer is already there and if it is don't do it all again

Would that sort of approach work for you?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
