### ISSUE TITLE
cypress/plugins/index.js

### ISSUE THREAD

**Issue by shijiu1919zyx** [badeball/cypress-cucumber-preprocessor#326]
如果我需要在此使用多个插件，例如 cypress/code-coverage/task 和 cypress-cucumber-preprocessor，我应该怎么进行配置呢

**Comment by lgandecki** [comment]
yes

**Comment by lgandecki** [comment]
感谢您使用我们的插件。 回答您的问题-它应该可以正常工作。 请尝试以下方法：

```javascript
module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
  on('task', require('@cypress/code-coverage/task'))
}
```

如果您有任何问题，请随时在此处回复。 英语会有所帮助，因为我的中文有点生疏。

**Comment by shijiu1919zyx** [comment]
`module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
  on('task', require('@cypress/code-coverage/task'));
  config.env.API_ENVENV = process.env.API_ENVENV;
  return config;
};`
sorry my English is not very good ! 
as shown in the above code，
“yarn cypress open” ，
the error is as follows .


`The function exported by the plugins file threw an error.

We invoked the function exported by C:\mycypress\cypress\plugins\index.js, but it threw an error.

C:\mycypress\console\node_modules\@cypress\code-coverage\node_modules\execa\index.js:18`

still working on how to show you the error screenshot。。。
I don't know if I made it clear ???


”cypress/support/index.js “ 进行了对config.env相关的配置，按照@cypress/code-coverage 的指导进行了安装和配置，但是启动时一直报错。不太清楚是哪方面的问题。

**Comment by shijiu1919zyx** [comment]
![3](https://user-images.githubusercontent.com/57492108/75243508-f6166e00-5804-11ea-818e-9c50c7bcad10.png)

**Comment by shijiu1919zyx** [comment]
> 感谢您使用我们的插件。回答您的问题-它应该可以正常工作。请尝试以下方法：
> 
> ```js
> 模块。出口 =（on，config）=> {
>    on（' file：preprocessor '，cumcum（））
>    on（' task '，require（' @ cypress / code-coverage / task '））
> }
> ```
> 
> 如果您有任何问题，请随时在这里回复。英语会有所帮助，因为我的中文有点生疏。

done , I wonder if it is execa ??

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
