### ISSUE TITLE
cypress integrationFolder option seems not to be taken into account

### ISSUE THREAD

**Issue by zadigus** [badeball/cypress-cucumber-preprocessor#349]
I have the following `cypress.json` file:
```json
{
  "env": {
    "TAGS": "not @wip"
  },
  "integrationFolder": "cypress/my-integration-folder",
  "fixturesFolder": "./shared/fixtures/graphql/responses",
  "ignoreTestFiles": [
    "*.js",
    "*.gif"
  ],
  "projectId": "g6v5sw",
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "cypress/test-reports/cypress-e2e-report.[hash].xml",
    "toConsole": true
  },
  "video": true,
  "videoUploadOnPasses": false,
  "viewportHeight": 900,
  "viewportWidth": 1440
}
```
When I run my e2e tests, I get the following error:
```bash
Error: We've tried to resolve your step definitions at cypress/integration, but that doesn't seem to exist. [...]
```
I am using cypress 4.2.0 and cypress-cucumber-preprocessor 2.0.1. What am I doing wrong? It's like the `cypress.json` is not taken into account or just the `integrationFolder` option.

**Comment by spikyjt** [comment]
It seems that this library is so opinionated that it ignores the options in cypress. Whilst I agree that a logical pattern is useful, customisation is also important, especially if the parent library has an associated option.

Presumably it shouldn't be too difficult to respect the value of cypress's `integrationFolder` instead of hardcoding `cypress/integration`?

**Comment by lgandecki** [comment]
Sorry for the problem folks. It's not really about being opinionated but about the fact that we no longer read cypress configuration as we don't own it and it was problematic since cypress allowed that configuration to be put in different places and passed differently. 

You can set the where you put the path to stepDefinitions with our own configuration:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration-option

**Comment by badeball** [comment]
Unless Cypress introduce a programmatic way to resolve & retrieve its configuration, any attempt at mimicking it would likely come with its own set of problems.

**Comment by spikyjt** [comment]
@lgandecki thanks for the clarification, I appreciate it is actually cypress not being very helpful with its config. Also, by opinionated, I didn't mean that was necessarily a bad thing, it can be very useful, but it's usually best to allow customisation where possible.

Regarding the options to set, can you give an example of how this would work?

If I set `integrationFolder` in `cypress.json` and `nonGlobalStepBaseDir` and `stepDefinitions` in `cypress-cucumber-preprocessor` section in `package.json` (with`nonGlobalStepDefinitions` set `true`, as recommended) then a custom directory works fine, however the actual values of the `cypress-cucumber-preprocessor` seem to be ignored, as I still have to follow the pattern of having step definitions next to gherkin files.

What I want to achieve is having feature (gherkin) files in a separate directory, so that it can be a submodule, editable by non-tech team, and step definitions separately (happy to mirror the well thought out structure of step definitions preferred in this project).

**Comment by spikyjt** [comment]
I have figured it out. If I set `nonGlobalStepDefinitions` to `false`, then `stepDefinitions` is honoured and it works the way I like.

Ideally I would like to enforce the preferred pattern with `nonGlobalStepDefinitions` set `true`, but still have the step definitions in a separate location to the features. For now, I can follow that as best practice.

**Comment by goesbysteve** [comment]
@lgandecki couldn't the cypressIntegration value be set in the cypress-cucumber-preprocessor config in package.json as well? I realise that Cypress config isn't fixed to just from cypress.json but this would be better than nothing.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
