### ISSUE TITLE
How to configure multiple directories for step definitions

### ISSUE THREAD

**Issue by averri** [badeball/cypress-cucumber-preprocessor#353]
I want to configure multiple directories for storing step definitions.

We have packaged common test steps into a npm library, and each application can have its own step definitions in addition to the common step definitions. I haven't found any documentation showing how to do that.

This is the actual fragment of `package.json`, it contains only the step definitions of the application. How to add the common step definitions contained in the folder `node_modules/@netan/common-step-definitions` ?

```json
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "test/javascript/features/step_definitions"
  }
```

**Comment by courtney-regis** [comment]
@averri 
We faced a similar issue and solved it by writing a postinstall step which copies the steps into common using cosmiconfig but quickly found out this approach falls apart since consumers were happy at first, but as tests became more complex, the step text became less coherent so people started rewriting the steps we took so much time to package. 

So rather than packaging the steps, our NPM modules now package cypress commands and package our recommended step text as well. 
This has been very well received since a consumer can get the steps and assertions regardless of if they use cucumber sytnax and if they do use cucumber, they can compose a step using our text and our custom command.

**Comment by andsamp** [comment]
@averri - I'm sure you've figured this out by now, but I was able to `import` our shared step-definitions in one of the common step-definition files and that worked for us. Not as nice as having `step_definitions` take an array that includes the project's step-definition location as well as the dependency's, but it works...

See https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/269

**Comment by hdidier** [comment]
@andsamp  @courtney-regis Is there any documentation on how you did the export/import of the step definitions? Thanks in advance!

**Comment by andsamp** [comment]
> @andsamp @courtney-regis Is there any documentation on how you did the export/import of the step definitions? Thanks in advance!

It is fairly straight forward, we created a `@team/cypress` artifact that install as a dev dep. the import goes in a `shared.js` file where we have our project-specific step-definitions (${[integrationFolder](https://docs.cypress.io/guides/references/configuration#Folders-Files)}/step-definitions).

`import '@team/cypress/step-definitions';`

Within the `@team/cypress` project we have a `src/step-definitions` directory with the step-definitions broken out as we see fit and then we have an an `index.js` in that directory where we `import` all of the other files.

**Comment by hdidier** [comment]
Thank you very much for the reply, however, it still isn't working for me.  We have an internal npm package where I have a TS file and several common/shared steps listed.  Do they need to somehow be exported? 

For the import, did you have to modify any config files in the project repo?  I've tried importing to the npm package index file, but also in the project repo's default.ts file which contains the base steps.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
