### ISSUE TITLE
Cucumber background hook does not match the behaviour of Cypress before hook

### ISSUE THREAD

**Issue by BirgitPohl** [badeball/cypress-cucumber-preprocessor#359]
I've noticed that the Cypress Cucumber Preprocessor Background is behaving like just another step definition in Cypress and not as it intents to be: A before hook.

Here is an example:
Assuming, that chromeWebSecurity is false and [extra info:] [Cypress wants to allow different visiting different domains with cy.visit() as well.](https://docs.cypress.io/guides/guides/web-security.html#Set-chromeWebSecurity-to-false)

Currently Cypress allows to visit a domain in the before hook and another domain inside a step definition.
Here is an example for that: cypress-io/cypress#944  -> To the [comment](https://github.com/cypress-io/cypress/issues/944#issuecomment-609801121).

The Cucumber Background acts as a before hook and it is executed before each scenario. In this example Google shall be visited before going to another page.

```gherkin
Feature: Visiting websites

  Background: Visiting Google
    When I visit google

    Scenario: Visiting Facebook
      When I visit Facebook

    Scenario: Visiting Amazon
      When I visit Amazon
```
Each scenario will error, because the test already has visited a super domain.

## My use case:
I have implemented a SaaS inside a big portal. The portal is production and has a cool super domain. My SaaS is in staging mode and comes from a different domain. Now I want to visit a page inside my SaaS coming from the portal, which will error in a Cypress Web Security error.
![visitt](https://user-images.githubusercontent.com/4340405/78755594-b56c5180-7979-11ea-8548-5c5894b8105f.png)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
