### ISSUE TITLE
Integration with vue/cli 4

### ISSUE THREAD

**Issue by raghuvarbisht** [badeball/cypress-cucumber-preprocessor#366]
Can you please let me know how we can use the cypress-cucumber-preprocessor with the project of vue/cli framework?
Any working repo link is much appreciated.

**Comment by raghuvarbisht** [comment]
Hi , 
I am able to resolve the issue with latest project.@vue/cli latest code with step deployed at below location. You can share below repo link of with people in case they will face same issue with 

https://github.com/raghuvarbisht/vue-cypress-cucumber

Thanks,
Raghuvar

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
