### ISSUE TITLE
Smart auto-generation of step definition .js files/stubs

### ISSUE THREAD

**Issue by chachra** [badeball/cypress-cucumber-preprocessor#370]
Hi,

Is there a way to auto-generate the step definitions based on the feature files?

**Comment by jprealini** [comment]
If you are working from VSCode (not sure if this exists for other IDE's) there is an extension called Cuke Step Definition Generator. I use it and it works great.

**Comment by benjaminknauer** [comment]
https://github.com/agoldis/sorry-cypress

This works quite good.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
