### ISSUE TITLE
No commands were issued in this test.

### ISSUE THREAD

**Issue by LeonidYarosh** [badeball/cypress-cucumber-preprocessor#372]
Hello! I acted according to the [instructions ](https://www.npmjs.com/package/cypress-cucumber-preprocessor#installation)and connected cypress-cucumber-preprocessor to the project. Launched on command "cypress open". Maybe I missed something?

I ran on a webStorm 2019.2 and win10

My test
Feature:Google
  Scenario: Opening a Google network page
    Given I open Google page
    Then I see "Google" in the title

![1111](https://user-images.githubusercontent.com/31515107/80316889-2e3c2c00-8809-11ea-8711-00b267aa4ebd.PNG)

**Comment by gkruiger** [comment]
Happens to me also. When shut down Cypress and restart (npx cypress open) and run the test again without doing/changing anything else, it's fine again.

**Comment by lgandecki** [comment]
@gkruiger did it happen once or does it happen from time to time?

**Comment by gkruiger** [comment]
It does happend from time to time. Haven't figured out what triggers it though. I'll keep an eye on it in the coming days.

**Comment by LeonidYarosh** [comment]
Works on these versions: (they were in the example)
 "cypress": "3.4.1",
    "cypress-cucumber-preprocessor": "1.16.2"

I use these versions:
  "cypress": "4.4.0",
    "cypress-cucumber-preprocessor": "2.3.1",

**Comment by psech** [comment]
Same here after upgrading Cypress to 6.1.0

The plain project, no cucumber
macOS Big Sur 11.0.1

package.json script
`"cy:open:production": "CYPRESS_ENVIRONMENT=production cypress open --project tests/cypress --config baseUrl=https://dataroom.ansarada.com/"`

**Comment by nawlbergs** [comment]
So oddly...
I had this issue with one of my test files... in it... I had my `it` function flagged as async:
```js
   it('Should do whatever... ', async () => {
```
I was not doing any `await` and was not returning a promise...  The test would run fine when it was flagged with `.only`:
```js
describe.only('...', () => {
   it('Should do whatever... ', async () => {  // worked
}
```

When I removed the `.only` flag so i could run all my tests.. the tests were essentially skipped over and id get `No commands were issued`... tho they essentially didnt run.. `they were green and considered passed`.
```js
describe('...', () => {
   it('Should do whatever... ', async () => {  // No commands were issued (tho the test passed)
}
```


Removing the async from the function resolved the issue... at least for me.
```js
describe('...', () => {
   it('Should do whatever... ', () => {  // works as expected
}
```

**Comment by leilafi** [comment]
Happens to me as well. Using version 9.0 and "cypress-cucumber-preprocessor": "^4.2.0". It's intermittent and usually goes away if I close cypress IDE and reopen it.

**Comment by kovacsdongo** [comment]
hello
async solved a part of my problem, but there is one more:
here is my code
`it('My FirstTest case', async () => {

        cy.visit("...");

        cy.intercept({
            
        },`
I get TypeError: cy.intercept is not a function, I do not know why. Anybody met a similar problem?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
