### ISSUE TITLE
Feature Flagging

### ISSUE THREAD

**Issue by KevinT** [badeball/cypress-cucumber-preprocessor#375]
Is there a standard way of handling feature flags? Certain features/scenarios may only work with certain feature flags switched on, so we'd like to somehow make our specifications "feature flag aware".

Apologies if this is a solved problem/documented elsewhere, I did a search but turned up empty. 

Is there a nice clean way to do this?

**Comment by jprealini** [comment]
I just got in here to ask if there is a way to tag (or flag) a feature in order to run a before hook once before that feature starts executing... is that what you are requesting? (Just to not duplicate the question/request)

**Comment by badeball** [comment]
You can tag tests and chose to not run said tests as you desire.

```cucumber
Feature: frontpage
  @foobar-disabled
  Scenario:
    Given I'm on the frontpage
    Then I should not see traces of foobar

  @foobar-enabled
  Scenario:
    Given I'm on the frontpage
    Then I should see traces of foobar

```

So, when running with said feature flag:

```
$ my-application --enable-foobar
...
$ cypress run -e TAGS='not @foobar-disabled'
```

And when running without it:

```
$ my-application --disable-foobar
...
$ cypress run -e TAGS='not @foobar-enabled'
```

**Comment by badeball** [comment]
@jprealini, you can tag `Before` and `After` hooks, as per [docs](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#before-and-after-hooks).

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
