### ISSUE TITLE
Is not possible to get scenario status on After

### ISSUE THREAD

**Issue by AnaPena** [badeball/cypress-cucumber-preprocessor#377]
I would like to access to scenario status in order to attach screeshots on failure to my reports. Something like:

After(async function(scenario) {
    if (scenario.result.status === 'failed') {
            // actions on failure
    }
});

Is there a way to access to scenario status?

**Comment by Michenux** [comment]
I would like to have this feature too.

**Comment by felipealvarado** [comment]
Hi @AnaPena check if this documentation will help you https://docs.cypress.io/api/events/catalog-of-events.html#Catching-Test-Failures

**Comment by praveen1000** [comment]
I also would like to have this feature. Like in other tools scenario.isFailed() works or scenario.attach()

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
