### ISSUE TITLE
Error: Step implementation missing for: I am on the landing page and I do not have a hurricane account     at Context.resolveAndRunStepDefinition (http://localhost:8080/__cypress/tests?p=cypress\integration\my.hrrcn-user-stories-signup\my.hrrcn-signup-form.feature-216:7321:11)

### ISSUE THREAD

**Issue by davidh465** [badeball/cypress-cucumber-preprocessor#378]
When I start cypress for the first time and try to run the feature files I get the following error, but when I refresh it work perfectly.

"Error: Step implementation missing for: I am on the landing page and I do not have a hurricane account
    at Context.resolveAndRunStepDefinition (http://localhost:8080/__cypress/tests?p=cypress\integration\my.hrrcn-user-stories-signup\my.hrrcn-signup-form.feature-216:7321:11)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
