### ISSUE TITLE
Video recording not working

### ISSUE THREAD

**Issue by joaotnlima** [badeball/cypress-cucumber-preprocessor#387]
Hi there,

My tests are all working very nice when i run cypress with cypress:open.
My problem is when i try to run the same tests with cypress:run video recording is not working even though i explicitly add --record command.

It saves the videos with few seconds of recording ending with this error:
![image](https://user-images.githubusercontent.com/1760345/84206970-30500680-aaa8-11ea-9563-e9430579ed72.png)

**Comment by lgandecki** [comment]
@joaotnlima sorry for the troubles. Can you check 2.3.1?

**Comment by joaotnlima** [comment]
![image](https://user-images.githubusercontent.com/1760345/84637362-829c8780-aeed-11ea-92f2-c70495792215.png)
Hello @lgandecki, after upgrading i get this error. I have a common-steps file with most of the steps as i click i navigate etc... and for a very simple order workflow, the file *.feature is empty but requiring the common-steps file...

What am i doing wrong?

**Comment by joaotnlima** [comment]
Any updates here @lgandecki ?

**Comment by joaotnlima** [comment]
As I still can reproduce this issue, just commenting for it to remain active.

**Comment by lgandecki** [comment]
Hello @joaotnlima , any chance for a reproduction we could check out from github?

**Comment by joaotnlima** [comment]
/config
    staging.json
```
{
  "product-page": "baseurl/products/headphones-baseus-encok-wireless-d02-preto-01cc6a95-9e2b-4e7b-9300-27e3a5d8bc9a",
  "product-integrator-page": "baseurl/store/seller-brasinhas/products/headphones-baseus-encok-wireless-d02-preto-01cc6a95-9e2b-4e7b-9300-27e3a5d8bc9a",
  "cart-page": "/cart",
  "identity-page": "/checkout/identity/user",
}
```

/integration
  /config
     common-steps.js

import { Given, Then, When } from 'cypress-cucumber-preprocessor/steps';

Given("I visit {string}", (page) => {
  cy.visit(Cypress.config(page), {
    auth: {
      username: Cypress.config('authUser'),
      password: Cypress.config('authPwd'),
    },  
  });
});

When("I Press button with text {string}", (text) => {
  cy.get('button').contains(text).click();
});


Then("I Press div with text {string}", (text) => {
  cy.get('div').contains(text).click();
});


Then I have folders like

  /integration
    /orders
      order.feature


Feature: I purchase a product
  @e2e-test
  Scenario: Purchase product using CC
    Given I visit 'product-page'
    And I Press div with text "Adicionar ao cesto"
    When I Press button id 'header-cart'
    Then I am redirected to "cart-page"
    When I Press button id "confirm-checkout-button"
    ....

  /integration
    /orders
      /order
         order.js

import commonSteps from '../../common/common-steps';

 /integration
    /orders
      /order
         hook.js

import { Before } from 'cypress-cucumber-preprocessor/steps';

Before(() => {
  if (Cypress.env("DEVICE") !== "") {
    cy.viewport(Cypress.env("DEVICE"), Cypress.env('ORIENTATION'));
  }
});


As said it all works well when opening cypress, but when running it does not record neither runs the tests. Hope this can clarify. Please get in touch if you need more info.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
