### ISSUE TITLE
cucumberJson output does not respect folders

### ISSUE THREAD

**Issue by bukharov** [badeball/cypress-cucumber-preprocessor#393]
### Current behavior

I have some feature files that have the same name but in different folders, for instance:
```
OMA/Enrolment.feature
GLI/Enrolment.feature
```

Also I have the following configuration in my `package.json`:
```
  "cypress-cucumber-preprocessor": {
    "step_definitions": "cypress/support/steps/",
    "nonGlobalStepDefinitions": false,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "reports/cypress"
    }
  },
```

After the test run there is only one `Enrolment.cucumber.json` in the `reports/cypress` folder.

### Desired behavior

I'd like `reports/cypress` to look like this:
```
OMA/Enrolment.cucumber.json
GLI/Enrolment.cucumber.json
```

### Versions

* **Cypress version**: 4.7.0
* **Preprocessor version**: 2.4.0
* **Node version**:  12.8.0

**Comment by chihsam** [comment]
Will this ever be merged into master?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
