### ISSUE TITLE
Hooks Are Not Run if Defined in Cypress/support/

### ISSUE THREAD

**Issue by AlexK777** [badeball/cypress-cucumber-preprocessor#396]
### Current behavior

It's mentioned [here](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Support-file) that `Cypress/support/index.js` is a good place to set reusable hooks, but if I define a Cucumber hook in this file they are never run. Mocha hooks DO run, but I need to use tags so I want to use the Cucumber hooks if possible. Is there a specific reason the Cucumber hooks aren't being run when placed in the support directory but mocha hooks are? 

### Desired behavior

Cucumber hooks run when placed/imported into the `Cypress/support/index.js` file. 

### Test code to reproduce

Just use the Cypress example repo and place a Cucumber hook in `Cypress/support/index.js` such as 
```
Before(() => {
cy.log('Anything?');
});
```

And you can see this hook is not run and nothing is logged. If you change it to the mocha hook
```
before(() => {
cy.log('Anything?');
});
```
You will see this run and log `Anything?`.

### Versions

* **Cypress version**: 4.4.1
* **Preprocessor version**: 2.3.1
* **Node version**: 12.2.0

**Comment by praveen1000** [comment]
Add  below statement in the index.js file.
```
const {
  Before,
  After
} = require("cypress-cucumber-preprocessor/steps");
```

Reason: The cypress-cucumber-preprocessor supports both Mocha's before/beforeEach/after/afterEach hooks and Cucumber's Before and After hooks.

The Cucumber hooks implementation fully supports tagging as described in the cucumber js documentation. So they can be conditionally selected based on the tags applied to the Scenario. This is not possible with Mocha hooks.

Cucumber Before hooks run after all Mocha before and beforeEach hooks have completed and the Cucumber After hooks run before all the Mocha afterEach and after hooks.

Source: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor

**Comment by AlexK777** [comment]
This has no affect. Mocha hooks still run and Cucumber hooks still do not.

**Comment by lgandecki** [comment]
Could we get a repo with reproduction? That feature should work, we have it covered with tests

**Comment by AlexK777** [comment]
Here is a repo you can use for reproduction. In `support/index.js` there is a Cucumber Before hook and a Mocha before hook. When you run the feature you can see that only the Mocha hook is being executed. I also tried removing the Mocha hook completely so only the Cucumber hook existed, but then no hooks were run. 

<img width="561" alt="Screen Shot 2020-09-15 at 2 54 33 PM" src="https://user-images.githubusercontent.com/7462060/93258415-df654380-f763-11ea-8ab5-2b86f3f96a00.png">

https://github.com/AlexK777/cypress-example-kitchensink

1) Run `nvm use` then `yarn`.
2) Run `yarn cy:open`.
3) Run the only feature from the UI and view the output in the UI.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
