### ISSUE TITLE
Need more clarity in reference to #155 for taking screenshot on Pass steps

### ISSUE THREAD

**Issue by jaydeepbasu** [badeball/cypress-cucumber-preprocessor#399]
This is with reference to  : 
_Originally posted by @jcundill in https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/155#issuecomment-508904086_
Screenshots can be generated a couple of ways
 1) using cy.screenshot - I haven't added support for this to my fork, should be doable fairly easily by getting the onAfterScreenshot to feed the image data to the cucumber JSON data collector object.

Can you please provide a code sample to put little bit more clarity how this can be achieved.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
