### ISSUE TITLE
Default commonPath error

### ISSUE THREAD

**Issue by Song-Nan17** [badeball/cypress-cucumber-preprocessor#403]
When `nonGlobalStepDefinitions` is true and `nonGlobalStepBaseDir` is defined, but `commonPath` is not defined, then 
default `commonPath` is not correct.

it is because that `nonGlobalPath` & `stepBase` both have `appRoot` ...
![image](https://user-images.githubusercontent.com/43493277/86327848-7b5bd480-bc76-11ea-9c22-0aaacd536221.png)

**Comment by lgandecki** [comment]
Hello @Song-Nan17 . Thanks for the info and sorry for the trouble.

Any chance you could express this in a failing unit test here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/getStepDefinitionsPaths.test.js ? Better yet, a unit test and a fix to the code? ;) We love having more contributors to the project, and since you've already pinpointed the error..

**Comment by Song-Nan17** [comment]
Hi @lgandecki , I've create a pr: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/405 to resolve this issue. Hope it helps. And thx for your work.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
