### ISSUE TITLE
Tags are not inherited

### ISSUE THREAD

**Issue by olabalboa** [badeball/cypress-cucumber-preprocessor#406]
### Current behavior
Tags added above a feature are not inherited by the scenarios according to the spec https://cucumber.io/docs/cucumber/api/#tags

I have the following before step
`
Before({ tags: '@basic' }, () => {
  console.info('Before basic');
});`

When I put the `@basic` tag above the `Feature` in the feature file the Before-step is not executed. If I put the `@basic` tag above the `Scenario` in the feature file it is executed.

### Desired behavior
Tags should be inherited by the child elements

### Versions

* **Cypress version**: 4.9.0
* **Preprocessor version**: 2.5.2
* **Node version**: 13.11.0

**Comment by mpsijm** [comment]
This appears to be fixed in #557, which is released with version 4.2.0. Specifically, [these lines](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/557/files#diff-cc7c0a1c756a60d4c3c2429ccdd6d6fc7a6f740575ed28a53a204f73930fcb0fR20-R24) seem to do the trick :smile:

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
