### ISSUE TITLE
Cypress aliases are not available in the After hook

### ISSUE THREAD

**Issue by zadigus** [badeball/cypress-cucumber-preprocessor#413]
### Current behavior

Here's my spec file:
```js
import { After, Before, Given, When, Then } from 'cypress-cucumber-preprocessor/steps'

let userId

Before(() => {
  cy.registerNewUser().as('credentials')
    .then(creds => {
      userId = creds.userId
    })
})

After(() => {
  cy.deleteNewUser(userId)
})

Given('un Rex identifié', function () {
  cy.visit('/')
  cy.loginAsNewRex(this.credentials.username, this.credentials.password)
  cy.assertUserIsIdentified()
})

[...]
```

While the `this.credentials` is available in all my steps (here I only show the `Given` step), it is not available in the `After` hook, which is the reason why I am doing this hack with the `userId` variable. 

### Desired behavior

I do not understand why I can't simply do this:
```js
import { After, Before, Given, When, Then } from 'cypress-cucumber-preprocessor/steps'

Before(() => {
  cy.registerNewUser().as('credentials')
})

After(() => {
  cy.deleteNewUser(this.credentials.userId)
})

Given('un Rex identifié', function () {
  cy.visit('/')
  cy.loginAsNewRex(this.credentials.username, this.credentials.password)
  cy.assertUserIsIdentified()
})

[...]
```

To add some more context to that use case, the call to `registerNewUser` generates the new user's id, which is the only necessary information to delete that user after the test.

### Versions

* **Cypress version**: 4.4.1
* **Preprocessor version**: 2.3.1
* **Node version**: 13.8

**Comment by safatoujani** [comment]
I have the same problem too

**Comment by justjoeactually** [comment]
This workaround works fine for me:

```javascript
After(() => {
  cy.get('credentials').then(credentials => cy.log(credentials));
}
```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
