### ISSUE TITLE
Skipped test reporting breaks Jira TM4J automation

### ISSUE THREAD

**Issue by rcaunt** [badeball/cypress-cucumber-preprocessor#419]
### Background:

Release 2.4.0 addressed the issue raised by #288 and caused additional information to be reported into the JSON output that was previously missing, e.g. tests that were pending or skipped were not output into the JSON file.

The following is now output for a step which was ignored/skipped:

```
{
  "arguments": [],
  "keyword": "Given ",
  "line": 33,
  "name": "ABC",
  "result": {
    "status": "skipped",
    "duration": 1186000000
  }
}
```

### Issue:

We are utilising the cucumber automation endpoint provided by Jira's TM4J plugin.  This allows us to pass the output file directly to TM4J and have it populate information based on the cucumber output.

Since upgrading to 2.4.0 or higher, this integration fails with the following error:

```
"errorMessages":["Test Result Status with name skipped not found."]}
```

We have looked at configuration options in TM4J to see if a status can be added to allow it to function (also have a support ticket with TM4J support, awaiting reply).  However, we suspect that their API wont support these "skipped" steps.

### Question:

Is there a way that we can prevent this output behaviour (effectively reverting to previous)?

### Versions

* **Cypress version**: 4.11.0
* **Preprocessor version**: 2.4.0 onwards
* **Node version**: 12

**Comment by rcaunt** [comment]
SmartBear support have got back to me today stating that a step status of `skipped` is not supported but may be implemented in future versions :/

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
