### ISSUE TITLE
How to get a single cucumber.json file aggregate all features

### ISSUE THREAD

**Issue by hiaux0** [badeball/cypress-cucumber-preprocessor#423]
### Documentation

In [this section from the Readme](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#output) 

> The cypress-cucumber-preprocessor can generate a cucumber.json file output [...]

but 

> Output, by default, is written to the folder cypress/cucumber-json, and one file is generated per feature.

### Issue

I wasn't able to figure out how I could get a single file with all features included.
I even digged a bit in the source code, which led me to `writeCucumberJsonFile`, where the json files are generated.
For example in pure `cucumber-js`, I could get single json file 
https://github.com/hiptest/hps-cucumber-javascript#run-tests

### Exampe repo used
https://github.com/TheBrainFamily/cypress-cucumber-example

Any help is greatly appreciated

Thanks,
Hiau

**Comment by malt-man** [comment]
👍 This would be really useful - I'm facing the same issue.

**Comment by AlexMurphy** [comment]
I've spent a while trying to do just this but for now I'm using a hook that clears the folder before the test runs and a hook that runs after the test that grabs the last json file in the folder (just to make sure its the right one) and does the necessaries. 
Hope this helps.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
