### ISSUE TITLE
Common steps are not discovered

### ISSUE THREAD

**Issue by godrose** [badeball/cypress-cucumber-preprocessor#425]
### Current behavior

`Common` folder is not recognized by the framework

### Desired behavior

`Common` folder is recognized by the framework

### Test code to reproduce

Setup files:

`package.json`

```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
```

`cypress.json`

```
{
  "testFiles": "**/*.feature"
}
```

`plugins.js`

```
process.env["NODE_CONFIG_DIR"] = __dirname + "/../../config";
const config = require("config");
const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, cyConfig) => {
  cyConfig.baseUrl = config.get('baseUrl');
  cyConfig.integrationFolder = 'cypress/specs';
  cyConfig.commonPath = 'cypress/specs/common';
  on('file:preprocessor', cucumber());
  return cyConfig;
};
```

`Cypress` internal structure
- specs
  - common
    - steps.js
  - Login
    - steps.js
  - Sdk
    - steps.js
  - Login.feature
  - Sdk.feature

### Versions

`Cypress@latest`
`preprocessor@latest`
`Node 12`

**Comment by godrose** [comment]
In my opinion it's about having custom `integration` folder name

**Comment by godrose** [comment]
Any update on this @lgandecki ?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
