### ISSUE TITLE
Feature request - use scenario tags in hooks

### ISSUE THREAD

**Issue by jprealini** [badeball/cypress-cucumber-preprocessor#428]
### Current behavior

Inside before() hooks in support/index.js or globalBefore.js there is no way to get the current scenario tags in order to be able to run hooks specific to a scenario. If I use
```
Before({ tags: "@123" }, () => {
```
The hook will run for all scenarios

### Desired behavior

In old frameworks I used to build with Protractor + Cucumber I would create before and after hooks for specific tags, like
```
Before({ tags: "@123" }, () => {
    const spec = Cypress.mocha.getRunner().test;
    console.log(spec)
})
```
I haven't been able to find a way to create this "selective" hooks with Cypress and Cypress-Cucumber-Preprocessor in order to execute some specific hook for a given scenario

### Versions

* **Cypress version**: 4.12.1
* **Preprocessor versin**: 2.5.0
* **Node version**: 12.16.3

**Comment by RobertoPegoraro** [comment]
I have the same need

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
