### ISSUE TITLE
cypress throwing step implementation missing error, if we pass JSON from scenario outline

### ISSUE THREAD

**Issue by Hemalatha-JS** [badeball/cypress-cucumber-preprocessor#431]
My requirement is to pass JSON values from the scenario outline for validation purpose and Cypress is throwing step implementation missing error when we are passing the JSON from the Scenario Outline below is the scenario outline

    Scenario Outline:Validate the Task Actions list for Questionnaire
       Given user adds the "<TaskAction>"
        When "Done" is clicked
        Then record "<TaskActionSummary>" will be displayed under "Task Actions" listview
        Examples:
            | TaskAction                                                          | TaskActionSummary                                                     |  
            | [{"Condition":"Then","Task Type":"Questionnaire","Status":"Enabled"}]|[{"Condition":"Then","IconDisplayed":"yes","Performer":"Professional"}] |
and below is the step definitions available

('Given user adds the {string}',(taskAction)=>{
console.log(taskAction)
})
('Then record {string} will be displayed under {string} listview',(taskactionsummary,taskaction)=>{
  console.log(taskactionsummary)
})

does cypress doesn't support passing string in JSON format ?

**Comment by amitguptagwl** [comment]
I believe it should be defined as `('Given user adds the "{string}"',(taskAction)=>{})`.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
