### ISSUE TITLE
While running scenario with specific tag others are marked as pending in results

### ISSUE THREAD

**Issue by praveen1000** [badeball/cypress-cucumber-preprocessor#436]
### Current behavior
This feature file has two tests marked with tags @smoke and @Regression. I'm running command npx cypress-tags run -e TAGS='@smoke' to run only scenario marked with tag @smoke. This command runs the desired scenario but marks others as pending. Example of the result shown in the below image
[https://ibb.co/CPfqzLv](https://ibb.co/CPfqzLv)

### Desired behavior

Scenarios that are not executed should not show in the results.

### Test code to reproduce
Google.feature

```
Feature:  The Facebook

  I want to open a social network page
  
  @smoke
  Scenario: fhgfh a social network page
    Given I open Google page

  @regression
  Scenario: sd a social network page
    Given I open Google page
```
 
Step definition:
Givens.js
```
const url = 'https://google.com'
Given('I open Google page', () => {
  cy.visit(url)
})
```

### Versions

* **Cypress version**:5.0.0
* **Preprocessor version**: ^2.5.5
* **Node version**: v12.16.3

**Comment by alexkrolick** [comment]
I think they should be marked as "Skipped" instead of "Pending". Otherwise the Cypress test output looks incorrect (as if tests are hanging instead of not running).

**Comment by badeball** [comment]
> I think they should be marked as "Skipped" instead of "Pending". Otherwise the Cypress test output looks incorrect (as if tests are hanging instead of not running).

This isn't something we chose. See eg. https://github.com/cypress-io/cypress/issues/3092 and https://github.com/cypress-io/cypress-documentation/issues/593.

**Comment by badeball** [comment]
It seems like you have multiple test suites that you commonly run separate from each other, making the "pending output" seem like a polution. I get that, but why do you have separate types of tests gathered in a single test suite? Split them up and use eg. an environment variable to specify `testFiles` matching only the desired tests.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
