### ISSUE TITLE
Using @focus tag makes all tests without the tag fail in cypress with 'This.skip is not a function'

### ISSUE THREAD

**Issue by symon-skelly** [badeball/cypress-cucumber-preprocessor#440]
### Current behavior

When using any version of the preprocessor above 2.3.1 and using the @focus tag, any test without the tag will:

1. Run any code within beforeEach(), essentially starting the test.
2. Fail once it starts the first scenario step with the following error:

![image](https://user-images.githubusercontent.com/60613068/92460217-fe922d00-f1c7-11ea-9aab-ee596f9060fe.png)

### Desired behavior

When running tests with the @focus tag, skip the entire scenario, do not run any code for that scenario. do not throw the error.

### Versions

* **Cypress version**:
* **Preprocessor version**: 2.4 and above
* **Node version**:12.14.1

**Comment by CedricMalfreytBL** [comment]
Quite same here.

Using TypeScript 4.0.2, cypress 5.2.0, cypress-cucumber-preprocessor 2.5.5.

![image](https://user-images.githubusercontent.com/8135706/93625557-73444300-f9e2-11ea-914e-7f28596b2bcb.png)

**Comment by rudyaditya** [comment]
I'm also experienced this issue since version 2.5.5 and later.
Please fix it @focus is nice feature to make sure scenario can running well

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
