### ISSUE TITLE
Read stepDefinitions from cypress.json

### ISSUE THREAD

**Issue by mjaeggi** [badeball/cypress-cucumber-preprocessor#441]
I'm setting a monorepo like:

-packages 
-- pack_a
--- cypress/
-- pack_b
--- cypress/ 

### Current behavior

Currently, I cant run cypress from the root folder because I need to define `stepDefinitions` in package.json like `packages/pack_a/cypress/integration` 

### Desired behavior

There is any way that I can set the `stepDefinitions` in the cypress.json inside each pack?

### Versions
* **Cypress version**: 5.1
* **Preprocessor version**: 2.5.5
* **Node version**: 12.16.1

**Comment by Pessu** [comment]
Problem is that the stepDefinitionPath.js is only able to read the path from the preprocessor configuration in package.json. Was it able to read it from the cypress config integrationFolder variable then there would be no issue I think.

Then running it like this would work.
` cypress run --config integrationFolder=packages/pack_a/cypress/integration/`

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
