### ISSUE TITLE
Possible to have feature files in a submodule and still use nonGlobalStepDefinitions=true?

### ISSUE THREAD

**Issue by esbenmilan** [badeball/cypress-cucumber-preprocessor#448]
### Current behavior

When nonGlobalStepDefinitions=true folder with step definitions must be placed at same location as feature file.

### Desired behavior

We want to have feature files and step definitions separated but still use nonGlobalStepDefinitions=true.

The reason is that we use a shared git submodule (shared between different platforms) with feature files and we don't want to include the cypress test implementation from the web platform in that repository.

Is there a solution for using nonGlobalStepDefinitions=true but still have feature files separated from the implementation?

**Comment by Frontrider** [comment]
We have the same issue, I want to put shared step definitions inside a node module while having specific stuff in the project.

**Comment by safatoujani** [comment]
I have the same problem too and I get the erreur "step implementation missing" when steps are inside a node module

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
