### ISSUE TITLE
Fails to generate cucumber-json files for all the test cases. Missed jsons !! 

### ISSUE THREAD

**Issue by pvishnu991** [badeball/cypress-cucumber-preprocessor#459]
### Current behavior

The cypress-cucumber-preprocessor plugin fails to generate the json files for all the test cases under cucumber-json folder within cypress!!
Our project makes use of BDD structure wherein multiple feature files has been created for the test scenarios and whilst executing a bulk regression run it skips a few json files within the folder cucumber-json!!

![image](https://user-images.githubusercontent.com/47185544/96448034-b7f21280-120a-11eb-830f-5772cc04bcce.png)

Jsons generated : 113
![image](https://user-images.githubusercontent.com/47185544/96448338-2505a800-120b-11eb-87cc-970df2bfc3b1.png)

Totals features picked up: 123
![image](https://user-images.githubusercontent.com/47185544/96448459-52eaec80-120b-11eb-915a-365e9faafe71.png)

Feature file example: tags has been used at a feature level which picks up all the 123 tests but generates only jsons for 113 and 10 are skipped. The same has been observed over multiple runs wherein it misses some of the json files.
![image](https://user-images.githubusercontent.com/47185544/96448522-6dbd6100-120b-11eb-9200-5cb645b1f72b.png)

### Desired behavior

The cucumber-json folder should contain all the json files for all the features executed.

### Versions

* **Cypress version**: 4.3.0
* **Preprocessor version**: 3.0.0
* **Node version**: v12.16.2

**Comment by zamioku** [comment]
Hello,

I have the same issue when running features that contain Scenario Outlines with multiple examples.

If an example fails in the scenario outline, only 1 .json is generated per scenario outline, for the example that failed.

### **Versions**:

- **Cypress version:** 5.6.0
- **Preprocessor version:** 4.0.0
- **Node version:** v12.18.3

**Comment by saint88** [comment]
Hello.
I have the same issue too when running features and getting timeout error in cy.visible().

Versions:
Cypress version: 6.0.0
Preprocessor version: 4.0.0
Node version: v11.7.0

**Comment by zamioku** [comment]
Issue still occurs in **Cypress version 6.1.0**

I've noticed that at least 1 .json per feature file is generated, but not for all scenarios or examples regardless of pass/fail

I suspect the .json is being overwritten but I can't figure out why or how to debug.

**Comment by EagleEyeGH** [comment]
I've noticed that feature files that include a dot are not named correctly (2.1 becomes 2) which causes 2.2 for example to overwrite the 2.cucumber.json

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by archanaravikumar9512** [comment]
Hello, 
I have the same issue with "cypress-cucumber-preprocessor": "^4.3.1". Anyone found a solution for the 4.3.1?
