### ISSUE TITLE
The report doesn't display the failing step

### ISSUE THREAD

**Issue by viengiang** [badeball/cypress-cucumber-preprocessor#462]
### Current behavior

Hi guys, I want to thank you for everything, this plugin very amazing, I just have a question: are we have any way to display the step having an issue due to the report just display the spec having issue and I don't know what step is failing.

![image](https://user-images.githubusercontent.com/61610632/97561988-8c91d380-1a13-11eb-9e43-2a4ed7ce7695.png)

### Desired behavior

Can we modify the report to display the step having issues? Please have a look at the image for more details:

![image](https://user-images.githubusercontent.com/61610632/97562296-fad69600-1a13-11eb-9c78-10350edc98b0.png)

### Versions

* **Cypress version**: 5.5
* **Preprocessor version**: 3
* **Node version**: 12.16.1

**Comment by arielperez82** [comment]
+1

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
