### ISSUE TITLE
cypress-tags run is no longer working

### ISSUE THREAD

**Issue by maga-polito** [badeball/cypress-cucumber-preprocessor#466]
### Current behavior

When executing command cypress-tags run ---env 'TAGS=@test and not @ignore' following message will be logged and no test will be executed

No matching tags found cypress

### Desired behavior

this command used to work on version 2.3.1

### Versions

* **5.1**:
* **4.0.1**:
* **12.18.0**:

**Comment by DanielStoica85** [comment]
I have the same issue after moving to version 4.0.0. :(

**Comment by sabinasiddiqi** [comment]
It looks like there was a release which changes the TAGS behavior but the docs weren't updated. https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/releases/tag/v4.0.0

**Comment by yaanr3is** [comment]
it should help you just as it helped me [532](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/532)

**Comment by rkrisztian** [comment]
The following PR should be related: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/607

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
