### ISSUE TITLE
Unable to run tagged tests when adding other environment variables

### ISSUE THREAD

**Issue by DanielStoica85** [badeball/cypress-cucumber-preprocessor#469]
### Current behavior

I am trying to run tagged tests, but at the same time provide a configFile as an environment variable. For some reason, this does not work, because of "No matching tags found."

### Desired behavior

I would like to be able to use both tags AND config files as environment variables.

### Test code to reproduce

`./node_modules/.bin/cypress-tags run --headless --browser chrome -e TAGS='@something',configFile=staging`

Error:

```
$ ./node_modules/.bin/cypress-tags run --headless --browser chrome --env TAGS='@something',configFile=staging
No matching tags found
Done in 0.27s.
```

### Versions

* **Cypress version**:  5.5.0
* **Preprocessor version**: 2.0.1
* **Node version**:  10.16.3

**Comment by badeball** [comment]
I suspect there's an issue in parsing the arguments and mimicking Cypress' behavior. As a workaround, can you try specifying your variables using multiple `-e` arguments?

**Comment by DanielStoica85** [comment]
Thanks for the reply, @badeball .

I tried, but it still doesn't work. It does seem to recognize the tags (because I don't get "No matching tags found" anymore) and it runs the tests, but it runs ALL tests, so it doesn't actually consider the tag that is included in the script.

This is the script I ran:

`./node_modules/.bin/cypress-tags run --headless --browser chrome -e TAGS='@something' -e configFile=staging`

Might also be worth mentioning that everything works perfectly for a "cypress:open" script, like: `cypress open -e TAGS='@something',configFile=staging`

**Comment by lgandecki** [comment]
Did you try with other versions as well? Looks like you are using a bit of an older one

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
