### ISSUE TITLE
Enhancement: Request Ability to Read Global Step Definitions(monorepo setup)

### ISSUE THREAD

**Issue by adrian861** [badeball/cypress-cucumber-preprocessor#475]
### Current behavior

Currently there is no option to specify a location for "global" step definitions that are used across multiple projects housed under a single repo.  Our only option seems to be calling a step definition file inside the project that imports the needed javascript code from the global step definition file.

### Desired behavior

We have a number of projects that will share a few step definitions, but in all other ways need to be kept separate.  It would be nice if we could specify a global location outside of each projects `cypress > integration` path that would allow for this.  That way the `.feature` file could directly reference the global step definition.

### Test code to reproduce

For an example of how we have modeled our repo, see:
https://github.com/cypress-io/cypress-example-recipes#overview

### Versions

* **5.6.0**:
* **4.0.0**:
* **12.18.3**:

**Comment by badeball** [comment]
Can't you just symlink it inside the integration-folder?

**Comment by adrian861** [comment]
Tried symlinking, that does work.  The problem with it is I'm forced to name the same as the `.feature`, as `common` is still the only recognized "shared-step" folder.  Also, this creates extra folders in each project, at least from a visual perspective, so adds some visual bloat vs what I'm requesting.

**Comment by badeball** [comment]
> Tried symlinking, that does work. The problem with it is I'm forced to name the same as the .feature, as common is still the only recognized "shared-step" folder.

What if you symlink your outside, shared directory inside the common-directory?

> Also, this creates extra folders in each project, at least from a visual perspective, and more folders at the root of the repo because they have to tie into the .feature naming schema to be recognized.

Sounds preferable in my opinion. I'd rather have dependencies be visible.

**Comment by adrian861** [comment]
> What if you symlink your outside, shared directory inside the common-directory?

I did that.  But as I mentioned, I don't want to use the `.feature` name for my step ref folder name, as I want to keep these in a single folder called `global steps refs`, or similar.



> Sounds preferable in my opinion. I'd rather have dependencies be visible.

They would be visible regardless.  What I don't like it being forced to place global step refs in a lot of folders instead of one.

**Comment by badeball** [comment]
Am I right to undestand that you want a cross-repo common-folder, while still retaining the ability to have project-specific common-folder and feature-specific folders?

**Comment by adrian861** [comment]
Yep, exactly.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
