### ISSUE TITLE
Cant specify the order of cucumber Before/After hooks if they exist in the common and step definition file 

### ISSUE THREAD

**Issue by nabeel1121014** [badeball/cypress-cucumber-preprocessor#481]
### Current behavior

With nonGlobalStepDefinitions is set to true
Having Before/After hooks in the common file and another Before/After inside test it will be executed as following 

1. Before/After Hooks inside the steps definitions file with same order they were defined 
2. Before/After hooks inside  the common file with same order they were defined 

Default order is test hooks then common hooks, Im trying to achieve some common hooks that prepare the data then inside the test Before/After hooks can continue were common hooks stopped per test need

### Desired behavior
 Ability to specify the order of cucumber hooks

As example 
`Before({ tags: "@prepareData", order: 1 }, () => {`

Without specifying the order execution will remain as default 

### Test code to reproduce

**cucumberHooksTest.feature**

    @commonPrepareData  @testPrepareData
    Scenario: Test cucumber hooks order run 
        Given Test Given

   

**cucumberHooksTestSteps.ts**
`
Before({ tags: "@testPrepareData" }, () => {
    console.log("testHook");
});
Given("Test Given",() => {})
`

**commonHooks.ts** 

`
Before({ tags: "@commonPrepareData" }, () => {
    console.log("common hook");
});
`

Output of above is 
testHook
commonHook

**Note**  we already implemented adding order for cucumber Before/After hooks if we agreed to use them will share PR for it

### Versions

* **Cypress version**: 6.0.0
* **Preprocessor version**: 4.0.0
* **Node version**: 12.4.0

**Comment by badeball** [comment]
Is this possible in cucumber-js?

**Comment by nabeel1121014** [comment]
@badeball In cucumber style nonGlobalStepDefinitions=false  everything is global this case order not valid/needed though its not supported in cucumber-js AFAIK
 
In Cypress Cucumber Preprocessor Style pattern nonGlobalStepDefinitions=true 
We have the step implementation files under `cypress/integration`  and common step/hook files, And there is no way currently to configure which hooks to run first

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by DaveClissold** [comment]
Did this ever get picked up?

**Comment by badeball** [comment]
No. Given the existence in cucumber-jvm, I'd be open to adding it here as well. Contributions are welcome.

**Comment by nilgaar** [comment]
taking care of this @badeball, will submit PR before eoy or soon after

**Comment by mi4i0** [comment]
any update @nilgaar ?

**Comment by mi4i0** [comment]
@nabeel1121014 could you share your PR if it's still valid for you
`Note we already implemented adding order for cucumber Before/After hooks if we agreed to use them will share PR for it`

**Comment by amarazing** [comment]
any updates on this? We really need order of hooks, as we may need to use different before/after hooks from multiple steps, and we want to be able to run it in our preferred order

**Comment by VidhiRambhia** [comment]
Can I pick this up @badeball?

**Comment by VidhiRambhia** [comment]
Hi @badeball, I have raised a PR with an idea of how to approach this - https://github.com/badeball/cypress-cucumber-preprocessor/pull/1128
Please do let me know your thoughts on this!

**Comment by badeball** [comment]
The above-mentioned PR has been merged and released with v19.2.0.
