### ISSUE TITLE
Enable wildcards in path configurations

### ISSUE THREAD

**Issue by vio-codes** [badeball/cypress-cucumber-preprocessor#483]
Hello I just finished playing around with the example provided by you guys.
I'm trying to setup my own project now.

I want to have the following project structure:
![Screenshot 2020-12-09 at 15 33 38](https://user-images.githubusercontent.com/53267372/101636690-5b55eb80-3a34-11eb-9a0c-bc69e3649e5e.png)
But I'm having issues with understanding the documentation, and what should I put in my package.json for my specific structure.

What should I put in:
> "cypress-cucumber-preprocessor": { }

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
