### ISSUE TITLE
While editting the js file cypress test runner throws  Fetching resource at '/__cypress/tests?p=cypress\support\index.js' failed

### ISSUE THREAD

**Issue by scrumvisualize** [badeball/cypress-cucumber-preprocessor#491]
### Current behavior

While modifying and saving the step definition.js file, I am getting below error in test runner. Once we close the `cypress test runner` and I am able to run the same test without any issues/error.

![image](https://user-images.githubusercontent.com/5972626/103256470-21478c00-49d9-11eb-8ac4-1d756b0b8914.png)

### Desired behavior

Ideally it should successfully allow to modify the `.js` file without any issues.

### Test code to reproduce

Feature: Test feature
    Scenario: Verify the display of toast message
        Given I log in to mobile application
        And I click on "Notifications" in flyout menu

While editing the `.js` file which has the following step definition `And I click on "Notifications" in flyout menu`, system throws the above error. 
Now close the test runner and run again the same test. There is no error anymore and test run successfully.
       
### Versions

* **Cypress version**: 6.2.0
* **Preprocessor version**:  2.5.5
* **Node version**: v12.18.4

**Comment by badeball** [comment]
You're literally describing the most basic use case and this just doesn't help me at all at reproducing your issue. You need to provide us with a cloneable repository. Don't post large bodies of codes with filenames, it's not interesting.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
