### ISSUE TITLE
Tags functionality is not working as expected:No matching tags found

### ISSUE THREAD

**Issue by shyamprasadsdet** [badeball/cypress-cucumber-preprocessor#493]
### Desired behavior

Tags functionality is not working as expected:No matching tags found
When i use npx cypress run -e TAGS='@LoginScenario' all feature file scenarios are getting executed .
Please let me know any solution for this.

### Test code to reproduce
Feature: Google Functionalities

    @LoginScenario
    Scenario: Verify Login Functionality
    Given user navigates to Login page
    And user enters valid credentials
    Then User is able to login in to application

on Terminal::
**npx cypress-tags run  'TAGS=@LoginScenario' --browser chrome** 
Using cypress.json configuration:
Spec files:  {cypress/integration/**/*.{feature,cypress/integration/features}}
**No matching tags found**

### Versions

* **Cypress version**:^5.5.0
* **Preprocessor version**:4.0.0
* **Node version**:14.15.1

**Comment by appendixshuffle** [comment]
Any update on this issue ??

**Comment by frnc07** [comment]
Try this command instead:
npx cypress-tags run -e TAGS="@LoginScenario" --browser chrome

**Comment by cvolant** [comment]
I tried the above suggestion, but it does not solve the issue.

**Comment by antonversal** [comment]
It looks like how `cypress-tags` matches spec files changed. 
You need to fix `testFiles` in `cypress.json`:
from:
```
"testFiles": "**/*.{feature,features}",
```
to something like this:
```
"testFiles": "**/*.feature",
```
You can see which spec files are mutched from `cypress-tags` output,
before the fix:
```
Spec files:  {cypress/integration/**/*.{feature,cypress/integration/features}}
```
after:
```
Spec files:  cypress/integration/**/*.feature
```

**Comment by erik-inkapool** [comment]
@antonversal while that solution works if all you have it `.feature` files it can be solved to use the correct glob by using an array, like so:
```
"testFiles": ["**/*.{feature,features}"],
```
This is because the preprocessor will [split testfile string on `,`](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/021010dcd6e39a7efd31ab1fbb86756a1d49ed39/cypress-tags.js#L55), but leave arrays alone.

Using that config the spec files output will work:
```
Spec files:  cypress/integration/**/*.{feature,features}
```

**Comment by rkrisztian** [comment]
I found this issue late, but anyway created a PR because the script should work anyway for arbitrarily complex glob patterns, no matter how we specify the test files, in my opinion: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/607

**Comment by gogoid88** [comment]
only use double quotes surrounding the tag values single quotes dont work.
npx cypress-tags run -e TAGS="@Only"

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
