### ISSUE TITLE
cypress-tags not able to pick the correct scenario from a feature 

### ISSUE THREAD

**Issue by pvishnu991** [badeball/cypress-cucumber-preprocessor#496]
The cypress-cucumber-preprocessor dependency installed doesn't work well when it comes to features with multiple scenarios which has individual tags in them. 

### Current behavior

cypress tags fails to pick up the correct scenario from multiple scenarios within a feature
Command:
./node_modules/.bin/cypress-tags run -e TAGS='<tagname>'
The above command picks up the correct feature but executes all the scenarios within it.

### Desired behavior
./node_modules/.bin/cypress-tags run -e TAGS='<tagname>'
Should pick up the respective scenario with the tagname under the feature and execute only that!!

### Test code to reproduce

https://github.com/TheBrainFamily/cypress-cucumber-example

I have cloned the above git branch and tried executing the below command which was supposed to pick up only the second scenario from the GitHub.feature file but executes all the scenarios instead.
./node_modules/.bin/cypress-tags run -e TAGS='@another-tag-to-include and @github' --browser chrome --headless

@feature-tag @github-tag
Feature: The Github

  I want to GitHub Things

  @tag-to-include
  Scenario: Opening GitHub
    Given I open GitHub page
    Then I see "GitHub" in the title

  @github @another-tag-to-include
  Scenario: Opening GitHub again
    Given I open GitHub page
    Then I see "GitHub" in the title

Please note that i have introduced and additional tag(@github) in the second scenario to uniquely pick it up.
![image](https://user-images.githubusercontent.com/47185544/105069360-bdfdc680-5a79-11eb-83ce-1067fad419f4.png)

### Versions

* **Cypress version**: 5.2.0 /^4.9.0
* **Preprocessor version**: ^2.5.4/4.0.0
* **Node version**: 12.16.2

**Comment by appendixshuffle** [comment]
HI
Any update on this ?

**Comment by pvishnu991** [comment]
> Any update on this ?

Issue is still on with the cypress preprocessor tags. We kind of figured this out at a later stage of development and had to move on to a single scenario per feature strategy. This kind of makes the UI pack look quite big. So if any of you guys have figured out a way to resolve this , i would really appreciate some help on that.

Thanks

**Comment by frnc07** [comment]
Hey @pvishnu991 the above snippet shows exactly how it is supposed to be working. 'Tests' column are the total number of scenarios in your feature file which is 2 in your case. It clearly says 1 test Passing and 1 test Pending which means it only ran one scenario and the other one is still pending. Hope this helps.

**Comment by appendixshuffle** [comment]
@frnc07 Actually you're right ;-) I didn't noticed this screen. I was reviewing problems with tags because I'm getting "No matching tags found" when I'm trying to run only particular scenario. 
In this case Test Case opening GitHub is actually skipped and that's expected behavior. 
Thx frnc07 for the fresh look!
On the other hand with cypress-tags something is wrong - #493

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
