### ISSUE TITLE
Feature: Enable the ability to use cy.log outputs as "steps" in cucumber.json for reports

### ISSUE THREAD

**Issue by GideonCS** [badeball/cypress-cucumber-preprocessor#517]
### Current behavior
Currently when using `cy.log`, all of the output is ignored. None of it is output into cucumber.json files which are generally used in reports. This makes it difficult to view what's happening inside my step definitions during a test run on CI.

### Desired behavior
I would like to be able to see my cypress logs in the json file so that I can easily view it alongside the rest of the test output.

E.X If I have this test (I know it's trivial):
```
Scenario: I log in and post a tweet
  Given I am logged in
  And I go to the homepage
  When I post a tweet with text "tweet"
  Then I see my tweet with text "tweet"
```

And I have this step definition with this command:

```
// in commands.ts
Cypress.Commands.add('login', (username: string, password: string) => {
  cy.log('Logging in as user', username || Cypress.env('user').email)
  cy.APIRequest({
    method: 'POST',
    url: '/accounts/login/',
    body: {
      username: username || Cypress.env('user').email,
      password: password || Cypress.env('user').password,
  });
});
```

```
// in login.cucumber.ts
Given(/^(I am logged in|I log in)$/, () => {
  cy.login();
});
```

I have other commands that generate users and save them to env variables, so at runtime I want to know what they are for logging purposes. So I'd like to be able to view my report that says something like this on CI by pulling it out of the test output.

```
 Given I am logged in
 LOG Logging in as user "foo@gmail.com"
  .........
```

Please let me know if I can clarify in any way.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by kevinshahfws** [comment]
Is this feature added??

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md#attachments
