### ISSUE TITLE
Can't run scenarios with different tags

### ISSUE THREAD

**Issue by hari49951** [badeball/cypress-cucumber-preprocessor#518]
I have a feature file like below and want to run some scenarios with tags (e.g run scenarios with @FirstTest, @focus tags)

Feature: Test login
    Background:
        Given Refresh page

   @FirstTest
    Scenario: Test the login feature
        Given I visit the zero.webappsecurity.com site
  @focus
    Scenario: Click sign in
        Then I click sign in

  @not-focus
    Scenario: Click signout
        Then I click signout

### Current behavior
When I run the scenarios using "npx cypress-ntlm run -e TAGS='@FirstTest OR @focus' configFile=test --spec 'cypress/integration/**/*.feature' only one scenario with tag FirstTest is running, other scenario with tag focus is being skipped.

Note: I use cypress-ntlm-auth plugin for Windows Authentication so to open or run tests syntax should have "cypress-ntlm"

### Desired behavior
Run all scenarios having tags @FirstTest, @focus

### Versions

* **Cypress version**: 6.4.0
* **Preprocessor version**: 4.0.0
* **Node version**: 12.18.0
* cypress-ntlm-auth : 3.1.4

**Comment by badeball** [comment]
I'm not able to reproduce the issue. Using tags I can successfully the scenarios tagged with `@firsttest` / `@Focus`. Please provide a repository containing a minimal example that illustrates it.

**Comment by sandra-ouadghiri** [comment]
Have a look at #401 in case that's the problem?

**Comment by chrisbward** [comment]
Also having this issue

**Comment by hari49951** [comment]
@badeball I use cypress-ntlm-auth plugin (https://github.com/bjowes/cypress-ntlm-auth) to access my application since it requires authorization behind proxy. So we can't reproduce unless we test against an application where we need to use cypress-ntlm-auth for authorization. The syntax to open cypress test via this plugin is "npx cypress-ntlm open" where as with cucumber to run specific tags we have to use "npx cypress-tags run".

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
