### ISSUE TITLE
Feature Request: Having variables in scenario names (Scenario: StringWithVariable)

### ISSUE THREAD

**Issue by sandra-ouadghiri** [badeball/cypress-cucumber-preprocessor#521]
**Cypress (native)**
When using Cypress, we can name a scenario it(`Login using resolution ${Cypress.env('viewportWidth')} x ${Cypress.env('viewportHeight')}`, () => { scenarioContent})

**Cypress-cucumber-preprocessor**
Using cypress-cucumber-preprocessor I can't:
  Scenario: `Login using resolution ${Cypress.env('viewportWidth')} x ${Cypress.env('viewportHeight')}`
or Scenario: Login using resolution ${Cypress.env('viewportWidth')} x ${Cypress.env('viewportHeight')}
or Scenario: Login using resolution <Cypress.env('viewportWidth')> x <Cypress.env('viewportHeight')>
...

**Feature Request**
It would be nice to be able to include Cypress env. variables in Scenario name. Just so that reports always stay cohesive with the env parameters (if someone changes that, reports stay cohesive and reflect what was executed, it's not just hidden within the steps).

**Comment by mike-mccormick** [comment]
Weirdly, I came here questioning this exact thing! I'm coming from another test environment which made it really difficult to pass information between steps. 

Rather than write something like:

Scenario: Admin user creates a record

**Comment by derryx** [comment]
Hi!

I would use the standard cucumber features for this:

```
Scenario Outline: Login using resolution <width>x<height>
  Given I have a viewport with the resolution <width>x<height>
  ....

  Examples:
    | width   |  height  |
    |  1024   |   768    | 
    |   800   |   600    |
```

CU
Thomas

**Comment by sandra-ouadghiri** [comment]
@derryx Hi !
Thanks for the feedback.

In my case, it's not a scenario outline, but a plain scenario. In your example, imagine you want width and height in your cypress.json for example just so that the dev reading the report know the config the test had.

That's my issue :/.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
