### ISSUE TITLE
Stubbing API requests and waiting for responses

### ISSUE THREAD

**Issue by bensampaio** [badeball/cypress-cucumber-preprocessor#53]
I have some tests written in cypress that stub some API requests, fill in forms, submit those forms and the ending result is dependent on the stubbed responses. That works really well. However, I am having some difficulties translating those flows of actions into gherkin scenarios.

An example:

login.js
```
cy.server();

cy.visit('/login');

cy.route({
    method: 'POST',
    response: 'fixture:login/success.json',
    status: 204,
    url: '/api/login',
}).as('postLogin');

cy.get('#login-form-username').type('username');
cy.get('#login-form-password').type('somepassword');
cy.get('#login-form').find('button[type="submit"]').click();
cy.wait('@postLogin').its('status').should('be', 204);
```

In my opinion the logical way to convert this flow of actions to gherkin would be:

login.feature
```
Given I visit the "/login" page
When I fill in the username field in the login form with "clinian@karify.com"
And I fill in the password field in the login form with "somepassword"
And I submit the login form
Then I am logged in
```

However this won't work since the last step is the one defining what stub should be used, but the submit already occurred. One solution would be to have a step definition for stubbing explicitly. Another solution would be to combine the last two steps in one step. However, those two sound weird to me. Are those the only solutions? Are there any conventions on how to do this? Could you add examples on how to do this?

Besides that how can we handle async actions in step definitions? I also have cases where I need to wait for some action before continuing.

**Comment by volkanogretmen** [comment]
_I see that your post is quite a while ago, but I'll try it anyway._ 

I'm not sure why you would writeout the Gherkin steps so extensively. My suggestion would be to keep it simple:

`Given I visit the "/login" page
When I am successfully logged in
Then the stub response should be "204"`

You will then have the possibility to reuse this for other response codes. I hope I understood you correctly!

**Comment by bensampaio** [comment]
So you are suggesting that I create a step definition that fills in the form and sets the stub all in one? I understand the idea but doesn't feel so reusable. Besides that, It hides a lot of information about what is actually being done. What if I have a more complex form? Should I always have a single step definition that fills in an entire form and sets a stub? Is that a common practice in gherkin?

**Comment by FrancisBourgault** [comment]
You could store the stub response status in a cypress variable (using "as()"). Then assert it later

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
