### ISSUE TITLE
Running a feature from Webstorm doesn't work

### ISSUE THREAD

**Issue by oosterholt** [badeball/cypress-cucumber-preprocessor#530]
In Webstorm, each scenario is detected as test with an 'execute test' button. The test however cannot be executed.

![image](https://user-images.githubusercontent.com/730953/111473776-ad8d6380-872b-11eb-8ef2-834dd6a0315c.png)

### Current behavior

    Error running 'Scenario: Opening the dashboard tab a...': 
    Specify non-empty path to Cucumber package

![image](https://user-images.githubusercontent.com/730953/111473929-ceee4f80-872b-11eb-9058-2f2857d5db42.png)

**Comment by Kepro** [comment]
ehm, dude, it's WebStorm issue not issue of this package...

**Comment by badeball** [comment]
@Kepro is right, this isn't something controlled by the preprocessor. Furthermore, if you are able to control the command invoked, you would still have to have a way to run a single test based off a line number. Cucumber-js has this, but this preprocessor doesn't. In other words, this feature (running by play icon in an IDE) is currently not available.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
