### ISSUE TITLE
couldn't run feature files 

### ISSUE THREAD

**Issue by nidhalBougatf** [badeball/cypress-cucumber-preprocessor#531]
Hey all,
I am having some issues while running the *.feature files. Actually, it's always showing this error :

### Current behavior

login.feature
![loginfeature file](https://user-images.githubusercontent.com/22817092/111915816-60d1c180-8a78-11eb-8ec2-821f3ef0774d.PNG)

![feture file error](https://user-images.githubusercontent.com/22817092/111915561-3f240a80-8a77-11eb-832a-6baeda41df03.PNG)

and when running the login.js file 
![loginjs](https://user-images.githubusercontent.com/22817092/111915806-5b747700-8a78-11eb-8d61-ae9af351cdba.PNG)

![error js file](https://user-images.githubusercontent.com/22817092/111915570-48ad7280-8a77-11eb-9031-0085a0d1dff7.PNG)

### Desired behavior

I have a js file, written only in cypress without Gherkin language, that is running correctly.
test.js
![testjs](https://user-images.githubusercontent.com/22817092/111915785-48fa3d80-8a78-11eb-99dc-6a179ff45053.PNG)
Running screenshot
![working other js file](https://user-images.githubusercontent.com/22817092/111915646-975b0c80-8a77-11eb-84c8-2cc9aa2002a9.PNG)

This is my configuration files :
Cypress.json
![cypressjson](https://user-images.githubusercontent.com/22817092/111915758-2ec05f80-8a78-11eb-9173-90fa57f71fb9.PNG)

index.js
![indexjs file](https://user-images.githubusercontent.com/22817092/111915767-34b64080-8a78-11eb-8b74-c91c533f25f7.PNG)

package.json
![packgeJSON part1](https://user-images.githubusercontent.com/22817092/111915774-3bdd4e80-8a78-11eb-9b47-4babbc62c4ba.PNG)
![packgeJSON part2](https://user-images.githubusercontent.com/22817092/111915776-3da71200-8a78-11eb-9db7-f94134f18cfb.PNG)
 

### Versions

Things that I've tried :
- updating cypress to 6.8.0
- updating preprocessor to 4.0.1
- updating node to 14.16.0
- updating typescript +4
- clear cache of cypress

**Comment by sandra-ouadghiri** [comment]
@nidhalBougatf it's probably your tsconfig.json file.
This may help (please note that this config involves rules that you may not want, just take what you need).

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "cypress",
    "target": "es2018",
    "module": "commonjs",
    "lib": ["ES2020", "dom"],
    "strict": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": false,
    "types": ["node","cypress"],
    "forceConsistentCasingInFileNames": true
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules", "reports", "**/*.js"]
}
```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
