### ISSUE TITLE
Does not generate cucumber.json report in azure devops pipeline

### ISSUE THREAD

**Issue by gretherMG** [badeball/cypress-cucumber-preprocessor#535]
Hello good afternoon, I am using cypress with cucumber in my local, the report cucumber-json is generated correctly, however in the azure pipeline the report is never generated, does anyone have any idea what may be happening?

local
![image](https://user-images.githubusercontent.com/78503594/112484676-269e4380-8d48-11eb-9926-37c41adebc15.png)

azure devops pipeline
![image](https://user-images.githubusercontent.com/78503594/112490940-d3c78a80-8d4d-11eb-99ca-387418def887.png)

the json is not generated

Versions
cypress 6.8.0
cucumber 4.0.1

someone who has any idea what may be happening please.

**Comment by sandra-ouadghiri** [comment]
Hi @gretherMG 
I have an azure pipeline and I got my cucumber.json files ok.
This said, for reporting to be in the cool UI reporting in Azure I have to generate JUnit (xml) reports, so Azure understands the report. Just sharing in case that would make you drop the cucumber generation.

Anyway
- How do you trigger cypress in your pipeline (what command line). Is it the same as the local one? Only 'run' (vs open' generate reports & artifacts such as video & screenshots. Also, when in local vs when in pipeline, make sure you are on the same folder when line gets executed. Maybe your cucumber-json folder reference is relative, and you just execute your pipeline from another place, making the folder retrieval impossible.
- I see docker. Dockers dies instantly after usage. Do you look before it gets killed? I guess yes.
- Your local shows that cucumber-json is a folder. Your pipeline screenshot doesn't show much without context.

Do you have any error message? Did you try logging?

If none of this help, then you'll need to provide more for us to help.
- Pipeline command line
- Pipeline pwd before cypress execution
- Reports folder configuration
- Reporter full configuration

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
