### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module

### ISSUE THREAD

**Issue by hect1c** [badeball/cypress-cucumber-preprocessor#537]
### Current behavior

I am trying to setup cypress-cucumber-preprocessor in my project. Cypress + React + Typescript

I have it all working as expected but when I try and setup cypress-cucumber-preprocessor with typescript I get the following error `Error: Can't walk dependency graph: Cannot find module '^cypress/lib/auth.helper'`

This happens with any custom module aliases used in my cypress files.

Here is my plugin index file:

```
const browserify = require('@cypress/browserify-preprocessor')
const cucumber = require('cypress-cucumber-preprocessor').default
const resolve = require('resolve')

module.exports = (on, config) => {
 const options = {
    ...browserify.defaultOptions,
    typescript: resolve.sync('typescript', { baseDir: config.projectRoot }),
  }

  on('file:preprocessor', cucumber(options))
}
```

Below is my tsconfig.json file in cypress directory

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "target": "es6",
    "lib": ["es6", "dom"],
    "types": ["cypress"],
    "isolatedModules": false,
    "allowJs": true,
    "noEmit": true,
    "baseUrl": "..",
    "paths": {
      "^cypress": [
        "../cypress/*"
      ]
    }
  },
  "include": [
    "../node_modules/cypress",
    "**/*.ts"
  ],
  "exclude": [],
}
```

Below is my tsconfig file at root

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "sourceMap": false,
    "noImplicitAny": false,
    "noImplicitReturns": false,
    "noImplicitThis": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "rootDirs": ["src/__generated__", "src/**/__generated__"],
    "baseUrl": ".",
    "paths": {
      "@static/*": [
        "./public/static/*"
      ],
      "@generated/*": [
        "./src/__generated__/*"
      ],
      "@*": [
        "./src/*"
      ]
    }
  },
  "include": [
    "src",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "next.config.js",
    "public",
    "cypress",
    "jest.setup.js",
    "release.config.js"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.test.ts",
    "**/*.test.tsx",
    "**/*.graphql",
    "cache/Cypress/**"
  ]
}

I've tried different examples with typescript and tsify but they did not work as well and got same issue. 

```
### Desired behavior

I would like to get the cypress-cucumber-preprocessor working with typescript in my current project.

### Test code to reproduce

The code is a bit large but will try and provide a minimal working clone.

### Versions

* **Cypress version**: 6.8.0
* **Preprocessor version**: 4.0.3
* **Node version**:

**Comment by hect1c** [comment]
Hey, 

I was able to reproduce this in a separate project: https://github.com/hect1c/cypress-cucumber-nextjs-typescript

If you do the following you will see the error:

- `npm i`
- `npm run dev`
- in a separate terminal `npm run e2e`

This will open the cypress chrome browser. From there just click on the `Builder.feature` and then you will see the error message.

**Comment by hect1c** [comment]
Hey, did I not provide enough information? Would be great if I could get some guidance on this as I would like to very much use this plugin and start porting our tests over to Gherkin syntax. Thanks ahead of time for your support on this.

**Comment by lgandecki** [comment]
Hello, sorry to keep you waiting. The reproduction will definitely be very helpful, thanks for that. One of us should be able to take a look at it sooner than later. At the same time please remember we are volunteers and are doing this for free in our spare time.  :) So silence here doesn't mean there is something wrong with your report.. 

@MateuszNowosad maybe you would be able to take a look at this one? Besides veryfing that it fails on your end as well I'd check with older versions of cypress/our plugin. But obviously take any steps you feel are best :)

**Comment by badeball** [comment]
I'm not able to reproduce the issue you're describing using the mentioned repository. It runs, albeit not without errors, but with a different and expected error.

Can you add a simple test that is not a Cucumber-test, merely containing the following and see that it runs under the same configuration?

```js
it("should work", () => {
  expect(true).to.eq(true);
});
```

.. if that *doesn't* run and you observe the same error, then this is in fact not an issue with the preprocessor.

**Comment by hect1c** [comment]
@lgandecki Thanks for the response, and really appreciate the support you guys do on the plugin and the community.

@badeball Sorry I think I was not clear

The issue is more so related to module resolution using typescript + cucumber following the information here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#with-out-of-the-box-support

I also have a lot of custom module resolvers trying to access them using `@module/lib`. It seems when I add cucumber following the documentation using `browserify` my custom module imports are no longer working which is the error you are getting in the reproducible project.

I've tried various recommended solutions:

- https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/324
- webpack example: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/324
- without webpacke exampl: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/324

I'm struggling to get the cucumber implementation to work with typescript and custom module imports. Any help is greatly appreciated, thanks for the great plugin.

**Comment by MateuszNowosad** [comment]
@hect1c
I took a look at this issue and tried to reproduce it with a provided example but I wasn't able to just like @badeball. I did some digging and decide that a better approach than fixing yours will be to make my own using your configs and I think I succeeded with creating an example with only dependencies being cypress, typescript, and cypress-cucumber-preprocessor. 

I forked cypress-cucumber-typescript-example and added a branch with a title [537-Cant_walk_dependency_graph](https://github.com/MateuszNowosad/cypress-cucumber-typescript-example/tree/537-Cant_walk_dependency_graph)

To run it you have to:
`npm install` and run `npm test`

It also includes a test suggested by @badeball and it passes so I will be digging down on this issue and when I figured something out I will update you on this.

**Comment by zjkipping** [comment]
Is there any update on this? @MateuszNowosad @hect1c  I'm having this same issue when trying to access a global path listed in my tsconfig.json. I'm in a NX workspace so the global paths are coming from a root tsconfig.base.json & the cypress application extends from that. It doesn't appear to be looking at the tsconfig in the cypress application at all? Is there a way to pass this into the options for the cucumber-preprocessor? For now I might resort to relative paths instead of globals & see if that is a spot fix...

**Comment by zjkipping** [comment]
It seems the walking dependency graph issue happens irrespective of the tsconfig extension. I added the global path to the tsconfig located in the cypress application & the issue still persists. I confirmed the relative pathing works currently as a stop gap. Though it's a rather bad stop gap due to auto importing using the tsconfig's global paths.

**Comment by MateuszNowosad** [comment]
I've tried to pinpoint the issue but I can't exactly find the root cause. Since I wasn't making any progress on this and this ticket didn't get any responses with more information for me to go on I've put it on the back burner. Any extra information around this issue is valuable to me so if you find out anything worth mention, that you left out from your previous comments, I would gladly take a look at it (preferably in a form of a repository featuring something new about this problem). I will try to allocate some time to revisit this. As a side note, I encourage you to take a look around our code, sometimes it's easier to solve the problem when you know the exact use case.

**Comment by zjkipping** [comment]
I'll try to whip up small NX workspace repository based on this client project's setup and see if I can replicate the Nx + Cypress + TS + Cucumber issues I'm currently experiencing. Thanks for the fast response @MateuszNowosad

**Comment by fonzerelly** [comment]
+1 We have the same problem.

**Comment by hect1c** [comment]
I'm still having the issue and will try and replicate it using the forked repo that @MateuszNowosad created and go from there. 

Similar to @zjkipping it works with relative paths but I'm importing / using a lot of different utils and helpers scattered through the project so using relative path would not be practical. Will also try and scan through the code to see if I can find anything that may help.

**Comment by zjkipping** [comment]
Here is the github repo I promised:

Issues with the "out-of-box support": https://github.com/zjkipping/nx-cypress-cucumber/tree/out-of-box-support
Issues with the "webpack config": https://github.com/zjkipping/nx-cypress-cucumber/tree/webpack-config

To run the branches you would just need to `yarn install` & then run `yarn e2e`.

The "out-of-box-support" branch is throwing an error with walking the dependency graph.
The "webpack-config" branch is throwing an error about `err.replace` being undefined.

The webpack config one has Nx's typescript preprocessor for TS thrown on top. I've had the same "error" using just a straight up normal webpack config as well as seen in that forked repository above.

**Comment by pietschy** [comment]
Thanks @zjkipping for taking the time to reproduce this. 

We're getting the same issue in our project.  Any modules referenced from the paths in `tsconfig.base.json` break with the  `Can't walk dependency graph: ` error.

I've also spent the day battling webpack (without success) and the `err.replace` issue seems to be related to cypress not supporting webpack 5 yet.  See https://github.com/cypress-io/cypress/issues/8948 and https://github.com/cypress-io/cypress/issues/8948#issuecomment-737156406

This Webpack 5 support issue claims to be almost released but I can't see that its landed yet: https://github.com/cypress-io/cypress/issues/8900#issuecomment-867290832

**Comment by jtolotta** [comment]
Cypress: 8.3.0
Webpack: 5.5.0

In the `cypress/support/index.js` file I have the following that loads the `cypress-cucumber-preprocessor` module.
```
  on('file:preprocessor', (file) => {
    if (file.filePath.match(/\.(feature|features)$/)) {
      return cucumber()(file);
    }
    return webpackPreprocessor(webpackPreprocessorOptions)(file);
  });
```
Because the `file:preprocessor` can only execute either the `cypress-cucumber-preprocessor` or the `@cypress/webpack-preprocessor` the alias paths do not get applied to the Cucumber step definitions and any alias imports they use causing the `
Error: Can't walk dependency graph: Cannot find module` message to be displayed.
For all other `*.spec.js` files, these are correctly processed with the specified webpack aliases correctly.

I actually tried the [link-module-alias](https://www.npmjs.com/package/link-module-alias) npm package and actually got past the dependency graph error as it created all the aliases as static links, however, I ran into the dreaded `SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'` error.

I tried configuring Babel to try and get around this, but no luck.

**Comment by badeball** [comment]
You're not meant to conditionally use the preprocessor like that, because then, as you're experiencing, all of you other webpack configurations such as aliases doesn't get applied. Rather, take a look at [this](https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example) example and use a single preprocessor.

**Comment by jtolotta** [comment]
> you're not meant to conditionally use the preprocessor like that, because then, as you're experiencing, all of you other webpack configurations such as aliases doesn't get applied.

@badeball You are correct, I was trying to get it working with Webpack 5, but I guess the project will eventually be updated soon.
Works great with Webpack 4 so thanks for that.

Reference: **Webpack 5 support** https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/issues/6

**Comment by cyrixmorten** [comment]
Think I have been over all the approaches I could find and kept running into one issue or the other. 

Am currently using the following configuration in `index.js`:

```javascript
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');
const webpack = require('webpack');

module.exports = (on, config) => {
  on('file:preprocessor', preprocessTypescript(config, (wpConfig) => {
    wpConfig.resolve.fallback = {
      ...wpConfig.resolve.fallback,
      'path': require.resolve("path-browserify")
    };
    wpConfig.plugins.push(
      new webpack.ProvidePlugin({
        process: 'process/browser',
      })
    );
    wpConfig.module.rules.push(
      {
        test: /\.feature$/,
        use: [{
          loader: 'cypress-cucumber-preprocessor/loader'
        }]
      },
    );
    return wpConfig
  }));
};
```

It is a workaround as it still contains the deprecated `preprocessTypescript` but it allows us to run our e2e tests after upgrading to Nx 12.9.0

The configuration was found here: https://github.com/nrwl/nx/issues/1276#issuecomment-856018301

**Comment by rkrisztian** [comment]
@cyrixmorten , I just noticed this issue after bumping into the deprecation myself. I gave [an alternative solution](https://github.com/nrwl/nx/issues/1276#issuecomment-934324523) there that does not use deprecated Nx code.

As for `TypeError: err.replace is not a function`, [that isn't an issue anymore](https://github.com/cypress-io/cypress/issues/8948#issuecomment-934032159).

**Comment by yann-combarnous** [comment]
Same issue here, cannot get Typescript's "baseUrl" or "alias" honoured by the browserify, with the setup described in this project. See reproduction repo here: https://github.com/yann-combarnous/cypress-cucumber-ts-baseurl

**Comment by Viktor-Bredihin** [comment]
Same problem here, any solution/workaround?

**Comment by Viktor-Bredihin** [comment]
@yann-combarnous
Hey, did u find any workaround?

**Comment by yann-combarnous** [comment]
> @yann-combarnous
> Hey, did u find any workaround?

Suspect this is an issue with Cypress Browserify preprocessor rather: https://github.com/cypress-io/cypress-browserify-preprocessor/issues/53

**Comment by JurajJakubov** [comment]
What worked for me (cypress + cucumber + typescript)
Webpack file

```
const path = require('path');
const webpack = require("webpack");

module.exports = {
    resolve: {
        alias: {
            '@alias/something/testing': path.resolve(path.join(__dirname, '../../dist/something/testing')),
            '@alias/somethingElse/testing': path.resolve(path.join(__dirname, '../../dist/somethingElse/testing'))
        },
        extensions: ['.ts', '.js'],
        fallback: {
            path : require.resolve("path-browserify")
        }
    },
    module: {
        rules: [
            {
                test: /\.ts$/,
                exclude: [/node_modules/],
                use: [
                    {
                        loader: 'ts-loader',
                        options: {
                            configFile: 'tsconfig.e2e.json'
                        }
                    }
                ]
            },
            {
                test: /\.feature$/,
                use: [
                    {
                        loader: 'cypress-cucumber-preprocessor/loader'
                    }
                ]
            },
            {
                test: /\.features$/,
                use: [
                    {
                        loader: 'cypress-cucumber-preprocessor/lib/featuresLoader'
                    }
                ]
            }
        ]
    },
    plugins: [
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),
    ]
};
```

plugins/index.js

```
const webpack = require("@cypress/webpack-preprocessor");

module.exports = (on, config) => {

    const options = {
        webpackOptions: require("PATH TO WEBPACK FILE")
    };
    on("file:preprocessor", webpack(options));
  
};
```

**Comment by rkrisztian** [comment]
@JurajJakubov , correct me if I'm wrong, but that seems to be the webpack-based solution so that it does not use browserify, but we have seen similar configs before even for Webpack 5, like https://github.com/nrwl/nx/issues/1276#issuecomment-934324523 . One difference I could find in your code is paths configured in the webpack config, rather than in the tsconfig file... Which is unconventional.

**Comment by JurajJakubov** [comment]
@rkrisztian yes.

**Comment by 8byr0** [comment]
Just came across the same issue using browserify + typescript and solved it like this:

```javascript
// cypress/plugins/index.js

/// <reference types="cypress" />
const browserify = require('@cypress/browserify-preprocessor');
const cucumber = require('cypress-cucumber-preprocessor').default;
const path = require('path');
const resolve = require('resolve');

module.exports = (on, config) => {
  const { browserifyOptions } = browserify.defaultOptions;

  browserifyOptions.paths = [
    // the process.cwd() depends on the cypress process being started from
    // the project root. You can also use an absolute path here.
    path.resolve(`${process.cwd()}/src`),
    // Include any other path you want to access from cypress here
  ];

  const options = {
    ...{ ...browserify.defaultOptions, browserifyOptions },

    typescript: resolve.sync('typescript'),
  };

  on('file:preprocessor', cucumber(options));

  // other config here

  return config;
};
```


Hope this helps !

My solution is heavily inspired by this answer on stack overflow: https://stackoverflow.com/questions/58592497/how-to-use-import-with-absolute-paths-in-cypress-tests-built-with-parceljs

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by Manuel-Suarez-Abascal** [comment]
I'm having the same issue with the current version. Does anybody has found an easy workaround this?

**Comment by scottrippey** [comment]
I too was experiencing this issue, using the `cypress-tags` plugin, and was able to solve it with @8byr0 's solution.
For anyone wanting to reduce this fix into a 1-liner, here's what I did:
```diff
  // cypress/plugins/index.js
  const { tagify } = require('cypress-tags');
  module.exports = (on, config) => {
    
+   require('@cypress/browserify-preprocessor').defaultOptions.browserifyOptions.paths = [
+     './src' // (same value as in `tsconfig.json > baseUrl`)
+   ];
  
    on('file:preprocessor', tagify(options));
  
    return config;
  };
```
