### ISSUE TITLE
Getting error while running the cypress run command - Cannot read property 'name' of undefined.

### ISSUE THREAD

**Issue by singhrajkr** [badeball/cypress-cucumber-preprocessor#541]
Need help with cypress-cucumber-preprocessor plugin for Cypress.
Getting error while running the cypress run command( But it works fine with cypress open) -
Here are the logs

cypressiojsnodejsbdd@1.0.0 test:all
cypress run --spec "*/.features"

====================================================================================================

(Run Starting)

┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Cypress: 6.8.0 │
│ Browser: Electron 87 (headless) │
│ Specs: 1 found (All.features) │
│ Searched: *.features │
└────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────

Running: All.features (1 of 1)

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (.....\CypressIOJsNodejsBDD\cypress\plugins\index.js)

TypeError: Cannot read property 'name' of undefined
at .....\CypressIOJsNodejsBDD\node_modules\cypress-cucumber-preprocessor\lib\featuresLoader.js:114:64
at Array.map (<anonymous>:null:null)
at module.exports ( .....\CypressIOJsNodejsBDD\node_modules\cypress-cucumber-preprocessor\lib\featuresLoader.js:112:6)
at Stream.end ( .....\CypressIOJsNodejsBDD\node_modules\cypress-cucumber-preprocessor\lib\index.js:21:18)
at _end ( .....\CypressIOJsNodejsBDD\node_modules\through\index.js:65:9)
at Stream.stream.end ( .....\CypressIOJsNodejsBDD\node_modules\through\index.js:74:5)
at DestroyableTransform.onend ( .....\CypressIOJsNodejsBDD\node_modules\readable-stream\lib_stream_readable.js:577:10)
at Object.onceWrapper (events.js:421:28)
at DestroyableTransform.emit (events.js:327:22)
at endReadableNT ( .....\CypressIOJsNodejsBDD\node_modules\readable-stream\lib_stream_readable.js:1010:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)

Note - ..... means local root dir.

### Versions

* **Cypress version**: 6.8
* **Preprocessor version**: 4.0.3
* **Node version**: v14.13.1

**Comment by badeball** [comment]
There's not enough information here for me to reproduce the issue. You need to provide me with a minimal example in the form of a cloneable repository.

**Comment by sKavanaghV** [comment]
I'm pretty sure this happens if you have an empty .feature; easy fix :)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
