### ISSUE TITLE
Execution does not finish the whole steps in the feature file

### ISSUE THREAD

**Issue by ezmo14** [badeball/cypress-cucumber-preprocessor#544]
Sometimes, the execution stops with success at random places in middle of the execution of the feature file. Even though if I reran, it will succeed. 

I can not reproduce on demand but I expect consistency and that it runs it fully. What can I provide so I can show how the problem occurs?

### Versions

* cypress 4.10.0
* cypress-cucumber-preprocessor 4.0.1
* Node 14.15.3

**Comment by badeball** [comment]
> What can I provide so I can show how the problem occurs?

I'm not sure. Being able to observe the issue is at least a minimum prerequisite. Otherwise there's really nothing for me to go on here.

**Comment by robsutherland** [comment]
I have this happen to me all the time. It usually seems to be when I make a change to the feature file and it automatically goes to rerun the feature file if I already had cypress up and running. I will see if I can help find a way to help replicate.

**Comment by badeball** [comment]
Does [this](https://github.com/cypress-io/cypress/issues/7432) issue describe what you're experiencing?

**Comment by ezmo14** [comment]
@badeball The issue you mentioned is somehow different, the tick is done as below while there are more steps to execute. 
![image](https://user-images.githubusercontent.com/82312043/114724913-5388b980-9d3c-11eb-8cc5-987ac29c1799.png)

I looked conditions for when it happens, I was able to find the following (for now):

-  For the visit command

```
When('user visits the site', () => {
  cy.visit("/");
});
```
- When transition pages, after a click.
```
cy.get("button#resume").scrollIntoView().should("be.visible").click()
```
```
cy.get("button#continue").should("be.visible").click()
```
In the past, i loaded the locators from a fixture. But then i was afraid that this might be the reason so I removed it.

I run using npx cypress open.

Sometimes the execution stops, and there is a loader. I thought this might be the reason, but sometimes it happens regardless the loader appears or not. If it happens for any other reason not mentioned above, I will update you.

@robsutherland I run a feature file, one or two examples randomly stop with success. Then I do exactly the same, I refresh the browser (chrome) and it works. which is not the ideal solution. And what this happens if it is unattended, this will produce unstable results.

**Comment by safatoujani** [comment]
Hello
I face the same problem and it it happens randomly

**Comment by ezmo14** [comment]
Still facing the same issue @TheBrainFamily

**Comment by ezmo14** [comment]
@TheBrainFamily@xolvio please check

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
