### ISSUE TITLE
custom parameters types causing error when executing .features files

### ISSUE THREAD

**Issue by maga-polito** [badeball/cypress-cucumber-preprocessor#549]
### Current behavior

when defining custom parameter type on common steps like on the example 
const notes = ["A", "B", "C", "D", "E", "F", "G"];

defineParameterType({
  name: "note",
  regexp: new RegExp(notes.join("|")),
});

it works well when executing .feature suites but when trying to execute .features files it will break with the following error:

The following error originated from your test code, not from Cypress.

  > There is already a parameter type with name note

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

node_modules/cucumber-expressions/dist/src/parameter_type_registry.js:55:1

 defineParameterType(parameterType) {
  54 |     if (parameterType.name !== undefined) {
> 55 |       if (this._parameterTypeByName.has(parameterType.name)) if (parameterType.name.length === 0) throw new Error(`The anonymous parameter type has already been defined`);else throw new Error(`There is already a parameter type with name ${parameterType.name}`);
     | ^
  56 | 
  57 |       this._parameterTypeByName.set(parameterType.name, parameterType);
  58 |     }

### Desired behavior

should execute .features files without errors

### Versions

cypress: "7.1.0"
cypress-cucumber-preprocessor: "^4.0.3"
node: v12.18.0

**Comment by Pieras2** [comment]
What is the purpose of parameterType - I look for something that would work as enum in step file showing me available parameter values. I thought this would be the solution but it doesn't work to me.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
