### ISSUE TITLE
Update to latest cucumber major version (@cucumber/cucumber)

### ISSUE THREAD

**Issue by wrslatz** [badeball/cypress-cucumber-preprocessor#554]
### Current behavior

`cypress-cucumber-preprocessor` currently depends on `cucumber` version that is several major versions back
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/e7c08048f32f74d4884bc7f582a9deb9405f5457/package.json#L50

### Desired behavior

`cypress-cucumber-preprocessor` should update to use [`@cucumber/cucumber` `>=7`](https://github.com/cucumber/cucumber-js#7xx-and-above) so that users can take advantage of the latest Cucumber features, fixes, included TypeScript support, etc.

If upgrading would be a large effort, outlining the upgrade process in an issue or wiki could help community contributors take on parts of the work.

### Versions

* **Cypress version**: N/A
* **Preprocessor version**: 4.1.0
* **Node version**: N/A

**Comment by fbaba-nibtravel** [comment]
Will this be addressed any time soon? This upgrade is needed so we can upgrade other larger frameworks such as angular, that now requires webpack 5. In addition, cypress is already on v8.x so this is a lot of versions behind.

**Comment by wrslatz** [comment]
> This upgrade is needed so we can upgrade other larger frameworks such as angular, that now requires webpack 5. In addition, cypress is already on v8.x so this is a lot of versions behind.

This request is to target a `cucumber` version upgrade, not a `cypress` version upgrade. We're currently running this preprocessor with Angular 12, webpack 5, and Cypress 8 with no compatibility issues.

**Comment by fbaba-nibtravel** [comment]
@wrslatz , you are right. Apologies for my hasty comment :) 

My team is currently trying to upgrade to angular 12 and the preprocessor is throwing some exceptions. Are you able to share the pre-processor configuration that is working for you?

**Comment by wrslatz** [comment]
> @wrslatz , you are right. Apologies for my hasty comment :) 

Not a problem ☺️

> My team is currently trying to upgrade to angular 12 and the preprocessor is throwing some exceptions. Are you able to share the pre-processor configuration that is working for you? 

We're using the exact preprocessor configuration recommended in the README of this repo (and we're using Nx to manage our config and execute Cypress with the default generated config)

**Comment by rmalveis** [comment]
Any updates?

**Comment by wrslatz** [comment]
Last update I saw: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/648#issuecomment-986847695

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
