### ISSUE TITLE
Not able to execute .feature files with 7.5.0 version

### ISSUE THREAD

**Issue by senthkum** [badeball/cypress-cucumber-preprocessor#581]
Hi Team,

I am getting an error while executing the feature file, the same was working fine few months back, I have configured all the pre-requisite in the plugins->index.js. But I am getting errors while executing the feature file.
The only change is the cypress version upgraded, currently, I am using 7.5.0. Could you please help me with the issue?

**Previous Execution result:**
![worked-steps](https://user-images.githubusercontent.com/46837197/122029094-f4b0f080-ce0f-11eb-8a01-8884e5d8a021.JPG)

Now it's failing,
![feature-file-not-working](https://user-images.githubusercontent.com/46837197/122029331-22963500-ce10-11eb-88df-f1b8becb3a33.JPG)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
