### ISSUE TITLE
repeat a scenario X times to debug flaky tests

### ISSUE THREAD

**Issue by raphaelbadia** [badeball/cypress-cucumber-preprocessor#583]
### Current behavior

In cypress, there is a very [convenient way](https://www.cypress.io/blog/2020/12/03/retry-rerun-repeat/#repeat) to debug flaky tests  by running the same testmultiple times : you do

```javascript
Cypress._.times(10, () => {
    it('is a flaky test', (n) => {
       ....
     }
})
```

It will run the test 10 times.

### Desired behavior

I would love to have a @repeat(n) that that would run the test `n` times ! This would help identifying and fixing flaky tests.

I don't think I've seen anything that could allow me to code a custom tag either.

Thanks !

**Comment by praveenpandey02** [comment]
Have you tried using cypress-grep plugin? https://github.com/cypress-io/cypress-grep?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
