### ISSUE TITLE
Enhancement: Let multiple but not all feature files use the same step definitions

### ISSUE THREAD

**Issue by rdroog** [badeball/cypress-cucumber-preprocessor#590]
### Current behavior
Currently, when using non global step definitions you basically have two levels of step definitions:
- Per feature file: files in the folder with the same name as the feature file.
- Common: files in the `common`-folder (which can be customized).

### Desired behavior
Next to the above two levels of step definitions, also have a third, in-between level. This level can be used if you are already subdividing your feature files into multiple folders.

In a practical case: if you have an application with groups of features where each group is similar to each other, and you want to have the same step names used for each group but with different implementations, and you want to use multiple feature files within one group, then the current behavior won't suffice. Example setup:

```
/cypress
  /integration
    /common
      - a.ts
      - b.ts
      - ...
    /group1
      /feature-a
        - steps.ts
      /feature-b
        - steps.ts
      - feature-a.feature
      - feature-b.feature
      ...
    /group2
      /feature-a
        - steps.ts
      - feature-a.feature
      ...
```

Where each `feature-a.feature` contains similar tests, as the functionalities between the groups are similar. That results in each `feature-a.feature` using the same step names, but they need different implementations (as they are in different groups). This is possible if you do not have multiple feature files within one group, as for each group you would like to use the same step implementations, but then you would need to place them in `/common`, which would lead them to being used in different groups, which isn't compatible.

To summarize: having a third in-between level between steps per feature file and common steps, use a `shared` level where steps can be defined within the same folder as where the feature-files are (e.g. for `/group1/feature-a` and `/group1-feature-b` this would be `/group1/).

### Test code to reproduce
If necessary I can create a repository to show my implementation. I've tested it with my own setup and it works like a charm.

This issue seems similar as #475 and #231: 
- #475 has the same underlying problem, but they have determined to split up testing the groups over multiple repositories, leaving them without a folder for `common` steps over multiple repositories. We currently prefer having 1 feature file per group instead of not having any `common` steps over multiple groups.
- #231 contains basically the same request, but has a few requests in one issue, so I preferred creating a new one.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
