### ISSUE TITLE
Skip recording for skipped scenarios

### ISSUE THREAD

**Issue by ihsaddamhussain** [badeball/cypress-cucumber-preprocessor#601]
If I am running scenarios with specific tag, All the test scenarios is being recorded in video including the skipped scenarios and each feature file has a video file created even when it is not part of the execution. 
So if I have 10 feature files in which I am only using 4 feature files with a specific tag, then all 10 video files are created here. 6 of them are really unnecessary since it doesn't have any tags.

Is there a way to totally ignore the recording when it is not part of the execution? I only need videos to be created for the tags I specify and not all feature files.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
