### ISSUE TITLE
Unable to run tags on bundled features

### ISSUE THREAD

**Issue by DevDmitriy** [badeball/cypress-cucumber-preprocessor#602]
Hi, when running bundled features (https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#bundled-features-files) - It's seems to be no option to run tags (https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#running-tagged-tests) when we youse bundled feature files

### Versions

* **Cypress version - 8.0.0**:
* **Preprocessor version - 4.0.0**:
* **Node version - 14.17.1**:

**Comment by rkrisztian** [comment]
I think this PR is related: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/607

**Comment by DevDmitriy** [comment]
Thank you for the answer, well this way we can run tests with tags, but we don't bundle features. So that's not solution.

**Comment by andyg101** [comment]
This works for me with the following command 

`npx cypress-tags run --headless --browser=electron --spec **/*.features -e 'TAGS=@mycustomtag'`

**Comment by andyg101** [comment]
> 
> 
> This works for me with the following command
> 
> `npx cypress-tags run --headless --browser=electron --spec **/*.features -e 'TAGS=@mycustomtag'`

Apologies. I was misinterpreting the output. I think you are right that it doesn't work. The --spec argument I don't think is picked up by cypress-tags from a quick skim of the code. cypress-tags seems to use just the values in cypress.json. 

When I run this command
```npx cypress-tags run --headless --browser=electron  -e 'TAGS=@regression'```

I get 'No matching tags found'

**Comment by geabby** [comment]
As a temp solution saw in a comment elsewhere, after updating cypress.json -> `["**/*.{feature,features}"]` it started working.

**Comment by andyg101** [comment]
I have found another workaround for this. In fact you can combine bundled features with tags if you run cypress directly e.g.

`cypress run --headless --browser=electron --spec **/*.features -e 'TAGS=@mycustomtag'`

I notice that the reasoning for cypress-tags given in the documentation is to speed up running of cypress but I haven't yet found a way to get it working without a code change. I suspect it may work if the script was modified to not ignore the --spec parameter

**Comment by andyg101** [comment]
A quick update on this:

I have tried with an edited version of cypress-tags.js which removes the filtering by tags and passes through the spec file arguments. I have run equivalent sets of tests directly and with cypress tags. Some observations

1.  Cypress tags doesn't seem to be any faster than just calling cypress directly. The readme states that calling the cypress executable  directly from node modules should add a speed benefit and this is the purpose of the cypress tags wrapper however I've been unable to conclusively prove this is faster.
2. The filtering in cypress tags replicates filtering that already happens elsewhere in the pre-processor library. Although it isn't stated in the documentation I think this might be where the speed benefit comes from because we are processing less features in the first place.
3. Cypress tags doesn't seem to support feature bundling i.e. features files as it currently stands because the resolution of the features files into individual features happens after cypress tags has kicked off another node process not before.

Some thoughts for progressing this issue:
1. Consider whether cypress tags is necessary at all - one option could be just to remove cypress tags alltogether and call cypress directly. This is largely dependent on whether the assertion in the readme file is true or not. Perhaps I have run this incorrectly somehow as I'm not seeing a speed increase. If anyone can provide any advice on what I might be doing wrong this would be appreciated.
2. If there is no speed increase due to the use of a 'local' cypress executable and in fact the increase is due to pre-filtering of the features - second option would be to modify cypress tags to resolve features files into a list of features and then filter these in the same way as is being done for non bundled features.

For the moment I am going to switch to calling `cypress run` directly as per my previous comment as I am unsure how to proceed without some input on the points I raise above.

**Comment by lgandecki** [comment]
Thanks for the comment @andyg101 
The reason for cypress-tags was that otherwise running cypress run would execute every single .feature file which would take a few seconds each, even if a given file had no tests to run (because of the tags selected).
If now a .feature file takes just a few ms to execute if there are no tests inside, this would not be necessary. It was rather surprising to see how much time was wasted by cypress just by switching between one test file to another.

.features file solve a similar problem - by executing all tests in a one fake test file we skiipped the initialization times. The version by @badeball won't support .features files so I wouldn't build my system around them at this point

**Comment by andyg101** [comment]
No problem @lgandecki . I'm interested in your comment

> If now a .feature file takes just a few ms to execute if there are no tests inside, this would not be necessary. It was rather surprising to see how much time was wasted by cypress just by switching between one test file to another.

Are you saying that is definitely the case or is that a question? Your comment seems to confirm what I thought that the speed benefit was really from reducing the number of features passed to cypress in the first place and therefore if your comment above about skipped features taking a lot less time I *think* that means cypress-tags is no longer relevant. 

I would like to continue using feature bundling though as I think that it minimises the startup / loading time of the browser but maybe this is also irrelevant due to your point above. I haven't noticed any particular speed up in loading cypress tests so interested to understand where this speed improvement might be coming from.

**Comment by andyg101** [comment]
> Using the `cypress-tags` executable together with "bundled features" is non-sensical. 

Fair enough. That doesn't seem clear from the documentation to me and wanting to filter bundled features using tags sounds like a valid use case although it's clear you shouldn't use cypress-tags for this based on your comment.

Can @badeball  confirm whether the long term intention is to remove support for feature bundling? As I said above in my comment I think this does save time because you don't have to constantly re-start the browser but perhaps cypress-tags achieves this anyway. 

side note: It did confuse me for a while that filtering was going on both in cypress tags and then in the pre-processor itself later.

**Comment by andyg101** [comment]
@badeball  - yes I think so. I noticed when running without bundling that there is a 20s or so gap between each feature file which I think is the browser starting and loading the tests (when you run cypress interactively you see this each time you run a test in the popped up browser itself). Feature bundling loads all of the features at once and seems to avoid this (or at least front load it to when you start up the tests).

We have a lot of tests running and therefore running in this way seems to cut a few minutes off our total run time for our tests because we are saving 20 or 30s each time.

**Comment by badeball** [comment]
Okey, I understand your use case now. Can you try to use my fork with esbuild as bundler, as seen [here](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild), to see if that alleviates the issue and removes the need for bundled features?

**Comment by andyg101** [comment]
Thanks @badeball . Is it possible to group the bundles using this method? for example I am currently using features files in different directories to run different suites of tests.

**Comment by badeball** [comment]
You can always invoke Cypress with `--spec` to match files in certain directories, EG. `cypress run --spec 'cypress/integration/my-feature/**/*` (if my memory serves me correctly).

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
