### ISSUE TITLE
cypress cucumber + code coverage

### ISSUE THREAD

**Issue by grethermendezgomez** [badeball/cypress-cucumber-preprocessor#604]
hello I need some guide to install the code coverage, I have done with the steps of the cypress documentation, but it does not work for me. My code is cypress with cucumber, is there something wrong with this? Grateful to help me.
any idea please?

cypress 7.7.0
cucumber
![image](https://user-images.githubusercontent.com/25352699/127182388-8a669ee5-e31a-42af-a133-3556748615c5.png)
I get this and the coverage does not capture me
![image](https://user-images.githubusercontent.com/25352699/127187953-fee86570-2f3b-4bea-abfb-d2a72924e698.png)

@mhodgson @darrinholst @nickdunn @bauglir @fcurella  any idea please?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
