### ISSUE TITLE
Writing multiple scenarios in a feature file

### ISSUE THREAD

**Issue by stemmlerjs** [badeball/cypress-cucumber-preprocessor#606]
### Current behavior

I'm currently unsure about how to write implementations for features that have multiple scenarios. In other tools like [jest-cucumber](https://github.com/bencompton/jest-cucumber), I'm familiar with the ability to scope the implementation to the scenario you're currently on.

### Desired behavior

For example, if my feature was the following:

```gherkin
// ViewAllSpots.feature

Feature:  View all study spots 

  I want to see study spots
  
  Scenario: View all study spots in Toronto by default
    Given I'm on the main page
    And location is disabled
    When the page loads
    Then I should see the map of Toronto with at least one spot displayed

  Scenario: View spots based on my location
    Given I'm on the main page
    And location is enabled
    And I'm in San Francisco
    When the page loads 
    Then I should see the map of San Francisco with at least one spot displayed
```

Then I imagine my implementation would look something like this:

```typescript
/// <reference types="cypress" />

import { 
  Given, Then, When, Scenario
} from "cypress-cucumber-preprocessor/steps";
import { MainPage } from "../../pageObjects/main/mainPage";

let mainPage = new MainPage();

Scenario('View all study spots in Toronto by default', () => {
  Given(`I'm on the main page`, () => {
    mainPage.load();
  })
  
  And('location is disabled', () => {
    browser.disableLocation();
   })
  
  When('the page loads', () => {
    mainPage.waitUntilLoaded();
  })
  
  Then(`I should see the map of Toronto with at least one study spot displayed`, () => {
    let city = mainPage.getCurrentCityOnMap();
    expect(city).to.eq('Toronto');
    
    let spots = mainPage.getCurrentStudySpotsInViewOnMap();
    expect(spots.its.length).to.be.greaterThan(0);
  })
})

Scenario('View spots based on my location', () => {
  ... 
  // scenario implementation with slightly different 
  // behavior, but still cohesive and related to the
  // feature
})

```

I understand there's a tagging feature, but I'm unsure if that could be used to address this problem semantically. Curious about others' thoughts on this.

**Comment by nicoaugereau** [comment]
Hello

You can write your feature like this : 

```
// ViewAllSpots.feature

Feature:  View all study spots 
  I want to see study spots
  
  Background: Before Each
    Given I'm on the main page
    

  Scenario: View all study spots in Toronto by default
    When location is disabled
    And the page loads
    Then I should see the map of Toronto with at least one spot displayed

  Scenario: View spots based on my location
    When location is enabled
    And I'm in San Francisco
    And the page loads 
    Then I should see the map of San Francisco with at least one spot displayed
```

All the Given can be a And or But. Same for When and Then.

```
import { 
  Given, Then, When
} from "cypress-cucumber-preprocessor/steps";
import { MainPage } from "../../pageObjects/main/mainPage";

let mainPage = new MainPage();

Given(/^I'm on the main page$/, () => {
mainPage.load();
})

Given(/^location is (enabled|disabled)$/, (Status) => {
    if (Status == "disabled") {
    browser.disableLocation();
    }else{
    browser.enableLocation()
    }
})

When(/^the page loads$/, () => {
mainPage.waitUntilLoaded();
})

Then(/^I should see the map of Toronto with at least one study spot displayed$/, () => {
let city = mainPage.getCurrentCityOnMap();
expect(city).to.eq('Toronto');

let spots = mainPage.getCurrentStudySpotsInViewOnMap();
expect(spots.its.length).to.be.greaterThan(0);
})
```

**Comment by lgandecki** [comment]
Hello @stemmlerjs , I'm not sure if the Scenario syntax is available in cucumberjs (couldn't find it here https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/api_reference.md ),  but it seems great!

For similar reasons, we've done a similar thing but driven by convention, we called it "nonGlobalStepDefinitions". If you set that to true in your preprocessor configuration then you get a folder for step definitions that's scoped to a related feature file. It's not exactly 1:1 to what you are proposing, because the step definitions will still be reused between different scenarios of the same feature file, but it gets you close.

You can see an example here:
https://github.com/TheBrainFamily/cypress-cucumber-example/tree/master/cypress/integration/socialNetworks

And there is more in our README if you look for nonGlobalStepDefinitions

@nicoaugereau thanks for your help, although I think Khalil was asking about something slightly different so I've decided to send my reply as well. :-)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by Amofe2** [comment]
what if we have a situation where we need to have more than one given statement & each given statement has a diff code implementation, just like this:

// ViewAllSpots.feature

Feature:  View all study spots 

  I want to see study spots
  
  Scenario: View all study spots in Toronto by default
    Given I'm on the main page
    And location is disabled
    When the page loads
    Then I should see the map of Toronto with at least one spot displayed

  Scenario: View spots based on my location
    Given I'm on the admin page
    And location is enabled
    And I'm in San Francisco
    When the page loads 
    Then I should see the map of San Francisco with at least one spot displayed
    
    
    I noticed cypress automatically makes the first given thesame for the rest given, more like it can only run a given statement in a single feature
