### ISSUE TITLE
Error: Step implementation missing for: I open Google page #208

### ISSUE THREAD

**Issue by Sowmya-ankegowda** [badeball/cypress-cucumber-preprocessor#608]
Hello Team

I am trying to work on Cypress Cucumber Frame work but observed error Error: Step implementation missing for: I open Google page #208

**Feature file** 

Feature: Feature name

    Feature Description

    Scenario: Opening a search engine page
    Given I open Google page

**step file**

import { Given } from "cypress-cucumber-preprocessor/steps";

const url = 'https://google.com'
Given('I open Google page', () => {
  cy.visit(url)
})

**Error observed**

![image](https://user-images.githubusercontent.com/86396555/128498498-40d4c791-4ce4-4c20-9816-11ef9add2164.png)

Folder structure

![image](https://user-images.githubusercontent.com/86396555/128498591-e70daf86-6a6a-461d-8689-3e762532627b.png)

Please help me to resolve this issue

**Comment by nicoaugereau** [comment]
Hello,

This works for me. With Cypress 8.2.0
![image](https://user-images.githubusercontent.com/32208373/128531708-0a63d170-dbdf-417f-81ac-5f8a777fead1.png)

My feature file
`
`Feature: Feature name

Scenario: Opening a search engine page
Given I open Google page
`

My Given file in the cypress/support/step_definitions
`// Cypress reference
/// <reference types="cypress" />
// Given
import { Given } from 'cypress-cucumber-preprocessor/steps'

const url = 'https://google.com'
Given('I open Google page', () => {
    cy.visit(url)
})

**Comment by rkrisztian** [comment]
The problem must be that the preprocessor cannot find the step definitions where it expects them to be. Check the configuration options:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration-option

Namely: `nonGlobalStepDefinitions`, `nonGlobalStepBaseDir`, `stepDefinitions`.

**Comment by robert-elles** [comment]
I can get the google example only to work with the settings:

  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/support/step_definitions"
  }

and the step definitions in cypress/support/step_definitions/google.js

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
