### ISSUE TITLE
Cannot "import" cucumber

### ISSUE THREAD

**Issue by pixelass** [badeball/cypress-cucumber-preprocessor#614]
I cannot `import` cucumber. I have to use `require`.
I have other `import` statements in the same file and other files. All of them work as expected.

### Current behavior

**DOES NOT WORK**
```js
import cucumber from "cypress-cucumber-preprocessor";
```
<img width="989" alt="cucumber import" src="https://user-images.githubusercontent.com/1148334/129844532-5414931f-9c39-4802-8cdf-995c75bf1a92.png">

**WORKS**
```js
const cucumber = require("cypress-cucumber-preprocessor").default;
```

**WORKS**
```js
import cucumber from "cypress-cucumber-preprocessor";

const setupPlugins = (on) => {
	// We need to access the default method of cucumber
	on("file:preprocessor", cucumber.default());
};

export default setupPlugins;
```

### Desired behavior

**SHOULD  WORK**
```js
import cucumber from "cypress-cucumber-preprocessor";
```

### Test code to reproduce

```js
import cucumber from "cypress-cucumber-preprocessor";
```

### Potential reason for this error

The main file does not have a "default export". Instead it only has a `module.exports` with a nested default method.

**node_modules/cypress-cucumber-preprocessor/lib/index.js**
```js
/* ... source code*/
module.exports = {
  default: preprocessor,
  transform,
};
```

**should be**
```js
/* ... source code*/
module.exports = {
  default: preprocessor,
  transform,
};
exports.default = preprocessor;
exports.transform = transform;
```

### Versions

* **Cypress version**: `8.3.0`:
* **Preprocessor version**: `4.2.0`:
* **Node version**: `v14.17.1`

**Comment by lliccien** [comment]
Greetings

I have the same problem

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by VRedondo** [comment]
I'm still having the same issue with 
- Node v18.14.0
- Cypress 12.8.1
- badeball/cypress-cucumber-preprocessor 15.1.4

Moving the imports to require fixes the issue as reported previously

**Comment by badeball** [comment]
This has been answered many times alrewady, use the search.
