### ISSUE TITLE
[Feature Request] Extends common steps definition to folder level

### ISSUE THREAD

**Issue by LoganWlv** [badeball/cypress-cucumber-preprocessor#619]
Currently we can have reusable steps this way: 

```
cypress/integration/
      common/ <---- put globally reusable steps here
      moduleA/
          A/ <------ steps
          A.feature
      moduleB/
          B/ <------ steps
          B.feature
```

Wouldn't be nice to extend the common/ feature to sub folders cf: 

```
cypress/integration/
      common/ <---- put globally reusable steps here
      moduleA/
          common/ <---- put moduleA reusable steps here
          A/ <------ steps
          A.feature
      moduleB/
          common/ <---- put moduleB reusable steps here
          B/ <------ steps
          B.feature
```

How difficult would it be to implement that?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
