### ISSUE TITLE
Folder structure issue

### ISSUE THREAD

**Issue by conrad-azzopardi** [badeball/cypress-cucumber-preprocessor#623]
### Versions

* **Cypress version**: 8.4.0
* **Preprocessor version**: 4.2.0
* **Node version**:  12.18.2

Hi all, apologies if this is a stupid question, I'm quite new/noob with cypress, let alone cypress + cucumber.

So I wrote some automation tests in cucumber, and they work fine. I have the feature files in the integration folder, and the step definition folders in the integration folder too. Now I'm trying to have some structure where under integration I have a folder named step_definitions (will show better in screenshot).

![image](https://user-images.githubusercontent.com/67275077/133804107-fa3c2616-f27d-418e-826e-573b60598e28.png)

In package.json I put the following:
`  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepBaseDir": "step_definitions",
    "commonPath": "common",
    "stepDefinitions": "step_definitions"
  }`

When I try to run the tests, I get the below error:
`Error: We've tried to resolve your step definitions at step_definitions, but that doesn't seem to exist. As of version 2.0.0 it's required to set step_definitions in your cypress-cucumber-preprocessor configuration. Look for nonGlobalStepDefinitions and add stepDefinitions right next to it. It should match your cypress configuration has set for integrationFolder. We no longer rely on getting information from that file as it was unreliable and problematic across Linux/MacOS/Windows especially since the config file could have been passed as an argument to cypress.`

Any pointers are appreciated :)

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
