### ISSUE TITLE
cucumberJson doesn't contain all tests when multiple example tables are present in the feature file

### ISSUE THREAD

**Issue by sham-christopher** [badeball/cypress-cucumber-preprocessor#629]
### Current behavior
When there are multiple Example tables in a a Scenario Outline and when only one of the tags is run, the cucumberJson file will only contain the scenarios of the last table. 

### Desired behavior
cucumberJson should contain the tests of the correct tag executed

### Test code to reproduce
Here's an example feature file

---------------------------------------------------
Feature: An example feature file

  @abc
  Scenario Outline: Verify that a customer can do something
    Given that the applicatoin is open
    And the user searches for the <customerNumber>
    When the user does something
    Then the operation has performed

    @test
    Examples:
      | customerNumber |
      | 2193542483     |

    @release
    Examples:
      | customerNumber |
      | 5560121237     |
------------------------------------------------------------

#### Scenario 1: Run the tests for the @test tag
npx cypress run TAGS=@test --spec xyz.feature

##### Actual Result
cucumberJson file is generated with only the skipped scenarios of @release and not the passed or failed tests of @test

#### Scenario 2: Run the tests for the @release tag
npx cypress run TAGS=@release --spec xyz.feature

##### Actual Result
cucumberJson file is generated with only the passed/failed scenarios of @release

In both cases, only the tests of the Example table shown last is present in the json file, be it passed, failed or skipped.

### Versions

* **Cypress version**: 7.7.0, however this has the same behavior with the latest as well
* **Preprocessor version**: 4.3.0
* **Node version**: 14

**Comment by avikashg** [comment]
I also tried. It does execute as expected. Spec results also show it correctly. Issue is with json report. It only contains the entries of last example table of scenario.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
