### ISSUE TITLE
Setup for monorepo

### ISSUE THREAD

**Issue by j-sandeep** [badeball/cypress-cucumber-preprocessor#633]
Is there any way of abstracting common steps definitions into a shared package of a monorepo?

For instance, is the following structure possible?

common package
	↳ common steps

UI package
	↳ feature file
		↳ steps for feature file

### Current behavior
It's possible to make the above structure for the UI project but not possible to implement some steps in the common package and use them in UI project.

### Desired behavior
Would be great if it's possible to be able to define some common steps in a shared package of monorepo.

Also, in future, can I create a copy UI package and continue with a similar structure?

### Versions

* **Cypress version**: 8.5.0
* **Preprocessor version**: 4.3.0
* **Node version**: 16.9.0

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
