### ISSUE TITLE
how to configure steps file to not be in the common folder or use another name

### ISSUE THREAD

**Issue by LayMui** [badeball/cypress-cucumber-preprocessor#641]
I got the following error when run in the cypress IDE
./node_modules/.bin/cypress open
I got this error

Error
Step implementation missing for: she search for the item
../../../../../usr/local/Cellar/node/16.3.0/lib/node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:199:1
https://github.com/LayMui/shopee-automation-with-cypress/tree/cucumber

node v16.3.0
"cypress": "^5.6.0",
 "cypress-cucumber-preprocessor": "^1.19.2"

I have rename the folder from step-definitions to common

how can I change this?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
