### ISSUE TITLE
Fail to run cypress-tags when features dir is not in cypress/integrations

### ISSUE THREAD

**Issue by danielh-codefresh** [badeball/cypress-cucumber-preprocessor#643]
### Current behavior

running the command `cypress-tags run -e TAGS='@final'` 
or `cypress-tags run -e TAGS='@final' -d 'features/final/*.feature'`
fails with the output:
```
Failed to read cypress.json, using default configuration
Spec files:  cypress/integration/**/*.feature
No matching tags found
```

### Desired behavior
scenarios with the tag `@final` should be run

### Test code to reproduce
Feature files are not inside the directory **cypress/integration**, they are in the directory **features** outside the directory **cypress**
**package.json** has the part:
```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "step_definitions/**"
  }
```
**cypress.json** is in the root of the project:
```
{
  "integrationFolder": "features",
  "testFiles": "**/*.{feature,features}",
  "chromeWebSecurity": false,
  "video": true,
  "screenshotsFolder": "dist/screenshots",
  "videosFolder": "dist/videos",
  "videoUploadOnPasses": false,
  "baseUrl": "http://local.xxxxxxxxxxx.xxx",
  "viewportHeight": 1000,
  "viewportWidth": 1280,
  "projectId": "xxxxxxx",
  "ignoreTestFiles": "*.js",
  "trashAssetsBeforeRuns": true,
  "env":
  {
    "FAIL_FAST_PLUGIN": false
  }
}
```
**tsconfig.json**:
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "sourceMap": false,
    "allowSyntheticDefaultImports": true,
    "types": [
      "cypress", "node"
    ],
    "target": "es6",
    "strict": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "**/*.ts"
  ]
}
```
**cypress/plugins/index.js**:
```
/**
 * @type {Cypress.PluginConfig}
 */
const cucumber = require("cypress-cucumber-preprocessor").default;
const browserify = require("@cypress/browserify-preprocessor");
const { downloadFile } = require('cypress-downloadfile/lib/addPlugin')

module.exports = (on, config) => {
  const options = browserify.defaultOptions;

  options.browserifyOptions.plugin.unshift(['tsify'])
  // Or, if you need a custom tsconfig.json for your test files:
  // options.browserifyOptions.plugin.unshift(['tsify', {project: 'path/to/other/tsconfig.json'}]);
  if (process.env.BROWSER_LOG && process.env.BROWSER_LOG === 'yes') {
    require('cypress-log-to-output').install(on)
  }
  on("file:preprocessor", cucumber(options));
  on('task', { downloadFile })

  on('task', { isFileExists })

  createConfig(config)

  require("cypress-fail-fast/plugin")(on, config)
  return config
}
```

### Versions

* **Cypress version**: 8.7.0
* **Preprocessor version**: 4.3.0
* **Node version**: 16.13.0

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
