### ISSUE TITLE
TypeError: (0 , cypress_cucumber_preprocessor_1.default) is not a function

### ISSUE THREAD

**Issue by tharak62** [badeball/cypress-cucumber-preprocessor#647]
Importing cypress_cucumber_preprocessor rather than using require() as below ::
----------------------------------------------------------------------------------------------------------
```
import { default as cucumber } from "cypress-cucumber-preprocessor";
import browserify from "@cypress/browserify-preprocessor";
import resolve from "resolve";

module.exports = (on, config) => {
     const options = {
        ...browserify.defaultOptions,
        typescript: resolve.sync('typescript', { baseDir: config.projectRoot })
     };
     on('file:preprocessor', cucumber(options));

}
```
--------------------------------------------------------------------------------------------------
I'm getting error as TypeError: (0 , cypress_cucumber_preprocessor_1.default) is not a function
![notfunc](https://user-images.githubusercontent.com/93313470/142982669-993ed9ce-a938-44d7-8cc4-92650637f5ab.jpg)

git commit errors for typscript type of any

![eslint](https://user-images.githubusercontent.com/93313470/142982807-3aaadffe-3414-44f7-8ada-ab29fee17c31.jpg)

**Comment by riboher** [comment]
Getting the same error here. Seems a problem related with a TypeScript update but I'm not sure since I've been trying with several combinations with no luck.

Being on the latest yarn version doesn't seem to be the issue either, since I've been using it for a while and it worked without major issues. 

This is my current dependency setup:
```
{
  "cypress": "9.2.0",
  "cypress-cucumber-preprocessor": "4.3.1",
  "typescript": "4.5.3",
  "@yarnpkg/pnpify": "3.1.1-rc.10",
},
"packageManager": "yarn@3.1.1"
```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
