### ISSUE TITLE
How to mimic Cypress "Test-specific-Configuration" using Gherkin

### ISSUE THREAD

**Issue by san-ouadghiri** [badeball/cypress-cucumber-preprocessor#651]
### Cypress feature
See https://docs.cypress.io/guides/references/configuration#Test-specific-Configuration

Using native Cypress, one can state that a test is only valid for a given configuration. For example, that a test should be run when browser is different from chrome only. While testing with chrome, the test will be skipped.

It takes the shape of:
```
describe(name, config, fn)
context(name, config, fn)
it(name, config, fn)
specify(name, config, fn)
```

Such as
```
it('Show warning outside Chrome', { browser: '!chrome' }, () => {
  cy.get('.browser-warning').should(
    'contain',
    'For optimal viewing, use Chrome browser'
  )
})
```
### Desired behaviour

I would like to write a gherkin such as
```
Given we are not in our local environment
When ...
Then ...
```

With `Given ...` being a step that acts as the option `{ target: '!local' }` that Cypress accepts (obviously `target` being a valid variable within my config object, don't worry about that).

Is it possible? If yes how would you write it? If no, could it be considered?
I want to prevent using tags if possible here.

### Workaround
Tagging & calling tests using tags.

### Versions
    "cypress": "7.4.0",
    "cypress-cucumber-preprocessor": "4.0.0",

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
