### ISSUE TITLE
[Feature Request] Add functionality which can execute  cucumber steps from code

### ISSUE THREAD

**Issue by pavlo-kartavkin** [badeball/cypress-cucumber-preprocessor#653]
Hello everyone. It would be very useful to have such feature

And('Step name 1', () => {logic});
And('Step name 2', () => {logic});
And('Step name 3', () => {logic});

And('My big step which uses logic from previous steps', () => {
...
//it would be perfect to have the following function, something like:
cucumber.executeStep('Step name 1');
cucumber.executeStep('Step name 2');
cucumber.executeStep('Step name 3');
.......
});

**Comment by amitguptagwl** [comment]
@pavlo-kartavkin What would be the advantage of doing that. You can probably create 3 functions to achieve it;

```js
And('Step name 1', func1 );
And('Step name 2', func2 );
And('Step name 3', func3 );

And('My big step which uses logic from previous steps', () => {
...
//it would be perfect to have the following function, something like:
func1();
func2();
func3();
.......
});
```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
