### ISSUE TITLE
Cypress Cucumber Preprocessor does not run all features

### ISSUE THREAD

**Issue by bugb** [badeball/cypress-cucumber-preprocessor#656]
### Current behavior
Cypress Cucumber Preprocessor does not run all features

### Desired behavior

It should be run all features

### Log

```
> cypress-cucumber-webpack-example@0.1.0 test
> cypress run --headed --no-exit --spec "**/*.feature"



====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.1.1                                                                          │
  │ Browser:        Electron 94                                                                    │
  │ Node Version:   v14.16.0 (D:\Setup\nodejs\node.exe)                                            │
  │ Specs:          2 found (WebPack.feature, XSS.feature)                                         │
  │ Searched:       **\*.feature                                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  WebPack.feature                                                                 (1 of 2)


  Working with Webpack
    √ it can work with webpack!


  1 passing (9s)
```

### Versions

* **Cypress version**: 9.1.1
* **Preprocessor version**:  1.18.0
* **Node version**: 14.16.0

**Comment by amitguptagwl** [comment]
I hope you have not user `@focus` with Scenario.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
