### ISSUE TITLE
Upgrading - Getting arguments not defined

### ISSUE THREAD

**Issue by fras2560** [badeball/cypress-cucumber-preprocessor#660]
I upgrade to Cypress 9 and upgrade to Webpack in the process. I have not kept up with things so I had to do some things to get the normal tests to run. However, the bundles features I still not get to work.

It says arguments are not defined which I think I narrowed down to this file
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/featuresLoader.js

Am I just missing something in the configuration? Where should the arguments be coming from or this just some type of bug?

### Versions

* **Cypress version**: 9.2.0"
* **Preprocessor version**: 4.3.1"
* **Node version**: v12.19.0
*  **Webpack version**: 5.65.0"

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
