### ISSUE TITLE
use esbuild to handle spec bundle as replacement for browserify or webpack

### ISSUE THREAD

**Issue by nour-dev** [badeball/cypress-cucumber-preprocessor#661]
who do I replace browserify or webpack with esbuild to handle spec code bundles ?
and with support for typescript and so on.

### Current behavior
only support browserify or webpack to handle typescript files

### Desired behavior
use esbuild to handle typescript step definitions files

maybe can be integrated with https://github.com/bahmutov/cypress-esbuild-preprocessor

### Versions
* **Cypress version**: 9.2.0
* **Preprocessor version**: 4.0.1
* **Node version**: 16.13

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
