### ISSUE TITLE
{string} from example table does not work unless using quote: '<myStringFromTable>'

### ISSUE THREAD

**Issue by vince-ee** [badeball/cypress-cucumber-preprocessor#664]
### Current behavior

Scenario:
```
   ...
    Then this <stringFromTable> is displayed
    Examples:
        | stringFromTable | 
          abcdef
```
Code:
```
Then("this {string} is displayed", (myValue) => {
    cy.log('The value is: '+myValue)
})
```
Result:
`Step implementation missing for: this abcdef is displayed`

### Desired behavior

It should find the step and print `The value is abcdef`

It works if adding quote in scenario:

 `Then this '<stringFromTable>' is displayed`

Which is not correct regarding Gherkin syntax.

However there is no issue with {int}:

```
   ...
    Then this <myInt> is displayed
    Examples:
        | stringFromTable | 
          1234
```
Code:
```
Then("this {int} is displayed", (myValue) => {
    cy.log('The value is: '+myValue)
})
```

 `Then this 1234 is displayed`

### Versions

* **Cypress version**: 9.1.0
* **Preprocessor version**: 4.3.0
* **Node version**: Node.js v17.2.0

**Comment by amitguptagwl** [comment]
@vince-ee I believe this is the cucumber expression behavior that the string data should be wrapped in single/double quotes. This is not the framework issue. Check [this](https://github.com/NaturalIntelligence/cytorus/blob/master/docs/12.CucumberParameterTypes.md) for an example

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
