### ISSUE TITLE
Error: Cannot find module 'cypress-cucumber-preprocessor'

### ISSUE THREAD

**Issue by ashuans** [badeball/cypress-cucumber-preprocessor#675]
I am currently running Cypress / cucumber tests as a part of our Jenkins build pipeline. This only happens on Jenkins, I am able to run the tests locally.

I am getting below error in Jenkins :-

### Current behavior

11:03:18  Your pluginsFile is invalid: /home/jenkins/workspace/project-path/cypress/plugins/index.js
11:03:18  It threw an error when required, check the stack trace below:
11:03:18  Error: Cannot find module 'cypress-cucumber-preprocessor'
11:03:18  Require stack:
11:03:18  - /home/jenkins/workspace/project-path/cypress/plugins/index.js
11:03:18  - /home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
11:03:18  - /home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js
11:03:18      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
11:03:18      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
11:03:18      at Module.require (internal/modules/cjs/loader.js:974:19)
11:03:18      at require (internal/modules/cjs/helpers.js:101:18)
11:03:18      at Object.<anonymous> (/home/jenkins/workspace/project-path/cypress/plugins/index.js:5:18)
11:03:18      at Module._compile (internal/modules/cjs/loader.js:1085:14)
11:03:18      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
11:03:18      at Module.load (internal/modules/cjs/loader.js:950:32)
11:03:18      at Function.Module._load (internal/modules/cjs/loader.js:790:12)
11:03:18      at Module.require (internal/modules/cjs/loader.js:974:19)
11:03:18      at require (internal/modules/cjs/helpers.js:101:18)
11:03:18      at runPlugins (/home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:186:15)
11:03:18      at Object.<anonymous> (/home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
11:03:18      at Module._compile (internal/modules/cjs/loader.js:1085:14)
11:03:18      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
11:03:18      at Module.load (internal/modules/cjs/loader.js:950:32)
11:03:18  error Command failed with exit code 1.

### Desired behavior

It should run in Jenkins pipeline

**Comment by gurchik** [comment]
This usually happens if you don't have it installed. Maybe you ran a command like `npm install cypress-cucumber-preprocessor` on your local, but you don't do the same in your Jenkins pipeline?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
