### ISSUE TITLE
I'm also getting this error message on windows

### ISSUE THREAD

**Issue by ugyenlekzin** [badeball/cypress-cucumber-preprocessor#677]
I'm also getting this error message on windows
The following error originated from your test code, not from Cypress.

  > Cannot read property 'signals' of undefined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

my nonGlobalStepDefinitions is set to True

"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": true
}

Please can anyone help.
![2021-07-13 17_03_33-QA-CSFEAUTOMATION](https://user-images.githubusercontent.com/46799533/125486154-b689295d-4fed-4704-a5af-090b19fb2a9e.png)

_Originally posted by @abonje2000 in https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/555#issuecomment-879211571_

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
