### ISSUE TITLE
Duplicate step definitions should not be allowed

### ISSUE THREAD

**Issue by andyg101** [badeball/cypress-cucumber-preprocessor#678]
### Current behavior

Currently the pre-processor allows duplicate step definition implementation to be present and just silently picks the first step definition it finds. This is counter to my understanding of good practice with BDD frameworks where a single step definition should have a single implementation so that the natural language gherkin phrases have a consistent and deterministic behaviour.

Note I'm just considering the general case here. I'm not saying that if you have a custom step definition for a specific feature file in a matching folder it couldn't match an existing common step (although I would argue that is probably bad practice from a BDD perspecive).

### Desired behavior

I think the framework should reject / refuse to process a set of feature files if it cannot resolve step definitions down to a single implementation.

### Test code to reproduce
Feature file:

```Gherkin
Feature: A feature with a duplicate step definition

This demonstrates the sisue with duplicate step definition implementations 
which are not currently detected by the pre-processor.

  Scenario: Duplicate step definition implementations should fail
     Given a step definition with a duplicate implementation
```

Implementation:

```Javascript
const { Given } = require("cypress-cucumber-preprocessor/steps")

Given(/^a step definition with a duplicate implementation$/, function () {
  cy.log("This step will get executed becacuse it appears first")
}); 


Given(/^a step definition with a duplicate implementation$/, function () {
  cy.log("This step will note get executed becacuse it appears second")
}); 
```

### Versions

* **Cypress version**: 8.3.1
* **Preprocessor version**: 4.3.1
* **Node version**: 14.17.3

**Comment by lgandecki** [comment]
Hello

Could you please check how pure cucumberjs solves this problem? We would like to match cucumber behavior as much as possible

**Comment by badeball** [comment]
It's [not allowed](https://github.com/cucumber/cucumber-js/blob/39e2c7f62aff051f04dfb131749ab78aa0be228c/features/ambiguous_step.feature) in cucumber-js (I've replicated that behavior in my [fork](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/features/unambiguous_step_definitions.feature)).

**Comment by andyg101** [comment]
Thanks for confirming that for me @badeball . I've opened  a PR with a proposed fix for this. Please let me know if you think it is suitable or needs additional work.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by JomyGeo** [comment]
@badeball  I am facing Multiple-step definitions found error when we have same step definition description in two different feature files.

For example,

I have two different feature files like login.feature, forgetPassword.feature. I have a common step **Given(''Open the browser and load the URL'')**,  in both feature files. 

How to handle this scenario? i believe this error will display only when we have duplicate steps in same feature file, not for two different feature files. Please provide your thoughts on this

#Cypress 10.2

**Comment by badeball** [comment]
@JomyGeo, you're making it impossible for me to help you. You have to show me an example that I can correct (and don't make it difficult by doing that with screenshots or large bodies of code, give me a cloneable repository that illustrates your folder structure).

**Comment by JomyGeo** [comment]
@badeball  
I have created a sample project which illustrates the folder structure of my project.
[Please Use this repo ](https://github.com/JomyGeo/SampleQA_SauceDemo.git)

**Comment by JomyGeorge33** [comment]
@badeball Please look into the above repo.

**Comment by JomyGeo** [comment]
@badeball Could you please check the above repo and provide us an update for the same

**Comment by badeball** [comment]
@JomyGeo https://github.com/badeball/cypress-cucumber-preprocessor/issues/750#issuecomment-1171516078

**Comment by JomyGeo** [comment]
@badeball  Do we have an option to pass stepDefinition file path on runtime (Terminal) as we pass it for Spec path(.Feature file)?

Because when I set the Stepdefiition as a global pattern in package.json then Before() Hook runs every time which is not related to that spec file. [#750](https://github.com/badeball/cypress-cucumber-preprocessor/issues/750)

Current behaviour :
I have to pass the exact step definition path in package.json to overcome this issue

Expected behaviour : 
Passing step definition path in run time (Terminal). So that it will be executed the hook within the Specified step definition path

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md#configuration-overrides

**Comment by JomyGeo** [comment]
@badeball  I couldn't override the Environment variables in command line. Correct me , if i am wrong

Example : cypress run -e tags='@Demo',filterSpecs=true --browser='electron'

![image](https://user-images.githubusercontent.com/89033776/177990352-05664d6f-700c-4cc5-87e9-68a46d844b97.png)

**Comment by badeball** [comment]
Looks right, but again it's difficult to tell because you're giving me an example of what you're doing and not exactly what you're doing.

**Comment by JomyGeo** [comment]
@badeball  Please check the below [Repo]( https://github.com/JomyGeo/SampleQA_SauceDemo)

run command :cypress run -e tags='@Login',filterSpecs=true --browser='electron'

**Comment by badeball** [comment]
The command _does_ set the environment variables `tags=@Login` and `filterSpecs=true`.

**Comment by JomyGeo** [comment]
@badeball  It didn't work for me. All i want here is to override the stepDefinitions and filterSpecs environment variable values in runtime. But it is not working for me.  Cypress script executing based on the value in cypress.config.js , not run time. 

cypress run -e stepDefinitions='cypress/e2e/StepDefinitions/Product_Steps/**/*.js' --browser='electron'
cypress run command :cypress run -e tags='@Login',filterSpecs=true --browser='electron'

**Comment by badeball** [comment]
Well, what have to tried so far? I only see two commands which sets each separately, how have you tried to set them simultaneously?

**Comment by JomyGeo** [comment]
@badeball I run the below commands seperately , Not at same time  

cypress run -e stepDefinitions='cypress/e2e/StepDefinitions/Product_Steps/**/*.js' --browser='electron'
cypress run command :cypress run -e tags='@Login',filterSpecs=true --browser='electron'

**Comment by badeball** [comment]
Then I don’t understand what’s the issue here.

**Comment by JomyGeo** [comment]
The problem here is that I could not override the value in runtime. In some cases, I want to change the stepDefinition folder value im runtime. The below code didn't work for me. Please guide to sort out this problem

cypress run -e stepDefinitions='cypress/e2e/StepDefinitions/Product_Steps/**/*.js' --browser='electron'

**Comment by badeball** [comment]
Saying "it didn't work" simply doesn't help me and I give up now. This wasn't a support forum to begin with and you've turned out to be too difficult to deal with. I recommend that you try SO.

**Comment by JomyGeo** [comment]
Hi,

 Can we have a call regarding this? So that i can explain you in detail
about the issue which i am facing now
