### ISSUE TITLE
vue-cli 3 and cypress

### ISSUE THREAD

**Issue by dvelasquez** [badeball/cypress-cucumber-preprocessor#68]
Hello, im using vue-cli v3 with the cypress plugin and when i start a feature test i got the following error:
```
Uncaught TypeError: Cannot read property 'prototype' of undefined

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.

 at patch (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/Generic.feature-741:51105:54)
    at Object.<anonymous> (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/Generic.feature-741:50966:18)
    at Object.273../fs.js (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/Generic.feature-741:51203:4)
    at o (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/Generic.feature-741:1:265)
    at http://localhost:8080/__cypress/tests?p=tests/e2e/specs/Generic.feature-741:1:316
```

This is the plugin configuration from cypress and vue-cli, is not the usual config:

```js
// https://docs.cypress.io/guides/guides/plugins-guide.html
const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
  return Object.assign({}, config, {
    fixturesFolder: 'tests/e2e/fixtures',
    integrationFolder: 'tests/e2e/specs',
    screenshotsFolder: 'tests/e2e/screenshots',
    videosFolder: 'tests/e2e/videos',
    supportFile: 'tests/e2e/support/index.js',
    step_definitions: 'tests/e2e/support/step_definitions/',
  })
};
```
I'm not sure if someone has stumbled with this issue or has an idea of how to implement it in the right way.

**Comment by dvelasquez** [comment]
So, this problem was caused because the "step_definitions" was in package.json and in the vue-cli configuration provided by the plugin.

To make this work, i have to delete the entry in package.json, add the preprocessor line and the step_definitions in the object returned.

I'll open a PR adding this to the docs.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
