### ISSUE TITLE
Tag @focus is disabled when the tag @ignore is enabled

### ISSUE THREAD

**Issue by asf89** [badeball/cypress-cucumber-preprocessor#680]
I did the configuration from the section "[Ignoring specific scenarios using tags when executing test runner](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#:~:text=the%20example%20repo.-,Ignoring%20specific%20scenarios%20using%20tags%20when%20executing%20test%20runner,-You%20can%20also)" and enabled the use of the tag `@ignore`. However, by doing this, I can't use the tag `@focus` anymore. There is a way to enable the tag again without removing the `@ignore` configuration?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
