### ISSUE TITLE
Failure with exception when using cypress-allure-plugin

### ISSUE THREAD

**Issue by pwpatton** [badeball/cypress-cucumber-preprocessor#714]
I'm working on an example repo using [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) and [cypress-allure-plugin](https://github.com/Shelex/cypress-allure-plugin)

When attempting to use [cypress-allure-plugin](https://github.com/Shelex/cypress-allure-plugin) with  [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) the first test appears to hangs at the end due to an exception thrown in the cypress-cucumber-preprocessor.

To duplicate
- clone [badeball-cypress-cucumber-allure-issue](https://github.com/pwpatton/badeball-cypress-cucumber-allure-issue)
- npm install
- npm run cy:open
- open the developer tools window and see stacktrace

```
Uncaught TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of undefined (reading 'keyword')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at CucumberHandler.checkLinksInExamplesTable (https://duckduckgo.com/__cypress/tests?p=cypress\support\index.ts:1862:43)
    at Runner.eval (https://duckduckgo.com/__cypress/tests?p=cypress\support\index.ts:2878:39)
From previous event:
    at onNext (https://duckduckgo.com/__cypress/runner/cypress_runner.js:185685:19)
    at done (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129431:5)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:129496:11
From previous event:
    at callFn (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129494:14)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129478:7)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:185755:30
From previous event:
    at Object.onRunnableRun (https://duckduckgo.com/__cypress/runner/cypress_runner.js:185740:19)
    at $Cypress.action (https://duckduckgo.com/__cypress/runner/cypress_runner.js:174847:28)
    at Test.Runnable.run (https://duckduckgo.com/__cypress/runner/cypress_runner.js:183404:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://duckduckgo.com/__cypress/runner/cypress_runner.js:130150:10)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:130276:12
    at next (https://duckduckgo.com/__cypress/runner/cypress_runner.js:130059:14)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:130069:7
    at next (https://duckduckgo.com/__cypress/runner/cypress_runner.js:129971:14)
    at https://duckduckgo.com/__cypress/runner/cypress_runner.js:130037:5
    at timeslice (https://duckduckgo.com/__cypress/runner/cypress_runner.js:123963:27)
```

### Test code to reproduce
[badeball-cypress-cucumber-allure-issue](https://github.com/pwpatton/badeball-cypress-cucumber-allure-issue)

See README.md showing how I installed the `cypress-allure-plugin`
https://github.com/pwpatton/badeball-cypress-cucumber-allure-example#add-reporting-using-cypress-allure-plugin

### Versions

* **Cypress version**: 9.6.1
* **Preprocessor version**: 9.2.1
* **Node version**: v14.17.3

**Comment by badeball** [comment]
So this isn't due to a bug in the preprocessor, but rather in [cypress-allure-plugin](https://github.com/Shelex/cypress-allure-plugin). It makes some assumptions about global variables, which changed during the great rewrite (TM) (https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The allure plugin should instead retrieve this information through some interface, which can be documented, maintained and tested. I'm happy to cooperate with the maintainers of the allure plugin on this, but they will have to reach out. I think for example that the preprocessor could be an optional peer dependency of the allure plugin and export a method a `getGherkinDocument()` and / or `getPickle()`.

Furthermore, as the maintainers of the allure plugin has discovered, there can be only one listener to events such as `after:spec`. Both the allure plugin and this preprocessor needs to listen to this event.

As explained by Chris (https://github.com/cypress-io/cypress/issues/6648#issuecomment-596542094), to blatantly attach listeners might be considered bad behavior from a plugin and we should expose a method which you can call yourself instead (when needed).

I've [recently](https://github.com/badeball/cypress-cucumber-preprocessor/issues/705#issuecomment-1126357407) made a change to let the consumer take more control over this (15ae6d0ae3b30fe3034804a2826ba5411a5de102) and the allure plugin should do something similar rather than (or as a complement) implement a [heuristic](https://github.com/Shelex/cypress-allure-plugin/blob/master/writer/checkPluginsFile.js).

**Comment by badeball** [comment]
@pwpatton, I think you should open an issue on their issue tracker and link to this.
