### ISSUE TITLE
Could not get JSON report output

### ISSUE THREAD

**Issue by burakkaygusuz** [badeball/cypress-cucumber-preprocessor#737]
### Current behavior

An error occurred when the JSON report is enabled:

    An error was thrown in your plugins file while executing the handler for the after:run event.

    The error we received was:

    Error: spawn cucumber-json-formatter ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Desired behavior

According to this doc, a JSON report should be enabled: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md

### Test code to reproduce

> package.json

```json
    {
      "cypress-cucumber-preprocessor": {
        "json": {
          "enabled": true
        },
        "stepDefinitions": "cypress/support/step_definitions/**/*.{js,ts}"
      }
    }
```
> cypress.config.js

```js
const { defineConfig } = require('cypress');
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const { createEsbuildPlugin } = require('@badeball/cypress-cucumber-preprocessor/esbuild');
const { addCucumberPreprocessorPlugin } = require('@badeball/cypress-cucumber-preprocessor');

module.exports = defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });
      on('file:preprocessor', bundler);

      await addCucumberPreprocessorPlugin(on, config);
      return config;
    },
  },
});
```

### Versions

* **Cypress version**: 10.1.0
* **Preprocessor version**: 11.0.0
* **Cucumber version**: 8.3.0
* **Node version**: 16.5.1

**Comment by badeball** [comment]
Have you installed cucumber-json-formatter per docs?

**Comment by burakkaygusuz** [comment]
> Have you installed cucumber-json-formatter per docs?

No, I didn't. Could you please direct me?

**Comment by thllbrg** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md

**Comment by adamsjr8576** [comment]
@badeball Thank you so much for taking over this project and updating to work with Cypress v10! I am currently in the progress of migrating our repo over to Cypress v10/cypress-cucumber-preprocessor v11. I have everything working except for the JSON report output. I feel like it is probably user error which is why I did not open a new issue but rather decided to chain unto this closed one - hope that's fine.
I have followed the steps laid out in https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md:
- Download cucumber-json-formatter
- Renamed it and moved to root folder
- Set to PATH on My Mac - `sudo cp cucumber-json-formatter /usr/local/bin`
- Ran `sudo chmod +x /usr/local/bin/cucumber-json-formatter`
- Tested it in terminal
```
cucumber-json-formatter --help
Usage of cucumber-json-formatter:
```
- My `cypress.config.js` file is configured correctly to run `cypress-cucumber-preprocessor`
- I have `cypress-cucumber-preprocessor` set-up like so:
![Screen Shot 2022-06-29 at 2 20 31 PM](https://user-images.githubusercontent.com/49846853/176508358-2319f542-cbe7-4d1f-b119-e3462abccee7.png)
I am attempting to recreate the same functionality that was working in the deprecated repo via: 
```
    "cucumberJson": {
      "generate": true,
      "outputFolder": "test-results/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ""
    }
```
When running tests I am not receiving any errors or anything that would indicate it is not working, though at the end of the test run no json report file is generated in the specified output folder.

Any thoughts on what I might be doing wrong or suggestions for things I could try in order to better isolate the issue or figure out why this is not working?? Any help would be very very much appreciated - thank you!!

**Comment by deepakshrma** [comment]
I have create a wrapper due to same issue. You can give a try. @[adamsjr8576](https://github.com/adamsjr8576)


https://www.npmjs.com/package/@deepakvishwakarma/cucumber-json-formatter

**Comment by badeball** [comment]
@adamsjr8576, post the complete output, please. Also, are there _any_ new files created?

**Comment by adamsjr8576** [comment]
Of course! Here is the complete output when running the test:
![Screen Shot 2022-06-29 at 3 12 35 PM](https://user-images.githubusercontent.com/49846853/176517791-0faf2f6d-d621-4ecb-86e4-dd804cbdd818.png)
Please let me know if you need anything else or meant something else for output.

There are no new files created at all. Thank you for taking a look!

**Comment by badeball** [comment]
No idea what's wrong given the provided info. You're going to have to give me an example that I can take a look at.

**Comment by adamsjr8576** [comment]
Will do - I'll see if I can reproduce in a test repo and share with you if so. Thanks for taking a look! I feel like the issue might be with how I downloaded and added cucumber-json-formatter to my PATH. Though the fact that there is no output at all makes it hard to tell what's going on.

**Comment by kiran-epic** [comment]
@adamsjr8576 Were you able to find the root cause as to why no files were getting generated ? I am facing the same issue currently..

**Comment by Amine2004** [comment]
Hello, @adamsjr8576 I'am facing also the same issue currently.. Any update ?
Thanks

**Comment by Mathiarasan3** [comment]
I am facing the same issue.
This is how my project structure looks like
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/82944178/63631e82-37bb-4e5f-9296-49c4ea53a7a1)


and this is my package.json,
{
  "name": "cypressautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx cypress run",
    "test_headed": "npm run test -- --headed",
    "test_record": "npm run test -- --record --key 4cd089db-56dc-47ec-94e1-b805784fb482 --spec cypress\\integration\\examples\\test4.js --headed --browser chrome",
    "test_single": "npm run test -- --spec cypress\\integration\\examples\\test4.js"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions":false,
    "stepDefinitions":"cypress/integration/examples/BDD/ecommerce/*.js",
    "json": {
      "enabled": true,
      "output": "cypress/cucumberReports/results.json",
      "formatter":"cucumber-json-formatter"
    },
    
      "messages": {
        "enabled": true,
        "output":"cucumber-messages.ndjson"
      }
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cypress/browserify-preprocessor": "^3.0.2",
    "cypress": "^12.14.0",
    "cypress-iframe": "^1.0.1",
    "multiple-cucumber-html-reporter": "^3.4.0"
  },
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^18.0.1",
    "@cypress/browserify-preprocessor": "^3.0.2"
  }
}
 And when I run json formatter from terminal, i get this proper output,
 C:\Users\MATHI\CypressAutomation>cucumber-json-formatter --help
Usage of cucumber-json-formatter:




But after running the feature file, I dont see any cucumber messages and also I dont see any json report generated.

Please help here.
