### ISSUE TITLE
Possible of generate empty tests with a "Pending" warning?

### ISSUE THREAD

**Issue by victorheid** [badeball/cypress-cucumber-preprocessor#75]
I have to leave all tests empty, which gives a false status of passing and fails on guiding the development process.  

Is there any way to do it? Or am I missing it? #

**Comment by lgandecki** [comment]
I think this is more of a cypress / mocha thing - what happens if you put this.skip() inside your step definition?

**Comment by victorheid** [comment]
It just skips it, and the test itself marks as passing (if only skipped steps are left)

I've tried to throw an error saying "Step pending" or just not write the step until I get to it, but both cases, it seems to override the entire test ,Cypress doesn't show the other steps that were executed before. i.e. I have a step that is pending, where I just do an 'assert.isTrue(false)'. The error emerges, but it does not show the previous steps

**Comment by lgandecki** [comment]
I see what you are saying and I would love to have that as well, but at this moment I don't see a way to achieve that, as Cypress forces us to treat all steps as one test. you can try to introduce a warning instead of the this.skip but that will be easy to miss for example in the CI (which is the point of pending tests as far as I understand). 
I think we would need some changes in the cypress runner here, possibly around the way they deal with loging. 
This is something I was hoping to look at in November.

**Comment by flowt-au** [comment]
OK. All good. Just as long as it is on the radar! 

Thanks,
Murray

**Comment by miteshpatel1** [comment]
Hello - any updates on the development of this feature?

**Comment by servandoprime** [comment]
This feature would be awesome... right now, not being able to set a scenario as "pending" with cucumber is what's hindering me from using cypress...

**Comment by PascalBe07** [comment]
Any update here?

My use case is the following:
I want to mark tests, which are not implemented yet, so that they do not break the CI build. 
The idea was to give a custom tag and then, in the before hook, skip the whole scenario.

Is there a way to do that? I came up with an approach like that, but I can not seem to get it running:
`
Before({ tags: '@manual' }, function() {
  console.log('In before hook');
  this.skip();
  //   return 'skipped';
});
`
Is there a way to achieve that right now?

**Comment by rfftrifork** [comment]
Any news on this?

**Comment by ncko** [comment]
Any update on this?

**Comment by AlphaWong** [comment]
It is a good feature to have. As right now, the result table of the test show pending

**Comment by gtsop** [comment]
Anyone here found a way to achieve the desired behaviour?

**Comment by andyg101** [comment]
I have used cucumber with Java and to acheive this you throw a PendingException() is there a similar concept that can be used here?

**Comment by flowt-au** [comment]
FYI This is helpful: [https://github.com/cypress-io/cypress-skip-test](https://github.com/cypress-io/cypress-skip-test)
`
Then('Skip this test', () => {
    cy.skipOn(true)
});
`

**Comment by mkefd** [comment]
hi! when using `this.skip()` I get `empty.cucumber.json` generated instead of some meaningful data, does anyone experiences the same?

versions
```
"cypress": "^9.0.0",
"cypress-cucumber-preprocessor": "^4.3.0",
```

config
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }
```

**Comment by Finaldrace** [comment]
> While this doesn't address the bigger issue, this is helpful: https://github.com/cypress-io/cypress-skip-test eg: `Then('Skip this test', () => { cy.skipOn(true) });`

Yeah i use the skip-test plugin too.
And in CLI the testcases with the cy.skipOn("true") are marked as pending.

![image](https://user-images.githubusercontent.com/22379578/153104488-e254635b-f3c3-4ba4-8758-66e04c647450.png)
As you can see 5 are pending.

but in my json file is every expected `"status": "pending" `testcase missing.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
