### ISSUE TITLE
making one test in scenario outline an option

### ISSUE THREAD

**Issue by ronlawrence3** [badeball/cypress-cucumber-preprocessor#76]
I am struggling with cypress' insistence on tearing the world down between tests. With protractor, we did not need to do this. Not your issue, but...

Scenario outlines are especially painful as invoking "background" ( log in and navigate to where I need to be) on each example becomes very long running. I'd like to see an option where the scenario outlines could be "rendered" as one test rather than "n" tests.

**Comment by lgandecki** [comment]
I hear ya!

But, I think, the Cypress guys are suggesting that if you have one test that covers the whole "happy path", including login in, navigating, etc, then if you need to do multiple tests on a given page, then just go there directly being in a logged in state - there is no need to verify over and over whether the application can log you in. It might not be as "safe" in terms of safety net, but it will be close, while MUCH faster and reliable (the tests failures will point you to the problem, one thing breaking won't brek tens of tests, etc)

**Comment by ronlawrence3** [comment]
Unfortunately not an easy thing to do for our app, which uses localstorage to store authentication details, which gets wiped. I will try saving / restoring local storage (or at least these keys) for now to see if I can speed up these tests, but it would sure be a nice feature to pick and choose when to do this sort of thing.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
