### ISSUE TITLE
Is there a Default Step definition project?

### ISSUE THREAD

**Issue by amenk** [badeball/cypress-cucumber-preprocessor#83]
Are there any default step definitions out there for example, to open a page, click a button, type text and so on? 

If not, would it make sense to share such?

**Comment by amenk** [comment]
So essentially I am looking for a port of https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/Context/MinkContext.php to cypress-cucumber

Did anybody do this yet?

**Comment by amenk** [comment]
I am trying to do this .. what would be the best way to distribute a mink.js with a port from Mink's step definitions? Should it be put to this project (fork, pull request) or a separate NPM package?

**Comment by lgandecki** [comment]
Hard to say.. Could you create a separate package/repo first, and then we will think whether it makes more sense to merge it in here or link to it in the README? 

Thanks!

**Comment by amenk** [comment]
Coming here: https://github.com/iMi-digital/mink-cypress

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
