### ISSUE TITLE
And and But keywords seem unsupported

### ISSUE THREAD

**Issue by madbreena** [badeball/cypress-cucumber-preprocessor#859]
### Current behavior

After the migration from TheBrainFamily, we cannot use 'And' or 'But' keywords as they are not exposed in badeball/cypress-cucumber-preprocessor.

When trying to import And/But in the stepDefinition file, we get the following error
![Screenshot_21](https://user-images.githubusercontent.com/23477928/195572555-fd394b8b-c3a7-43d4-8be6-36357fc58d74.png)

### Desired behavior

I create a feature file with scenarios including with And or But keywords
I create the respective stepDefs
I expect the And or But keywords to be successfully imported with "import { Given, When, And } from '@badeball/cypress-cucumber-preprocessor';"

### Test code to reproduce

test.feature 

Feature: Test#1

Scenario: Test Scenario #1
    Given that I am landed to page foo
    When I click on register button
    And I input my email
   ...

test.ts (stepDefinition)

import { Given, When, And } from '@badeball/cypress-cucumber-preprocessor';

...

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**: 13.0.2
* **Node version**: 16.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by malt-man** [comment]
Facing the same problem when also trying to migrate to version `13.0.2`.
Would be great if this could please be addressed.

**Comment by NuruDashdamir** [comment]
You can still use "And" and "But" keywords in your feature file.
But you need to define those steps with "When" keyword in your JS/TS file.

The reason is shown here:
https://github.com/badeball/cypress-cucumber-preprocessor/issues/821

You will need to swap "And()" and "But()" calls to "Given()" calls

**Comment by NuruDashdamir** [comment]
You can still use "And" and "But" keywords in your feature file.
But you need to define those steps with  `Given()`, `Then()`, `When()` calls in your JS/TS file.

The reason is shown here: https://github.com/badeball/cypress-cucumber-preprocessor/issues/821

You will need to swap `And()` / `But()` calls to `Given()`, `Then()`, `When()` calls

**Comment by badeball** [comment]
> The reason is shown here: https://github.com/badeball/cypress-cucumber-preprocessor/issues/821

This is correct. I've updated the upgrade guide to reflect this.
