### ISSUE TITLE
All Features are skipped when using "TAGS='not @ignore'" though only one is Tagged

### ISSUE THREAD

**Issue by bartonhammond** [badeball/cypress-cucumber-preprocessor#980]
### Current behavior
All the Features are skipped even though only one was marked w/ "@ignore" tag

One Feature is marked with @ignore 

If I run with the following, only the feature tagged is run as expected.
```
node_modules\\.bin\\cypress run --env TAGS='@ignore',ENV=mv --browser edge --headed",
```
But if I run with "not @ignore" none of the Features run.
```
node_modules\\.bin\\cypress run --env TAGS='not @ignore',ENV=mv --browser edge --headed",
```

The feature here is tagged to be ignored.
```
@ignore
Feature: EFiling HP
    Scenario: File a new case
        #Precodition
        Given user must have an efiling account - logged in and on the efiling menu
```
This Feature has no Tags at all
```
Feature: Officer Setup
    Scenario: User needs to set up an officer and assign them to a specific group.
        #Test steps
        Given Click on Admin
```
![image](https://user-images.githubusercontent.com/1282364/228959589-3217afd5-5ce3-423e-9c6f-2a03b280037d.png)

### Desired behavior

All Features not Tagged with '@ignore' should run

### Test code to reproduce

I can't share my code as I work for the State Gov 

### Versions

* **Cypress version**:  "cypress": "^12.9.0",
* **Preprocessor version**: "^16.0.0"
* **Node version**: v19.7.0

### Checklist

- [ Y] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ Y] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ Y] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> I can't share my code as I work for the State Gov

This just isn't an acceptable answer and I will try to explain why.

In [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md) I state that I need a way to reproduce the issue. I can't just blindly attempt to fix something based on a hunch, right? I have to be able to see the issue, write a fix and verify that the issue does in fact cease to exist. I hope this doesn't require further explanation.

Furthermore, I'm not actually asking for your company secrets here. In all actuality, I don't want to see your production code at all, it doesn't interest me.

What I want from you, is that you reduce your problem into something so minimal that it barely illustrates the issue at hand and nothing more. A minimal example that reproduces the issue should ideally be the foundation for a test. It's something that should be comitted into [features/issues](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/features/issues) to ensure that it never resurfaces again.

Another and perhaps more important reason for why I want you to go through the exercise of reducing the problem, is to ensure that the real problem is actually what you describe it to be. You might be surprised how often I find this not to be the case. Simply put, I need you to do the leg work before I acknowledge that there even is an issue, otherwise I would too often be wasting my own time.

**Comment by badeball** [comment]
I recommend that you use one of the [exampes](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples) as a starting point, modify it and use that to show me what you think is wrong.

**Comment by bartonhammond** [comment]
@badeball I will take an example to reproduce as you recommend.

**Comment by bartonhammond** [comment]
Reproducing example: https://github.com/bartonhammond/-cypress-cucumber-preprocessor-issue-980

`npm run runFeatures` => `node_modules\\.bin\\cypress run --headed`
Runs as expected:
![image](https://user-images.githubusercontent.com/1282364/229140774-74581637-37f4-4c6e-9505-b28b9529b843.png)

`npm run runIgnoreOnly` => `node_modules\\.bin\\cypress run --env tags=@ignore --headed`,
Runs as expected:
![image](https://user-images.githubusercontent.com/1282364/229141065-b8b3a796-f680-4bbb-af8c-cd6cb401356e.png)

`npm run runFeaturesNotIgnore` => `node_modules\\.bin\\cypress run --env tags='not @ignore' --headed`
Does not run as expected:
![image](https://user-images.githubusercontent.com/1282364/229141332-faac3cb9-f226-4105-9f49-8c8046f1530c.png)

**Comment by badeball** [comment]
Your example runs seemingly fine here and I do not get the results you are depicting. I'm guessing your shell is doing something surprising, but it's something you're going to have to figure out. I recommend running `cypress open --env tags='not @ignore'`, go to settings and see what environment variables Cypress has actually resolved.

**Comment by bartonhammond** [comment]
@badeball Thanks for the insight of looking at the Settings.  
Turns out I had to do escape the double quotes.
```
 "scripts": {
    "runFeaturesNotIgnore": "node_modules\\.bin\\cypress run --env tags=\"not @ignore\" --headed",
  },
```

**Comment by badeball** [comment]
Closing as not an issue with the preprocessor.
