### ISSUE TITLE
Scenario fails with Error Message "Expected to find internal spec properties with reference = 2 "

### ISSUE THREAD

**Issue by SaiManojKumarYerra** [badeball/cypress-cucumber-preprocessor#991]
### Current behavior

Cypress - Cucumber Framework is included with  "experimentalRunAllSpecs" as true. If we execute the all specs at a time,  one of the scenario get fails showing the error message as below
<img width="225" alt="Error Message" src="https://user-images.githubusercontent.com/86812591/231145453-51168552-1a70-4b03-9670-b0cfa963083c.png">
<img width="769" alt="Enabled Run All Specs" src="https://user-images.githubusercontent.com/86812591/231145804-d9a774b7-9ce7-488c-bd93-50389261128d.png">

If we execute each feature file, script is working fine. Issues happen only, when we use "Run All Specs"

### Desired behavior

Expected to execute all the scenarios to without any issues with "Run All Specs"

### Test code to reproduce

Unfortunately. I couldn't share the test code here

### Versions

* **Cypress version**:  12.9.0
* **@badeball/cypress-cucumber-preprocessorversion**:  16.0.3
* **@bahmutov/cypress-esbuild-preprocessor version**:  2.2.0
* **Node version**:  18.13.0

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by r6q** [comment]
Updated everything related to cypres to latest version as of today.
* cypress: 12.11.0
* cypress-localstorage-commands: 2.2.3
* @badeball/cypress-cucumber-preprocessor: 16.0.3
* @bahmutov/cypress-esbuild-preprocessor: 2.2.0
* @cypress/webpack-preprocessor: 5.17.0
* node: 18.14.2 

Chrome: 112
MacOS: Ventura 13.3.1 m1

Also get the same error.

---

Expected to find internal spec properties with reference = 10 (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a after each hook we are skipping all of the remaining tests.
```
[node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:7:1](http://localhost:4200/__/#)
   5 | const package_json_1 = require("../package.json");
   6 | function createError(message) {
>  7 |     return new Error(`${message} (this might be a bug, please report at ${package_json_1.homepage})`);
     | ^
   8 | }
   9 | exports.createError = createError;
  10 | function fail(message) { 
View stack trace
 Print to console
at createError ([webpack://my-webapp/./node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:7](http://localhost:4200/__/#))
at fail ([webpack://my-webapp/./node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:11](http://localhost:4200/__/#))
at assert ([webpack://my-webapp/./node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:18](http://localhost:4200/__/#))
at assertAndReturn ([webpack://my-webapp/./node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:22](http://localhost:4200/__/#))
at retrieveInternalSpecProperties ([webpack://my-webapp/./node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:36](http://localhost:4200/__/#))
at Context.eval ([webpack://my-webapp/./node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:452](http://localhost:4200/__/#))
```

Unfortunately as most of the people I cannot upload my company's code.

The error occurs only when running `All Spec` (15 in my case) and it fails somewhere semi-randomly in the middle of ~50 tests. Running features separately work perfectly fine.

@badeball maybe you can give some clues or pointers what we can try? 

Unfortuntely nobody will write a fresh frontend app (and maybe backend) with a lot of features in hopes to maybe reproduce a bug in regards to [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case)

**Comment by badeball** [comment]
I think I've already made myself clear.

**Comment by badeball** [comment]
Closing due to lack of reproducible example. Feel free to open up another issue if anything changes in this regard.
